// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	strconv "strconv"
)

type AccountType uint16

// AccountType_TypeID is the unique identifier for the type AccountType.
const AccountType_TypeID = 0xa309701d252a3266

// Values of AccountType.
const (
	AccountType_unknown            AccountType = 0
	AccountType_claudeSubscription AccountType = 1
	AccountType_claudePayAsYouGo   AccountType = 2
	AccountType_codexSubscription  AccountType = 3
	AccountType_geminiSubscription AccountType = 4
	AccountType_geminiApiKey       AccountType = 5
	AccountType_awsBedrock         AccountType = 6
)

// String returns the enum's constant name.
func (c AccountType) String() string {
	switch c {
	case AccountType_unknown:
		return "unknown"
	case AccountType_claudeSubscription:
		return "claudeSubscription"
	case AccountType_claudePayAsYouGo:
		return "claudePayAsYouGo"
	case AccountType_codexSubscription:
		return "codexSubscription"
	case AccountType_geminiSubscription:
		return "geminiSubscription"
	case AccountType_geminiApiKey:
		return "geminiApiKey"
	case AccountType_awsBedrock:
		return "awsBedrock"

	default:
		return ""
	}
}

// AccountTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func AccountTypeFromString(c string) AccountType {
	switch c {
	case "unknown":
		return AccountType_unknown
	case "claudeSubscription":
		return AccountType_claudeSubscription
	case "claudePayAsYouGo":
		return AccountType_claudePayAsYouGo
	case "codexSubscription":
		return AccountType_codexSubscription
	case "geminiSubscription":
		return AccountType_geminiSubscription
	case "geminiApiKey":
		return AccountType_geminiApiKey
	case "awsBedrock":
		return AccountType_awsBedrock

	default:
		return 0
	}
}

type AccountType_List = capnp.EnumList[AccountType]

func NewAccountType_List(s *capnp.Segment, sz int32) (AccountType_List, error) {
	return capnp.NewEnumList[AccountType](s, sz)
}

type ClaudeTokenCredentials capnp.Struct

// ClaudeTokenCredentials_TypeID is the unique identifier for the type ClaudeTokenCredentials.
const ClaudeTokenCredentials_TypeID = 0xf49df8ad98c6b0a0

func NewClaudeTokenCredentials(s *capnp.Segment) (ClaudeTokenCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeTokenCredentials(st), err
}

func NewRootClaudeTokenCredentials(s *capnp.Segment) (ClaudeTokenCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeTokenCredentials(st), err
}

func ReadRootClaudeTokenCredentials(msg *capnp.Message) (ClaudeTokenCredentials, error) {
	root, err := msg.Root()
	return ClaudeTokenCredentials(root.Struct()), err
}

func (s ClaudeTokenCredentials) String() string {
	str, _ := text.Marshal(0xf49df8ad98c6b0a0, capnp.Struct(s))
	return str
}

func (s ClaudeTokenCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeTokenCredentials) DecodeFromPtr(p capnp.Ptr) ClaudeTokenCredentials {
	return ClaudeTokenCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeTokenCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeTokenCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeTokenCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeTokenCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeTokenCredentials) AccessToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeTokenCredentials) HasAccessToken() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeTokenCredentials) AccessTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeTokenCredentials) SetAccessToken(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeTokenCredentials) RefreshToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeTokenCredentials) HasRefreshToken() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeTokenCredentials) RefreshTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeTokenCredentials) SetRefreshToken(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ClaudeTokenCredentials_List is a list of ClaudeTokenCredentials.
type ClaudeTokenCredentials_List = capnp.StructList[ClaudeTokenCredentials]

// NewClaudeTokenCredentials creates a new list of ClaudeTokenCredentials.
func NewClaudeTokenCredentials_List(s *capnp.Segment, sz int32) (ClaudeTokenCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ClaudeTokenCredentials](l), err
}

// ClaudeTokenCredentials_Future is a wrapper for a ClaudeTokenCredentials promised by a client call.
type ClaudeTokenCredentials_Future struct{ *capnp.Future }

func (f ClaudeTokenCredentials_Future) Struct() (ClaudeTokenCredentials, error) {
	p, err := f.Future.Ptr()
	return ClaudeTokenCredentials(p.Struct()), err
}

type ClaudeApiKeyCredentials capnp.Struct

// ClaudeApiKeyCredentials_TypeID is the unique identifier for the type ClaudeApiKeyCredentials.
const ClaudeApiKeyCredentials_TypeID = 0x8ef23c1999b62e1f

func NewClaudeApiKeyCredentials(s *capnp.Segment) (ClaudeApiKeyCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeApiKeyCredentials(st), err
}

func NewRootClaudeApiKeyCredentials(s *capnp.Segment) (ClaudeApiKeyCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeApiKeyCredentials(st), err
}

func ReadRootClaudeApiKeyCredentials(msg *capnp.Message) (ClaudeApiKeyCredentials, error) {
	root, err := msg.Root()
	return ClaudeApiKeyCredentials(root.Struct()), err
}

func (s ClaudeApiKeyCredentials) String() string {
	str, _ := text.Marshal(0x8ef23c1999b62e1f, capnp.Struct(s))
	return str
}

func (s ClaudeApiKeyCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeApiKeyCredentials) DecodeFromPtr(p capnp.Ptr) ClaudeApiKeyCredentials {
	return ClaudeApiKeyCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeApiKeyCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeApiKeyCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeApiKeyCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeApiKeyCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeApiKeyCredentials) ApiKey() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeApiKeyCredentials) HasApiKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeApiKeyCredentials) ApiKeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeApiKeyCredentials) SetApiKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeApiKeyCredentials) BaseUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeApiKeyCredentials) HasBaseUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeApiKeyCredentials) BaseUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeApiKeyCredentials) SetBaseUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ClaudeApiKeyCredentials_List is a list of ClaudeApiKeyCredentials.
type ClaudeApiKeyCredentials_List = capnp.StructList[ClaudeApiKeyCredentials]

// NewClaudeApiKeyCredentials creates a new list of ClaudeApiKeyCredentials.
func NewClaudeApiKeyCredentials_List(s *capnp.Segment, sz int32) (ClaudeApiKeyCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ClaudeApiKeyCredentials](l), err
}

// ClaudeApiKeyCredentials_Future is a wrapper for a ClaudeApiKeyCredentials promised by a client call.
type ClaudeApiKeyCredentials_Future struct{ *capnp.Future }

func (f ClaudeApiKeyCredentials_Future) Struct() (ClaudeApiKeyCredentials, error) {
	p, err := f.Future.Ptr()
	return ClaudeApiKeyCredentials(p.Struct()), err
}

type AccountCredentials capnp.Struct
type AccountCredentials_Which uint16

const (
	AccountCredentials_Which_none              AccountCredentials_Which = 0
	AccountCredentials_Which_claudeSubCreds    AccountCredentials_Which = 1
	AccountCredentials_Which_claudeApiKeyCreds AccountCredentials_Which = 2
)

func (w AccountCredentials_Which) String() string {
	const s = "noneclaudeSubCredsclaudeApiKeyCreds"
	switch w {
	case AccountCredentials_Which_none:
		return s[0:4]
	case AccountCredentials_Which_claudeSubCreds:
		return s[4:18]
	case AccountCredentials_Which_claudeApiKeyCreds:
		return s[18:35]

	}
	return "AccountCredentials_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// AccountCredentials_TypeID is the unique identifier for the type AccountCredentials.
const AccountCredentials_TypeID = 0xc80017a258c68a97

func NewAccountCredentials(s *capnp.Segment) (AccountCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountCredentials(st), err
}

func NewRootAccountCredentials(s *capnp.Segment) (AccountCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountCredentials(st), err
}

func ReadRootAccountCredentials(msg *capnp.Message) (AccountCredentials, error) {
	root, err := msg.Root()
	return AccountCredentials(root.Struct()), err
}

func (s AccountCredentials) String() string {
	str, _ := text.Marshal(0xc80017a258c68a97, capnp.Struct(s))
	return str
}

func (s AccountCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountCredentials) DecodeFromPtr(p capnp.Ptr) AccountCredentials {
	return AccountCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s AccountCredentials) Which() AccountCredentials_Which {
	return AccountCredentials_Which(capnp.Struct(s).Uint16(0))
}
func (s AccountCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountCredentials) SetNone() {
	capnp.Struct(s).SetUint16(0, 0)

}

func (s AccountCredentials) ClaudeSubCreds() (ClaudeTokenCredentials, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != claudeSubCreds")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ClaudeTokenCredentials(p.Struct()), err
}

func (s AccountCredentials) HasClaudeSubCreds() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountCredentials) SetClaudeSubCreds(v ClaudeTokenCredentials) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClaudeSubCreds sets the claudeSubCreds field to a newly
// allocated ClaudeTokenCredentials struct, preferring placement in s's segment.
func (s AccountCredentials) NewClaudeSubCreds() (ClaudeTokenCredentials, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewClaudeTokenCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeTokenCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s AccountCredentials) ClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != claudeApiKeyCreds")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ClaudeApiKeyCredentials(p.Struct()), err
}

func (s AccountCredentials) HasClaudeApiKeyCreds() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountCredentials) SetClaudeApiKeyCreds(v ClaudeApiKeyCredentials) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClaudeApiKeyCreds sets the claudeApiKeyCreds field to a newly
// allocated ClaudeApiKeyCredentials struct, preferring placement in s's segment.
func (s AccountCredentials) NewClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewClaudeApiKeyCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeApiKeyCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountCredentials_List is a list of AccountCredentials.
type AccountCredentials_List = capnp.StructList[AccountCredentials]

// NewAccountCredentials creates a new list of AccountCredentials.
func NewAccountCredentials_List(s *capnp.Segment, sz int32) (AccountCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountCredentials](l), err
}

// AccountCredentials_Future is a wrapper for a AccountCredentials promised by a client call.
type AccountCredentials_Future struct{ *capnp.Future }

func (f AccountCredentials_Future) Struct() (AccountCredentials, error) {
	p, err := f.Future.Ptr()
	return AccountCredentials(p.Struct()), err
}
func (p AccountCredentials_Future) ClaudeSubCreds() ClaudeTokenCredentials_Future {
	return ClaudeTokenCredentials_Future{Future: p.Future.Field(0, nil)}
}
func (p AccountCredentials_Future) ClaudeApiKeyCreds() ClaudeApiKeyCredentials_Future {
	return ClaudeApiKeyCredentials_Future{Future: p.Future.Field(0, nil)}
}

type AccountInfo capnp.Struct

// AccountInfo_TypeID is the unique identifier for the type AccountInfo.
const AccountInfo_TypeID = 0xde341fe554ef796d

func NewAccountInfo(s *capnp.Segment) (AccountInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountInfo(st), err
}

func NewRootAccountInfo(s *capnp.Segment) (AccountInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountInfo(st), err
}

func ReadRootAccountInfo(msg *capnp.Message) (AccountInfo, error) {
	root, err := msg.Root()
	return AccountInfo(root.Struct()), err
}

func (s AccountInfo) String() string {
	str, _ := text.Marshal(0xde341fe554ef796d, capnp.Struct(s))
	return str
}

func (s AccountInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountInfo) DecodeFromPtr(p capnp.Ptr) AccountInfo {
	return AccountInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountInfo) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountInfo) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountInfo) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountInfo) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountInfo) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountInfo) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountInfo) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountInfo) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountInfo) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountInfo) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountInfo) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountInfo) HasVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountInfo) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountInfo) SetVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountInfo) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s AccountInfo) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s AccountInfo) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountInfo) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountInfo) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountInfo) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountInfo) Credentials() (AccountCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return AccountCredentials(p.Struct()), err
}

func (s AccountInfo) HasCredentials() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountInfo) SetCredentials(v AccountCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewCredentials sets the credentials field to a newly
// allocated AccountCredentials struct, preferring placement in s's segment.
func (s AccountInfo) NewCredentials() (AccountCredentials, error) {
	ss, err := NewAccountCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return AccountCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountInfo_List is a list of AccountInfo.
type AccountInfo_List = capnp.StructList[AccountInfo]

// NewAccountInfo creates a new list of AccountInfo.
func NewAccountInfo_List(s *capnp.Segment, sz int32) (AccountInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5}, sz)
	return capnp.StructList[AccountInfo](l), err
}

// AccountInfo_Future is a wrapper for a AccountInfo promised by a client call.
type AccountInfo_Future struct{ *capnp.Future }

func (f AccountInfo_Future) Struct() (AccountInfo, error) {
	p, err := f.Future.Ptr()
	return AccountInfo(p.Struct()), err
}
func (p AccountInfo_Future) Credentials() AccountCredentials_Future {
	return AccountCredentials_Future{Future: p.Future.Field(4, nil)}
}

type AccountService capnp.Client

// AccountService_TypeID is the unique identifier for the type AccountService.
const AccountService_TypeID = 0x8a9179019ae6c648

func (c AccountService) RegisterAccount(ctx context.Context, params func(AccountService_registerAccount_Params) error) (AccountService_registerAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      0,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "registerAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 5}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_registerAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_registerAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) UpdateAccount(ctx context.Context, params func(AccountService_updateAccount_Params) error) (AccountService_updateAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      1,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "updateAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 6}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_updateAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_updateAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) RemoveAccount(ctx context.Context, params func(AccountService_removeAccount_Params) error) (AccountService_removeAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      2,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "removeAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_removeAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_removeAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) ListAccounts(ctx context.Context, params func(AccountService_listAccounts_Params) error) (AccountService_listAccounts_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      3,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "listAccounts",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_listAccounts_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_listAccounts_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c AccountService) String() string {
	return "AccountService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c AccountService) AddRef() AccountService {
	return AccountService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c AccountService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c AccountService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c AccountService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (AccountService) DecodeFromPtr(p capnp.Ptr) AccountService {
	return AccountService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c AccountService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c AccountService) IsSame(other AccountService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c AccountService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c AccountService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A AccountService_Server is a AccountService with a local implementation.
type AccountService_Server interface {
	RegisterAccount(context.Context, AccountService_registerAccount) error

	UpdateAccount(context.Context, AccountService_updateAccount) error

	RemoveAccount(context.Context, AccountService_removeAccount) error

	ListAccounts(context.Context, AccountService_listAccounts) error
}

// AccountService_NewServer creates a new Server from an implementation of AccountService_Server.
func AccountService_NewServer(s AccountService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(AccountService_Methods(nil, s), s, c)
}

// AccountService_ServerToClient creates a new Client from an implementation of AccountService_Server.
// The caller is responsible for calling Release on the returned Client.
func AccountService_ServerToClient(s AccountService_Server) AccountService {
	return AccountService(capnp.NewClient(AccountService_NewServer(s)))
}

// AccountService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func AccountService_Methods(methods []server.Method, s AccountService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      0,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "registerAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RegisterAccount(ctx, AccountService_registerAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      1,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "updateAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.UpdateAccount(ctx, AccountService_updateAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      2,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "removeAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RemoveAccount(ctx, AccountService_removeAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      3,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "listAccounts",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListAccounts(ctx, AccountService_listAccounts{call})
		},
	})

	return methods
}

// AccountService_registerAccount holds the state for a server call to AccountService.registerAccount.
// See server.Call for documentation.
type AccountService_registerAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_registerAccount) Args() AccountService_registerAccount_Params {
	return AccountService_registerAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_registerAccount) AllocResults() (AccountService_registerAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(r), err
}

// AccountService_updateAccount holds the state for a server call to AccountService.updateAccount.
// See server.Call for documentation.
type AccountService_updateAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_updateAccount) Args() AccountService_updateAccount_Params {
	return AccountService_updateAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_updateAccount) AllocResults() (AccountService_updateAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(r), err
}

// AccountService_removeAccount holds the state for a server call to AccountService.removeAccount.
// See server.Call for documentation.
type AccountService_removeAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_removeAccount) Args() AccountService_removeAccount_Params {
	return AccountService_removeAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_removeAccount) AllocResults() (AccountService_removeAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(r), err
}

// AccountService_listAccounts holds the state for a server call to AccountService.listAccounts.
// See server.Call for documentation.
type AccountService_listAccounts struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_listAccounts) Args() AccountService_listAccounts_Params {
	return AccountService_listAccounts_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_listAccounts) AllocResults() (AccountService_listAccounts_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(r), err
}

// AccountService_List is a list of AccountService.
type AccountService_List = capnp.CapList[AccountService]

// NewAccountService_List creates a new list of AccountService.
func NewAccountService_List(s *capnp.Segment, sz int32) (AccountService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[AccountService](l), err
}

type AccountService_registerAccount_Params capnp.Struct

// AccountService_registerAccount_Params_TypeID is the unique identifier for the type AccountService_registerAccount_Params.
const AccountService_registerAccount_Params_TypeID = 0xa77c56c45e37a0a1

func NewAccountService_registerAccount_Params(s *capnp.Segment) (AccountService_registerAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountService_registerAccount_Params(st), err
}

func NewRootAccountService_registerAccount_Params(s *capnp.Segment) (AccountService_registerAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountService_registerAccount_Params(st), err
}

func ReadRootAccountService_registerAccount_Params(msg *capnp.Message) (AccountService_registerAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_registerAccount_Params(root.Struct()), err
}

func (s AccountService_registerAccount_Params) String() string {
	str, _ := text.Marshal(0xa77c56c45e37a0a1, capnp.Struct(s))
	return str
}

func (s AccountService_registerAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_registerAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_registerAccount_Params {
	return AccountService_registerAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_registerAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_registerAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_registerAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_registerAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_registerAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_registerAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountService_registerAccount_Params) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountService_registerAccount_Params) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountService_registerAccount_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountService_registerAccount_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountService_registerAccount_Params) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountService_registerAccount_Params) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountService_registerAccount_Params) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountService_registerAccount_Params) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountService_registerAccount_Params) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s AccountService_registerAccount_Params) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s AccountService_registerAccount_Params) Credentials() (AccountCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return AccountCredentials(p.Struct()), err
}

func (s AccountService_registerAccount_Params) HasCredentials() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountService_registerAccount_Params) SetCredentials(v AccountCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewCredentials sets the credentials field to a newly
// allocated AccountCredentials struct, preferring placement in s's segment.
func (s AccountService_registerAccount_Params) NewCredentials() (AccountCredentials, error) {
	ss, err := NewAccountCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return AccountCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountService_registerAccount_Params_List is a list of AccountService_registerAccount_Params.
type AccountService_registerAccount_Params_List = capnp.StructList[AccountService_registerAccount_Params]

// NewAccountService_registerAccount_Params creates a new list of AccountService_registerAccount_Params.
func NewAccountService_registerAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_registerAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5}, sz)
	return capnp.StructList[AccountService_registerAccount_Params](l), err
}

// AccountService_registerAccount_Params_Future is a wrapper for a AccountService_registerAccount_Params promised by a client call.
type AccountService_registerAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_registerAccount_Params_Future) Struct() (AccountService_registerAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_registerAccount_Params(p.Struct()), err
}
func (p AccountService_registerAccount_Params_Future) Credentials() AccountCredentials_Future {
	return AccountCredentials_Future{Future: p.Future.Field(4, nil)}
}

type AccountService_registerAccount_Results capnp.Struct

// AccountService_registerAccount_Results_TypeID is the unique identifier for the type AccountService_registerAccount_Results.
const AccountService_registerAccount_Results_TypeID = 0xcd61f2c9baeb2c70

func NewAccountService_registerAccount_Results(s *capnp.Segment) (AccountService_registerAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(st), err
}

func NewRootAccountService_registerAccount_Results(s *capnp.Segment) (AccountService_registerAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(st), err
}

func ReadRootAccountService_registerAccount_Results(msg *capnp.Message) (AccountService_registerAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_registerAccount_Results(root.Struct()), err
}

func (s AccountService_registerAccount_Results) String() string {
	str, _ := text.Marshal(0xcd61f2c9baeb2c70, capnp.Struct(s))
	return str
}

func (s AccountService_registerAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_registerAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_registerAccount_Results {
	return AccountService_registerAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_registerAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_registerAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_registerAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_registerAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_registerAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_registerAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_registerAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_registerAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_registerAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_registerAccount_Results_List is a list of AccountService_registerAccount_Results.
type AccountService_registerAccount_Results_List = capnp.StructList[AccountService_registerAccount_Results]

// NewAccountService_registerAccount_Results creates a new list of AccountService_registerAccount_Results.
func NewAccountService_registerAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_registerAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_registerAccount_Results](l), err
}

// AccountService_registerAccount_Results_Future is a wrapper for a AccountService_registerAccount_Results promised by a client call.
type AccountService_registerAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_registerAccount_Results_Future) Struct() (AccountService_registerAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_registerAccount_Results(p.Struct()), err
}

type AccountService_updateAccount_Params capnp.Struct

// AccountService_updateAccount_Params_TypeID is the unique identifier for the type AccountService_updateAccount_Params.
const AccountService_updateAccount_Params_TypeID = 0x891fa8b6066a4ed5

func NewAccountService_updateAccount_Params(s *capnp.Segment) (AccountService_updateAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return AccountService_updateAccount_Params(st), err
}

func NewRootAccountService_updateAccount_Params(s *capnp.Segment) (AccountService_updateAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return AccountService_updateAccount_Params(st), err
}

func ReadRootAccountService_updateAccount_Params(msg *capnp.Message) (AccountService_updateAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_updateAccount_Params(root.Struct()), err
}

func (s AccountService_updateAccount_Params) String() string {
	str, _ := text.Marshal(0x891fa8b6066a4ed5, capnp.Struct(s))
	return str
}

func (s AccountService_updateAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_updateAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_updateAccount_Params {
	return AccountService_updateAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_updateAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_updateAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_updateAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_updateAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_updateAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_updateAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountService_updateAccount_Params) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountService_updateAccount_Params) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountService_updateAccount_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountService_updateAccount_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountService_updateAccount_Params) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountService_updateAccount_Params) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountService_updateAccount_Params) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasVersion() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountService_updateAccount_Params) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetVersion(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountService_updateAccount_Params) ClaudeSubCreds() (ClaudeTokenCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return ClaudeTokenCredentials(p.Struct()), err
}

func (s AccountService_updateAccount_Params) HasClaudeSubCreds() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountService_updateAccount_Params) SetClaudeSubCreds(v ClaudeTokenCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewClaudeSubCreds sets the claudeSubCreds field to a newly
// allocated ClaudeTokenCredentials struct, preferring placement in s's segment.
func (s AccountService_updateAccount_Params) NewClaudeSubCreds() (ClaudeTokenCredentials, error) {
	ss, err := NewClaudeTokenCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeTokenCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s AccountService_updateAccount_Params) ClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return ClaudeApiKeyCredentials(p.Struct()), err
}

func (s AccountService_updateAccount_Params) HasClaudeApiKeyCreds() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s AccountService_updateAccount_Params) SetClaudeApiKeyCreds(v ClaudeApiKeyCredentials) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewClaudeApiKeyCreds sets the claudeApiKeyCreds field to a newly
// allocated ClaudeApiKeyCredentials struct, preferring placement in s's segment.
func (s AccountService_updateAccount_Params) NewClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	ss, err := NewClaudeApiKeyCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeApiKeyCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountService_updateAccount_Params_List is a list of AccountService_updateAccount_Params.
type AccountService_updateAccount_Params_List = capnp.StructList[AccountService_updateAccount_Params]

// NewAccountService_updateAccount_Params creates a new list of AccountService_updateAccount_Params.
func NewAccountService_updateAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_updateAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6}, sz)
	return capnp.StructList[AccountService_updateAccount_Params](l), err
}

// AccountService_updateAccount_Params_Future is a wrapper for a AccountService_updateAccount_Params promised by a client call.
type AccountService_updateAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_updateAccount_Params_Future) Struct() (AccountService_updateAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_updateAccount_Params(p.Struct()), err
}
func (p AccountService_updateAccount_Params_Future) ClaudeSubCreds() ClaudeTokenCredentials_Future {
	return ClaudeTokenCredentials_Future{Future: p.Future.Field(4, nil)}
}
func (p AccountService_updateAccount_Params_Future) ClaudeApiKeyCreds() ClaudeApiKeyCredentials_Future {
	return ClaudeApiKeyCredentials_Future{Future: p.Future.Field(5, nil)}
}

type AccountService_updateAccount_Results capnp.Struct

// AccountService_updateAccount_Results_TypeID is the unique identifier for the type AccountService_updateAccount_Results.
const AccountService_updateAccount_Results_TypeID = 0xe83dabed9b090802

func NewAccountService_updateAccount_Results(s *capnp.Segment) (AccountService_updateAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(st), err
}

func NewRootAccountService_updateAccount_Results(s *capnp.Segment) (AccountService_updateAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(st), err
}

func ReadRootAccountService_updateAccount_Results(msg *capnp.Message) (AccountService_updateAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_updateAccount_Results(root.Struct()), err
}

func (s AccountService_updateAccount_Results) String() string {
	str, _ := text.Marshal(0xe83dabed9b090802, capnp.Struct(s))
	return str
}

func (s AccountService_updateAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_updateAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_updateAccount_Results {
	return AccountService_updateAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_updateAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_updateAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_updateAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_updateAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_updateAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_updateAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_updateAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_updateAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_updateAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_updateAccount_Results_List is a list of AccountService_updateAccount_Results.
type AccountService_updateAccount_Results_List = capnp.StructList[AccountService_updateAccount_Results]

// NewAccountService_updateAccount_Results creates a new list of AccountService_updateAccount_Results.
func NewAccountService_updateAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_updateAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_updateAccount_Results](l), err
}

// AccountService_updateAccount_Results_Future is a wrapper for a AccountService_updateAccount_Results promised by a client call.
type AccountService_updateAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_updateAccount_Results_Future) Struct() (AccountService_updateAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_updateAccount_Results(p.Struct()), err
}

type AccountService_removeAccount_Params capnp.Struct

// AccountService_removeAccount_Params_TypeID is the unique identifier for the type AccountService_removeAccount_Params.
const AccountService_removeAccount_Params_TypeID = 0xcfdc97e955c82412

func NewAccountService_removeAccount_Params(s *capnp.Segment) (AccountService_removeAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_removeAccount_Params(st), err
}

func NewRootAccountService_removeAccount_Params(s *capnp.Segment) (AccountService_removeAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_removeAccount_Params(st), err
}

func ReadRootAccountService_removeAccount_Params(msg *capnp.Message) (AccountService_removeAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_removeAccount_Params(root.Struct()), err
}

func (s AccountService_removeAccount_Params) String() string {
	str, _ := text.Marshal(0xcfdc97e955c82412, capnp.Struct(s))
	return str
}

func (s AccountService_removeAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_removeAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_removeAccount_Params {
	return AccountService_removeAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_removeAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_removeAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_removeAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_removeAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_removeAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_removeAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_removeAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_removeAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_removeAccount_Params_List is a list of AccountService_removeAccount_Params.
type AccountService_removeAccount_Params_List = capnp.StructList[AccountService_removeAccount_Params]

// NewAccountService_removeAccount_Params creates a new list of AccountService_removeAccount_Params.
func NewAccountService_removeAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_removeAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_removeAccount_Params](l), err
}

// AccountService_removeAccount_Params_Future is a wrapper for a AccountService_removeAccount_Params promised by a client call.
type AccountService_removeAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_removeAccount_Params_Future) Struct() (AccountService_removeAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_removeAccount_Params(p.Struct()), err
}

type AccountService_removeAccount_Results capnp.Struct

// AccountService_removeAccount_Results_TypeID is the unique identifier for the type AccountService_removeAccount_Results.
const AccountService_removeAccount_Results_TypeID = 0xf69c1e2bdba142bf

func NewAccountService_removeAccount_Results(s *capnp.Segment) (AccountService_removeAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(st), err
}

func NewRootAccountService_removeAccount_Results(s *capnp.Segment) (AccountService_removeAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(st), err
}

func ReadRootAccountService_removeAccount_Results(msg *capnp.Message) (AccountService_removeAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_removeAccount_Results(root.Struct()), err
}

func (s AccountService_removeAccount_Results) String() string {
	str, _ := text.Marshal(0xf69c1e2bdba142bf, capnp.Struct(s))
	return str
}

func (s AccountService_removeAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_removeAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_removeAccount_Results {
	return AccountService_removeAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_removeAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_removeAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_removeAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_removeAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_removeAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_removeAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_removeAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_removeAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_removeAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_removeAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_removeAccount_Results_List is a list of AccountService_removeAccount_Results.
type AccountService_removeAccount_Results_List = capnp.StructList[AccountService_removeAccount_Results]

// NewAccountService_removeAccount_Results creates a new list of AccountService_removeAccount_Results.
func NewAccountService_removeAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_removeAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_removeAccount_Results](l), err
}

// AccountService_removeAccount_Results_Future is a wrapper for a AccountService_removeAccount_Results promised by a client call.
type AccountService_removeAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_removeAccount_Results_Future) Struct() (AccountService_removeAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_removeAccount_Results(p.Struct()), err
}

type AccountService_listAccounts_Params capnp.Struct

// AccountService_listAccounts_Params_TypeID is the unique identifier for the type AccountService_listAccounts_Params.
const AccountService_listAccounts_Params_TypeID = 0x92070f51247244e5

func NewAccountService_listAccounts_Params(s *capnp.Segment) (AccountService_listAccounts_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AccountService_listAccounts_Params(st), err
}

func NewRootAccountService_listAccounts_Params(s *capnp.Segment) (AccountService_listAccounts_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AccountService_listAccounts_Params(st), err
}

func ReadRootAccountService_listAccounts_Params(msg *capnp.Message) (AccountService_listAccounts_Params, error) {
	root, err := msg.Root()
	return AccountService_listAccounts_Params(root.Struct()), err
}

func (s AccountService_listAccounts_Params) String() string {
	str, _ := text.Marshal(0x92070f51247244e5, capnp.Struct(s))
	return str
}

func (s AccountService_listAccounts_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_listAccounts_Params) DecodeFromPtr(p capnp.Ptr) AccountService_listAccounts_Params {
	return AccountService_listAccounts_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_listAccounts_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_listAccounts_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_listAccounts_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_listAccounts_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// AccountService_listAccounts_Params_List is a list of AccountService_listAccounts_Params.
type AccountService_listAccounts_Params_List = capnp.StructList[AccountService_listAccounts_Params]

// NewAccountService_listAccounts_Params creates a new list of AccountService_listAccounts_Params.
func NewAccountService_listAccounts_Params_List(s *capnp.Segment, sz int32) (AccountService_listAccounts_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[AccountService_listAccounts_Params](l), err
}

// AccountService_listAccounts_Params_Future is a wrapper for a AccountService_listAccounts_Params promised by a client call.
type AccountService_listAccounts_Params_Future struct{ *capnp.Future }

func (f AccountService_listAccounts_Params_Future) Struct() (AccountService_listAccounts_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_listAccounts_Params(p.Struct()), err
}

type AccountService_listAccounts_Results capnp.Struct

// AccountService_listAccounts_Results_TypeID is the unique identifier for the type AccountService_listAccounts_Results.
const AccountService_listAccounts_Results_TypeID = 0xeb097c133ce0ccbe

func NewAccountService_listAccounts_Results(s *capnp.Segment) (AccountService_listAccounts_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(st), err
}

func NewRootAccountService_listAccounts_Results(s *capnp.Segment) (AccountService_listAccounts_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(st), err
}

func ReadRootAccountService_listAccounts_Results(msg *capnp.Message) (AccountService_listAccounts_Results, error) {
	root, err := msg.Root()
	return AccountService_listAccounts_Results(root.Struct()), err
}

func (s AccountService_listAccounts_Results) String() string {
	str, _ := text.Marshal(0xeb097c133ce0ccbe, capnp.Struct(s))
	return str
}

func (s AccountService_listAccounts_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_listAccounts_Results) DecodeFromPtr(p capnp.Ptr) AccountService_listAccounts_Results {
	return AccountService_listAccounts_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_listAccounts_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_listAccounts_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_listAccounts_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_listAccounts_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_listAccounts_Results) Accounts() (AccountInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return AccountInfo_List(p.List()), err
}

func (s AccountService_listAccounts_Results) HasAccounts() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_listAccounts_Results) SetAccounts(v AccountInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewAccounts sets the accounts field to a newly
// allocated AccountInfo_List, preferring placement in s's segment.
func (s AccountService_listAccounts_Results) NewAccounts(n int32) (AccountInfo_List, error) {
	l, err := NewAccountInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return AccountInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// AccountService_listAccounts_Results_List is a list of AccountService_listAccounts_Results.
type AccountService_listAccounts_Results_List = capnp.StructList[AccountService_listAccounts_Results]

// NewAccountService_listAccounts_Results creates a new list of AccountService_listAccounts_Results.
func NewAccountService_listAccounts_Results_List(s *capnp.Segment, sz int32) (AccountService_listAccounts_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_listAccounts_Results](l), err
}

// AccountService_listAccounts_Results_Future is a wrapper for a AccountService_listAccounts_Results promised by a client call.
type AccountService_listAccounts_Results_Future struct{ *capnp.Future }

func (f AccountService_listAccounts_Results_Future) Struct() (AccountService_listAccounts_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_listAccounts_Results(p.Struct()), err
}

const schema_b1c2d3e4f5a6b7c8 = "x\xda\xec[}x\x14\xe5\xb5?g&\xc9&\x08l" +
	"\x86I*TdQC$\x01\x83I\xa4\xd5<\xd0\x90" +
	"`*IA3\xf9h-\xad\xcadwH&\xd9\xcc" +
	",3\xb3\xc8r\xb1h\x1f\xbdWhm\x05E\x85J" +
	"\x0b\xf6C\xa1\xf5Vh\x15\xf1\xd6\xb6\xd2j\xc5j+" +
	"Z\xae`\xb5\x8f\xdcJ\xeb\x07V\xf1\xd2\x0f\xabt\xef" +
	"s\xde\x99wf6,!\xf1\xa1\xcf\xfd\xa7\xff\xc0\xce" +
	"\x99w\xde\x8f\xf3\xf9;\xe7\xbc\xb9P-\x9dWP;" +
	"n\xd6Y t\xce\xc1\xc2\xa2\xec\xad\xdb\x96\xae{\xed" +
	"\xfa\xea\x1b@\xaaD\x80B\x8c\x00\xd4_7n\x0f\x02" +
	"\xca\xb7\x8ck\x04\xcc\x0a\xdd%\xffV\xf2\x9e}3(" +
	"\x93\x90F\x084b\xc7\xb8\x1e\x1a\xf1\xe8\xb8\xef\x03f" +
	"\xcfZ\xb6e\xfb\x9b\x8f\x7f\xfff\x90\xce\xf6\xa7\xf8\xec" +
	"\xf8{h\x80>\x9e\xa6\xd8\x7fy\x7f\xd1C\xf7\xc5\xd6" +
	"\x80r6\x9b\xa2\x88F\xac\x19\xbf\x1e\x01\xeb7\x8e\xff" +
	"*\x02\x1e\x7fv\xfbW\xf6\xcf\xbe~\x8dR\x81\x02\x1f" +
	"0\xb7\xf49\x1a\xa0\x94\xfe\x02\x01\xb3\x0d\x17\xdfy\xf8" +
	"\xd3\xdbo[\x03\xcaG\xd0_\xa5j\x02\xdb\xc6\xec\x09" +
	"\xd7\x02f\x17<\xf1\x87M\x98Y\xb7\x16\xa4\xf1b\xf6" +
	"\xc9]\xdf\xf9\xf3\xab\xcf\xef\xd9\x01\x80\xf2\x86\x09o\xc8" +
	"['\xd0\xf8\xcd\x13\"(/\x92#\x00\xd9Y\x97\xcf" +
	"\xbf\xa4\xe1\x85\xc4\x97\xc2\x9b\x9e-?B\xd3\xb5\xc8\xb4" +
	"\xe9\xb77\xfc\xfb\xc6\xfd\xbf\xd5\xbe\x02RT\xc8\xdes" +
	"\xf4\x95\x834%\x00\xd6kr5\xcai\x9aD^&" +
	"\xdf\x09\x98\x8d\xd5<\xb4q\xd2\x9cw\xbf\x02\xd2x\x0c" +
	"\x16v\x19\xf5\xa8\\\x87\xf23l\xf0^\x99vyx" +
	"\xcc\xefW\xbep_\xd3W\xc3\xebN+[\xcf\x8eQ" +
	"F\xeb\x1e\xbe\xd4\xaaP\xa2\x91\xf5\xee\x80\x02z\xdf]" +
	"\xb6\x16\xa1 \xdbw\xc7\xdf7\xbd\x93\xdax;(\x95" +
	"\x8c\x05\x85\xf4\xae\xa5\x8c\xf6\\\xdf]\xf6\x19\xe2\xd2\x7f" +
	"\xd6-\xa8\xfc\xd2\x91\xd7o\x0f}\xbc\xa3|\x13}\xbc" +
	"\xfee\xa1x\xe7\xa2\xbf\xdc\x09RT\x0c\x1fG\xdeZ" +
	"\xfe\x86|\x7f9mp[\xf9e\xf2>\xfa\x95\xbd\xf4" +
	"\xafO\xef}\xff\x93\xd7\xdf\x0d\xca8\xc4\xacw\xa2-" +
	"PXL\xc3v\x97?\"?V\xce\x0eW\x9e\xa5E" +
	"WEg\xae\xa9\xfc\xce\xce\xaf\x83\x12E\x0c\xe6.\x14" +
	"i\xcc\xde3\x05\x94\xf7\x9fI\x1f\xee;\xf3\x8f$\xa6" +
	"\x03\xbb_\xfa\xc7\xa67\xbfq\x02_wL\x14P~" +
	"t\"[bb/`v\xdb\x9f\xca\xd7\xdfQ\xb6d" +
	"\x0bH\x13}V\x1d\x9ex.\xb1\xea\xad\x89\xc4\xaa\xab" +
	"\x8fKO\x1d|o\xc5\xd60/\xc7Mb\xba{\xf6" +
	"$\x1a\xb0k\xd6'^,\xf9Q\xff=\x9ccc\x98" +
	"^Mz\x8a\xe9\xd5\xa4{\x05\xc0\xec\xd2\xba\xeaig" +
	"\xa7J\xbe\x09\xd2x!GkfO~Nn\x9aL" +
	"\xbb\x99;\x99\xb4|\xeb\x96\x8f_\xfd\xf3O\xaf\xba\x97" +
	"\x94X\xe0\xdc\xdf=\x99\xd4\xbc~\xefdR\xe2\xecw" +
	"\xe7\xfeqj\xd7m\x0fn\x07\xe9#\xfe~\xf4)\x8b" +
	"i?\xe9)\xb4\x9f\xcdG\xff\xba:\xf2\xbd+\xbf\x0f" +
	"\xcaY\x88\xd9;\xbe\xf7\xe8\x91\xf1\x7fJ\xfe\x12\xca\x85" +
	"\x08\x02\xd4o\x98\xc2\xce\xb6y\x0a\xe9\xc95\xd7\xbc\xbd" +
	"\xe1\xbd\x8fU>\x10\x92\xe4\xf1)L\x0d._\xf2\xb7" +
	"\x9e_\xdd\xf0\x85\x9d\xa17oMy\x84\xde\xbc\xb4\xe9" +
	"\x93\xb1\x87[\xc6<\x04a3zy\x0a;\xee\xd1)" +
	"\xcc\x8c\x9e\x9e\xf1\x1b\x9c\xba\xed\x07\xbbHV\x05Cd" +
	"%\xef\x9d\xfa\xa2\xbc\x7f*}\xb4o\xea\xc7\x899\xb8" +
	"\xe1W\x0f~\xce\xb9\xeca\x90*\xe8@L\xa0\xb5\xe7" +
	"\xed\xa4]6\x9dGL\xb9\xbe\xf91\xf3#w\x14\xed" +
	"\x09\x8b\xe8\xd0y\xd54\xe0\xf5\xf3\xe8\xc4;\xc6\xff\xee" +
	"\xa7\xc5\xabW\xec9A\xedJ*v\xcaR\x05\x93X" +
	"E\x04\xe5G\xe9gV\x887\xfca\xfbk\x0f\xeda" +
	"&\xfc\x03o8\x8d\xfev\xc5\x1b\xf2\x0e6\xfa\xfe\x8a" +
	"\xcbP^7-\x02\xf0\x93;\xd7>q\xe5=g>" +
	"\xa9\x8c\xc7\x90\xd9\xb5`D\x04\xa8\xcfL\x1b\x83\xf2\x1a" +
	"\x1a&\xdf4\x8dvZa\xdc3-\xf9\xd8G\xf7\x82" +
	"$\x8bYw\x1b\xaf>OjWUY\x87\xf2%\x95" +
	"4rv\xe5/\xe4\xdd\xf4+{l\xd7mWW\x1e" +
	"\xf8\xd9S\xae$\x19\x8f\xb7V\xf6\x13\x8f\xaf\x183\xee" +
	"gGV\xbd\xf0\x14(2\x16\x04\x13\xd1\x10\xf9\x96\xca" +
	"w\xe5\x8dl\xa6\x0d\x95\xa4\xea\xbb\xfe7\xf9\xfa\x95\xad" +
	"\xc7\xbcY\\\x87\x909\xbf\x8d\xb8s\xd3\xf9$d_" +
	"\x03r-\xa7E\x88\x08\x88\xf2\xe1\xf3_\x94\x8f\x9eO" +
	"\xd3\xbd\xc5F\x7fr\xd1\x81\x03\xef\xde\xbb\xf1\x97!\xc1" +
	"\x97O_O\x9b\xfa\xc4\xe7\xf6<\xb0n\xe6/~\x19" +
	"\x96S\xe1tf\x08\xe5\xd3\xe9\xf4\xa9\x99o>\xb2\xf7" +
	"]\xf5\x19\xee\x81\x99\xa0\x1e\x9c\xbe\x9dF<>\x9d&" +
	"_\xf9_\x17\x9fY6\xe1\xd9_{S\xb0\xbd\x9eS" +
	"\xc5\xfcam\x15\x0d\x98P\xf1d\xf7\xebw\xbe\xf4\xeb" +
	"\xb0\xb1\xad\xabb\x8ekk\x15\x89\xfa\xd8\xc5G\x1f\x99" +
	"\xfb\xdc\xb6\xe7\xc2\x9bx\xbc\x8a\x94O>XE\x9b\xd8" +
	"\xdc\xdd\xd6\xdaX\xb8\xe47\xe1\x192\xd5\x9bh\xc0\x9a" +
	"j\x9a\xe1@\xe5\xc6\x057\xff\xa4\xfd\x85\xd0\x01\xb7U" +
	"\xef\xa4\x03\xda]\x7f\xe8\xfb\xc2\xc7\x1e~\x11\xa4\x09b" +
	"\xd6\xe3\xf9\x1e\x92\xde\xc6\xeasQ\xdeVMC\xbf]" +
	"\x1dA\xf9\xb33H|\xef_\xb7\xb0\xa7\xed\xadK_" +
	"\x0a\x89\xafiF\x07M4\x98y\xbb\xebp\xec\xa2\xdf" +
	"\x812\x1eC\xf6\xce\xacY\xbe`\xc6s\xf2%3X" +
	"$\x98\xc1\x0c:\xf6\xed[\x9f\x89\xee\xaa\xfa\x1f\x90\xc6" +
	"\x8aYO:\xaf\x92>\xee\x9f\xf9\x94|h&}\xf3" +
	"\xf2\xcc\xcb\xe4\x92\x0bh\xd1\xd6\x99\xb5+\xcf^\xf4\xfe" +
	"\xefC\xbb?:\x93t\xe6\xf8\x8e}\xdbo\xfb\xf4\xd7" +
	"\x0f\xe7X\xe5LA \xab\x9c\xc9\xacR(.\xf9\xda" +
	"[\xdf\x9d\xfbZ\x8ex\xf6\xd60\xd6\x1c\xac!\xee\xbf" +
	"W4\x7f\xd6\xf3\xbb\x9a^\x03iR\x10\xaef1\xd7" +
	"\xd24\x8bx\xf7\xfcO\x176a\xef\x85ox\xdcg" +
	"\x03\xb4Y\x7f\xa7\x01\x196\xe0\xc7O\xbf2G^U" +
	"\xf2f\x98\xfb\x9bg1\xf9\xdd\xcf\x06<~\xef\xee?" +
	"\xbd<w\xcb\x11\xee,\xd9\x09\x0e\xcdb\xe1\xe5\xe8\xac" +
	"\x18\xed\xf3\x1b}\xd5Uw,y\xe2H\x18,\x94\xd7" +
	"2\x7f0\xad\x96\xe6\x98#\xfc\xf7\x98\x8fu'\xdf\xf6" +
	"4\x9e\xf9\xc8\xd6\xda\x0e\x16\xa1j\xd9\x14\x87?\xf5\xc0" +
	"\x81\xe5\xe9-o\x9f`\xe2\xcb\xea\xf6\xc8\x99:bi" +
	"\xba\xee2y3\xfd\xcan\xaf\xfbq\xff\xac/\xbd\xf3" +
	"Nx\xbd\x9b\xea\xd8z\x1b\xeah\xbd-\x0f<q\xd7" +
	"\xfd\x7f\xdb|,_\xe8\xdd]W\x8d\xf2^6\xe3\xe3" +
	"u\xc4\xc3o\xeeQ\x9b\xbf\xb8O\xfas\x98\x03U\xf5" +
	".\x82\xa8\xa7\xd9~\xd2\xbc\xf5\xb73\xa6\xdc\xfd\x97\x1c" +
	"1t\xd731h\xf54\xc5\xa6\xe9\xe5\x9b.9\xab" +
	"\xe0\xfd\x90b=V\xcf\x14\xeb\xae\xff\x88\xd5|\x10\x9f" +
	"|<\xbfk\xbf\xbf~\x02M\xf2`=\xb9\x85\xdf\xae" +
	">\xf6\xb5\x17^\xfc\xc1\xf1\xb0[\xd8z\x11s\x0b\xf7" +
	"_D\xab\xbc*\x1cz\xe53W\x1f>N>\x06\x03" +
	"\x1f\xc3\xf6#\x8f\x9b\xfdwy\xd2l\xfaU>\xfbZ" +
	"0\xb3\xf1\xa4\x9aNh\xd7,+JkV\xa6&\xae" +
	"\xa6\x8cT\xc3|FS\x88\xd2\xa9Y\xcb\xf5\xb8V\xd3" +
	"\xab9\xed\x96\xb9TOj\x15\xed\xaa\xa5\x0e\xda\xa0\x14" +
	"\x88\x05\x00\x05\x08 \x8d\xeb\x00P\xc6\x8a\xa8L\x140" +
	"\xab\xc6\xe3f\xdapZ\x01\x138\x16\x04\x1cK\xfe\xc3" +
	"2W\xd0\xe4\x054{;=\xf0yS\x96\xd9\xa31" +
	"JE\x87f\xa7#I\xc7V\xc6\xfa\x13\xb74\x03(" +
	"\xf3DT\x16\x0a\x88XF\\\x95Z\x89v\xa9\x88J" +
	"\xbb\x80\x92\x80ed\x14\xd2\"\xda\xc1B\x11\x95+\x05" +
	"\\m\xa7\xe3q\xcd\xb6\x11A@\x04\\=\xa8\xd9\xb6" +
	"\xda\xab\xe5\xee\xa6\xd5X\x0ahbi\x00V\x00\xb1\x14" +
	"\x90\x18b$4\xbb\xa6\xd0\xe7\x05=\xf2\xfdz\xa7\xf3" +
	"\x1e\x83=\x87\x98q.\x80R,\xa2R&`\xc4^" +
	"\x1eG)\x80\x96\x80(\x81\xcf\"\xbeDS\xce\x9c5" +
	"\xe9TBu4\x8f\xe8r\x1bme\xb2\xbf\xc0\x83t" +
	"\xd6\x1f\x8a\xa8\xfc4`\xca\xa3=\x00\xca\x8fDT\x9e" +
	"\x0c1\xe5\xf16\x00\xe5\xe7\"*\xcf\x0a(\x89B\x19" +
	"\x8a\x00\xd23\x8b\x01\x94\xa7ET\x0e\x08(\x15\x88e" +
	"X\x00 \xed'\x9e>+\xa2\xf2\x92\x80RaA\x19" +
	"\x16\x02H\x07W\x02(\x07DT^\x15P**," +
	"\xc3\"\x00\xe9\xd0z\x00\xe5U\x11\x95wN\"j\x8f" +
	"\xd6\x05\x91LJ\xc3h\x00\x90\x001\xca\x99\xdfm%" +
	"\x01\xc0\xff&n\x1aK\xf5\xde6\x1bD\xd3\xe0\xc4\xd5" +
	"\xcb5\xcb\xd6\x83gOQ;\xd3\xd0\xd83\xdf\xd2\x12" +
	"6\x96\x06\xe6\x1b\x88.\x9d\xd0\x9aR\xa8\x7fJ\xcb\xd0" +
	" \xa4Q>\xbe\xce\x19u\x8dZ\x94v\xfar\x14\xbe" +
	")\xed\xf4q!\xc4\xcd\xc1TRs\xb4\x85f\xafn" +
	"01'\x1d\xb4\x95\xa9\xbe\x14\xf65\x07|\xe4R\xc8" +
	"a#\x97\xc2\xc1\x9e\x10\x1b\xb9\x14\x0e\xf5\x03(\xaf\x88" +
	"\xa8\x1c!)\xa0+\x85\xd7I\xb0\xaf\x89\xa8\x1c#)" +
	"\x88\xae\x14\x8e\x12\xf1\x1d\x11\x95\x0fH\x0a\x05\xae\x14\xde" +
	"\xab\x03P\x8e\x89\xd8\x81\x02J\x91\xc22\xb2l\xe98" +
	"\xc9\xeb\x03\x11;\x8bq\x04F\xa0\xb2\xd7]&D\x06" +
	"\xb4\x80\xc9\x96\xb6\xd4\xd2\xec\xbe.\x88\x9aa\xb2\xb6\"" +
	"\xa5[\x9a\xdd\x0ah`\x09\x08X\x02y\x85\x1f\xd3\x06" +
	"U=\xe9\x7feZ\xbd\xaa\xa1\xafT\xa1\xd1\xd1M\xa3" +
	"5\xd0\x91\xb8\x9aL\xf6\xa8\xf1\x81\x02\x8f\xfd\x1df\xda" +
	"\xd1\xac\x1a\xd3\xf0\x94\xbee\xb9\xe6j~D\x1d\xb4\x95" +
	"b\x9f\xe7U\xc4\x8b\xe9\"*\x17\x05<\xaf\xad\x06P" +
	"f\x8a\xa8\\\x9c_!\xa3\x03\xba\x91\xc0h\x907x" +
	"z\xc8mP\x18j\x83Q\x92\x7f;\xa2R*\x16\x02" +
	"\xf8\xb8\x1d9\x06\x92\x96}\x11\x04I\x8f`\x90\x98\"" +
	"\x0f\xc0\xd2U\x16\x08Rw\x04\x05\x1f\xef \x8f\x0aR" +
	"+\xbdk\x8a\xa0\xe8\xe7h\xc8\x83\xaa4\xbb\x1f\x04\xe9" +
	"\x82H\xd6\xd2zu\xdb\xd1,\xf4\xf6\x03\xf30\xcb\xfd" +
	"\x01\xc4\x18i\x1eIi\xd0\\\x9eCI\xea\xb6C\x9f" +
	"@4m8\xf6<l\xc7S9\xb2\xf8P\x95\xaf\xe8" +
	"hdZ~\x0a_\xe6C)\xcf\x97qY\x8a\x9e," +
	"\xbb\xfatc@7z\x17j\xcb\xb5\xe4\x15\xcb5+" +
	"j\xe9\x09\xc6\xcf\x89\xcc\x1c\x9a\x16\xb3/\xe7\xb6\x01\xa0" +
	" ]r.\x00\x8aRm\x03\x00\x16HU\xd5\x00X" +
	"(\x9dS\x07\x905L\xfa\xd8\xd2ALh\xd9\x84n" +
	"\xab=I-\x01\x00\x91\xa4ym\xe3\xa0\x96\xd0\xd3\x83" +
	"\xd1>\xbd\xb7/\xb6\x82\xfe\xf5\xc5)\xe6\x18t\x8a;" +
	"\x02\xcd\x889\xba\x9a\xb4i\x1f!}j\x00P*D" +
	"T.\x14P\xe2\x0auAs\xa0d\x8d*\x9b\xc1\xf7" +
	"I=\xaa\xadu[\xc9\xb0O\x1a\x86\xc5\xa9P\xa0\x0b" +
	"\\\xc8\xb0\xdc\xf5\x11\xe3\x88\"\x05\x97:\xc9\x9c\x87e" +
	"\xf0#z\xe1)#z7y\x84@\xee\x13\xfd\x9dm" +
	"$\x1e\xdc.\xa2\xb2%0\xb4\xcdD\xbbKD\xe5[" +
	"!\xe7\xb6\x95B\xcc\x16\x11\x95\xef\x85\x9c\xdb6\"\xde" +
	"'\xa2\xf2\xc3P\x88\xd9A\xde\xe9\x01\x11\x95\x1f\x85B" +
	"\xccn\x0aF\x0f\x8b\xa8\xfc|\x04\x1ek\xa9\xbe\\[" +
	"`\xa6-\x8a\x1c\xa5\x01\xc8\xf1\xbc\xba\xad-\xd7\x8cK" +
	"\xd5\xcc)\xde6v\x9a\x86\xa19y\x86h+\x1cK" +
	"\xed\xb6U\x10{5,\x0d\x12\xb5\x0f\x03\x0bH\x16\xe2" +
	"\xa0\xed\x1b\x87\xe0\x89\xa1\xddL\xea\xf1L\xd8\xc9\x140" +
	"'\xc3\xa1%\xf2$@\x92\x9aA\x90\x0a#\xab\xe3\xb4" +
	"\xdd\xb8\xe3Y\xb498h\x1a5qT=\x1c\xd5\xc8" +
	"p\x8cI\x13U\xf8\xc2{\xeb\xa3\xa10\xc2\xa5w\x94" +
	"\xa4wDD\xe5o$=\xc1\x95\xde\x9f\x1bB\xb1E" +
	"\x14]\xe9\xbdW\x1d\x8a-\x05\x05\xae\xf4\x8ew\x84b" +
	"\x0b\x162\xe9\xc9\x85x.@\x07\x8a\xd89\x16\x03\x88" +
	" \x97\xe0J\x80\xceb\xa2\x97\xb1\xf8T\xc4\xe2\x93," +
	"a5@\xe7X\xa2O$zq\xa4\x0c\x8b\x09\x87b" +
	"\x1b@g\x19\xd1\xa7\xa2\x80\xa2\x9e\xf2\xed\x8d1\xd5\xf2" +
	"\xed\xaf\x91\xdcc\x00\x09\xa2q\xdd\xc9\x84A\x84\xa3\x1b" +
	"\x9a\x01\xe8pZD\xb5\x0d,\x06\x01\x8b\xc9\x94\xec+" +
	"X<\x82\xc6\x95\xaa\x933\x8b\x994\xfdY\x1c}P" +
	"[i\x1aZ\x0e<\x19\xe2\xe2:\x1dKS\x07\xe7\xf7" +
	"\xa5\x8d\x01\x16\xa9\xc0\x8d\x16\x9c\xff*\xf1j\x89\x88J" +
	"20\x1e\x9d\x14\xbdOD\xc5\x09\x19\xcf2\x1a\x98\x12" +
	"QY\x152\x9e\x0c\xb1\xdf\x11Q\xb9\xfe$\x00+N" +
	"\xeb\xb6\x1a\x09\x10\xb5\x15\xfe\xe1H\xbd\x9d\xaeL\x0a\xd0" +
	"\xb7\x97hBu\xd4\x93\x9e!\x1ci?\xa5\x1b\x09\xf7" +
	"\x0cl[Uu\xcc\xfb\x9c\xd3\xcc<\xf4\xa4\x0e\xe6\xa1" +
	"\xcb-\x80\x98\x9aHh\x89\xd5n\xf4Ip\xac\xa0\x01" +
	"&<\x04\xd7\x9d\x82\x18\xc5\xaa\x84o-\x9e;n6" +
	"M\xc7v,5U\xa3\xa6\x9d>?\xb2\x87\\a]" +
	"\xe0\x0acN\x0e\xf6\xe0S\x15\x0d\x13\xc6\xc2\x8e\xcd\xf3" +
	"\xb4\xb9\x09\xca\x89\x9e\xd6/\xe8\xf086\xea<\x88\xaf" +
	"\x03\xca\x85|!\xb9\x09\x9b\x01:\xe7\x90./@_" +
	"\xfcr\x0b#\xcf#\xf2B\x0c4@n\xc5\x0e\x80\xce" +
	"\x05D\xef\xc2@\x09d\x05\xeb\x00:\x17\x12\xfdJ\x0c" +
	"\x9c\xa8\xdc\x8d=\x00\x9d]D_\x82\x81\x1f\x95\xafb" +
	"\xf3|\x9e\xe8}aS\xd4\x98)&\x88\x9e\x0a\x9b\xe2" +
	" \xae\x05\xe8L\x11}U\xd8\x143h\x01t\xae " +
	"\xfa\x8dD/\xc12,\x01\x90o\xc0\xed\x00\x9d7\x12" +
	"\xfdV\xa2\x8f).\xc31\x00\xf2-l?_&\xfa" +
	"]D?\xa3\xa4\x0c\xcf\x00\x907\xe0N\x80\xce\xbb\x88" +
	"\xfe\xad\x11\x82\xd1S`\xc9\x84n\xa7\x92j\xe6r\x88" +
	"\xa8\x83\xc1wqK#uk\x0a\xd9\xfc\xc9Q'\x7f" +
	"\x81D\xef\xca\xa4\xb4\x90\x89[\xaa\xa3-\xd4\x07u\x88" +
	"9]\xbaf\xf9\xf4>\xd5n\xa1\xb8\x80,T\xb6\x18" +
	"j\x94`\x08?G\xb6GO&u\xa3\xd7Kv\xf8" +
	"Gv\xba\xc7\x8e[z\x8a-4\xdf\xd2\xd4\x18\xed\xd1" +
	"\x19z\xda!\xd0\xb3+\x93B\x16\x12&\xbb\x19m3" +
	"\xd3\xcc\x96M\xcc\x0a[\xd62+lY\xcfp\x12#" +
	"\x16J-\xfd\x00X\xc4\x10\xd5\xea\xb41`\x98\xd7\x1a" +
	"~\x96\x84\xee\x16\x1c]49\xb1]\xc5L\x93\xfdY" +
	"3}\x99I(\xc1Lh+:\xd3=\xe8\x8d3\xd1" +
	"\xc8\xf6j\x83\xba\xa1\x0f\xf9\xd8%6\xa5 JP(" +
	"\xab^k7k\x09\xcb\x041>p\x0ax\xc2\xc1l" +
	"(\x95ef\x7f\xdaRY\x8aiO\x8a\xa8\xfc&\x84" +
	"3\xf6-\x0e\xa7\xb2\xe8\xa5\xb2\x1d\xe1T\xd6K\xa2\x0e" +
	"\xf5\x049\xd8\xe9JeO\xccZ\xf3\xa4\xb6y\xd3\xa9" +
	"8C\xa9\x8e\x0e\x115ic)\xafNs\xf4\x91?" +
	"c\xb2\xe8\xbf\x0emYZ\xb3\x1d\xd7\x1f\x89\xb9\xf8\xbd" +
	"!\xf0{\x8d\x96\x8b@K\x83\xea\xd2\x90\xc9\xc5\xf0\xe4" +
	"\xaew\xab\xb1\xb4~-\x1eq\xb4\x84\x0b\x9b]\xc6W" +
	"-\xce\xcd\xc3\x88\xef\xb5\xcd\xa1<\xccvT'm\xcf" +
	"7\x09\xbcc\x04\x04\x8c\xe41\xfaQ\x80\xe70\xb6=" +
	"eN\x93\x13\x0c\x1a\xddOG\x96\xf4\xf3\xec\x97\xe2O" +
	"\xc8\xbd\xff+\xe9?\x9dI?\xc7\xc2\xcc\xa3vh)" +
	"S\xb4\x1cr{\xd3\xfd Z\xc2\xa2Y\x00 y\x14" +
	"\x95\xb0!\x07@z0V.g\xd1\xb2\x94\xe8\x93)" +
	"\xe8\xba@V\x9e\xc4\x82\xd3D\"W`\xc0q\xf9\x1c" +
	"\xec\x07\xe8\x9cJ\xf4\x99,\x88\x0an\x10\xadb\xc1o" +
	":\xd1/bATt\x83h-.\x06\xe8\xbc\x90\xe8" +
	"s\x18\xeb\x057\x88^\xc2\xe8\x17\x13\xfdR\x16D\x8b" +
	"\xdc \xda\x84_\xcc\x09\xf6%\x117\x88\xb6\xb2\xa0\xeb" +
	"\x07\xf5|\xbc\x1c\x92o\xc6\x06\xcd\x84\x16\xb0V7R" +
	"i\xa7\xcb\x1c\x80\x88f\xd8>\xf43\xd3\x0e#Ct" +
	" Lv\xbc<\x1cb,\x13\xf7\xe99\xa6\xc9\x89\x89" +
	"\xb4\xc501\x88\x8b\xec\xc0#\xa9\xf1>\xadCS1" +
	"\xc1\x0c\xc2\x06\x7f8{\xf3\x19KGG\xf3^\x85\xde" +
	"y\x86V8\x9c\xa1\xd9\x8ej9ni\xad=\xc6\x0c" +
	"4\\\xf4\xed\x09\x15x\xb9\x95-j\x0b\x0a\xbc~\xfe" +
	"\xd2M\xa6\xd7.\xa2\xf2y\x81\xb48\xa1[Z\xdc\x81" +
	"H\xb7\xa5\xe7\xd6zO\xe5\xa3\x87\x05\xab\x1d\x9a\x1d\x1d" +
	"Z\x16i\x0e\xdc\xeaj\xdb=\x13JA\xfbqHi" +
	"\x04\xb9_\x8d1\xaf\x1d\xd4\x96x\xbb\x03y\xe7WZ" +
	"\xd6\xcfkK\xbc\xca\x8f\xbcg ]\xd5\xc3kK\xbc" +
	"1\x88\xbcQ%\xb5\xf6\xf0\xda\x12\xbf\xe8\x80\xbc\x07)" +
	"\xcd^\xe9\xd5\x96\xbc`\x01Q\x0a\x17\xac\x8c\x942-" +
	"\xa7\xdb\x86\x88\xda\xab\xf9\xcf\xf3\xfb \x926\x06\xe6a" +
	"\x96\xd7\xe3\xa0\xd1\xcd\x13r\xcbJ\xc2P\x17\xec\xe7\xb4" +
	"e\xecp\xfc.\x01\xf2\xfb\x1d\xd2:\xda\xc8\x1a:\x1c" +
	"\xef\xd4!\xbfF!]\xb7\x1e\x04)C\x87\xe3\xfdi" +
	"\xe4\xedyip\x93\xcb\x14\xd1\xefj#\xbf\x06!]" +
	"\xd5\xef2\xa5\xc0oo\"\xef\x13\xf2\x82\x1b7\xb4N" +
	"htE5\xcf\xaf\x14\xa7\x91\xeb$\x06T%\x8d<" +
	"\x80\x88l0\x0fE\x10\xf5\xbeNyi<\xc4\xbc\xf9" +
	"\x88/C*P\x1e\xe8\x99\xef\x85u5i\x03\xcb\xb1" +
	"\xc6\x8a\x05c\xb3YW\xd1\xab\x83\xee\xc68\xfcG\xd6" +
	"\xebo\x90G_ \xa2\xd2%\xe08\xe1x\xd6Uu" +
	"e=\x80\xd2%\xa2\xb2D\xc0\xa8A\x09j\xd1i\xaf" +
	"\x88/\x13O\x96\xfb\xb8\xe7t\xb7O\xb2\xe5\xb7~\x90" +
	"\xdf\x90\x90\x94\xc5 H\xad$[\xde\xe4C~\xdfD" +
	"\x9a\xdb\x06\x824\x9bd\xcb\x1br\xc8\x9b\x85R\x15\xbd" +
	";'\x92\xe5y\x15\x88I\xe20/N\x01\x80\xfb\xd4" +
	"a&5\x9b=1\x1d\x1cQ\x01\x99[\xae\x7f>!" +
	"t>\x06\xebcl\x91\x93\xa7\xef\xbe\xfb\xd1\xfb\xc3\xf9" +
	"\xbb\xe7~\x96\xf5\x84\xf3w\xaf|\x92!\xe2\x0a\x11\x95" +
	"\x1b\x05\xcc\xeav\x8b\xa1\xf6$)E\xf6s\x86A\xd3" +
	"p\xfa\x92\x99\x85\x10\xd5\x07u\x07\x0bA\xc0B\xc0l" +
	"\xda\xd6\x12$ \x88\xe8\x8e\x1dP\x1d=\xa9\xafT\x1d" +
	"\x88\x90\xc3:\x03\x04<c\x184\xe8\xd9o\xda\x18\xf0" +
	"\x11\xd3I\xaa\xe7\xfe\xc1j\xebB\xb0\xcdr\x91dN" +
	"tg\xe5\x06,\x0dn\xe9\x0c\x01\x8d\xc2P\xd0(&" +
	"\x1d\xaf\xca:6\x9bE\x0c:\x9bRU\x03\x08\xa4\xe7" +
	"\x18\xba\xc9\"Im 42\xd7\x94\xc82\xb0\xe9\xb0" +
	"2\xef\xa9\xd0!/\xa4\x05\xf0\x10?\x0c\xc8\xe3\xbd\xcc" +
	"P\xf4\xe9\xff\x90\xd1'/\x86\x1aI\xf8\x19]\x12\xe5" +
	"\x87\xa3\x90`\x9b\x832v\xbe*\xf6)a\xe1hc" +
	"\xb6_1\xce\xbf\x87\xa0\x94\xde\x11(\xd7j\x0a\xa6\xe1" +
	"\xda\xb9\xad\xd9\xc4\x86|\x19\xd7IY\xe1\xb6=r\x1b" +
	"\xa3\xa3hC\x7f\x88\xce\x9foG!\x0d\xe9\xc8\xa7!" +
	"\xd5\x81\xd7\xf65D\xe9\x09iH\x9e\xf3F)\x09?" +
	"\x01 \x13\x80\x19q\x8b!\xc7\x0e\xf2e\x80'V\xbe" +
	"\xfc\xab|A\xe5kT}\"\x0f\xb1\xf9\xdc\x14O\xc6" +
	"\xcdHN#\x8d_\x06C~UHZ\xb6\x98\x83\x1d" +
	"~\xf7\x07\x9f\x05\xf7\"g\xa8\x91\xc6/'!\xbf\x9e" +
	"&\xb5\xf6s\xb0\xc3o\xad\xe0\x0ep\xef\xc8H\xb3\xef" +
	"\x01A\xaa\x8dd\xb9\xb6\x82\xa8\x1b\xf3X\xe5\x9c\x09\x15" +
	"bL\xac\xf3\x86\x1al@hB/\xeb7#\x8c>" +
	"L\xb8\x09\xfb[\xde\xde9Iq\xa7\xd5X\x8a\xacL" +
	"\xff\xcf\xa9}x\xb9\xe4\xbe\x8ep\xed\xc3\xcb%\x0f." +
	"\xfe\xff\xaa}\xe4-s\xe4\xab\x87\x0c_\xfb\xe0\x97G" +
	"\x84\xa1\x97G\\@\xe5vP\xf8\x05'\xe4\xf7\x8d%" +
	"\x89\xb4\xab$\x92\xe57L@\\\x91\xc9/\xce\xf6\xb0" +
	"\x11\xd5x\x1d\x97\x13\xd0\x83\x1a\x19AT\xe1\xb5\xbc\x9c" +
	"\x0a\xc2\xbf\x0a\x08\xa7\xa5\x800\x9a[3\xbe'<\x8d" +
	"QrD\x97\x98\xbc\xce_\xd8\x03\xb7\x85\xa2R\xde\xdb" +
	"/\xa3@-9\xfa\xe5\xd5\xb6F\x13\x01G\xd1O\xce" +
	"\xd7\xb0\xe6G\x99\x1eLO\xa0\x1c\xc7\x03\xb6\x8b\x88\xa5" +
	"\xc1\xfdH@\"\x8e\xa2\x17\xcd\x00~\x80,\xca\xfcE" +
	"\xafk\x0e\x005\x97\xdb\x0dD[%\xa2rs\xc8d" +
	"nZ\x0b\xa0\xdc,\xa2r{\xc8d\xd6Y\x00\xca\xad" +
	"\"*w\x87j\xc4\x1bi\xe4\xdd\"*\xf7\x8d@\xec" +
	"9m\x03\xdaeHt\xd7\x9a\xd6\x80\x9dR\xe3\x10\xd3" +
	"\xe8M\xfeo.W\x07\xb5\x13\xc5=\xe2\xf6</\x90" +
	"\x8c\x06\xe7\x8c\xa0Z\xcc\xe1S\x88\xd1\x1d!\xa6rN" +
	"\xdf\xd4\x00\xa0\\/\xa2\xf2\xe5\x10\xaeYC\x8e\xe4F" +
	"\x11\x95[C\x89\xcf-\xa4\x1c_\x16Q\xb9+\xd47" +
	"\xde\xd0\x11\\$\xc8\x97^\x0c_\xf0\xd2\x8cD\xca\xd4" +
	"\x0d'l-i[\xb3\x9azs\xda\xbcCK\x12~" +
	"\x01'\x14\x1f\xf8\x1f\x03 \xbfr.I\xd5\xac\xc3\x1e" +
	"%\\\xeaW6F\xa5\xac\x1fB2y\xaf\xa90k" +
	"\xf6\x0a\x05\xd1<\xb7Tz\xf2\xe5m\xfd\xac\xef\x88\xca" +
	"\x1ca\x94^yd\xd1/O\x8b6\xa7\x97\xc04\x0a" +
	"\xa5\xe0\x82\xfe\x88.\xac\xe4\"\xf8\x7f\x86\x93\x1e\x16\xaa" +
	"y\xf7]8T\x1b\xb6\xefA\xbf1q\xca\xba\x80\x15" +
	"\xd4\x05\x90\x97\x05v\x06\x1d|I\x9c\xea\x06\xe4\xeb\xd6" +
	"\x06v\x94W3\x98\xe6_\xb1\\\x83\x98e\xe9\xa1\xac" +
	"\x80\xd7q\x91_\xa8\xf2\xdeG\x83\xbf0\xf2 \x99=" +
	"\xa0\xa7\x9a\xf5d\x12u\xa3w~\x9f\x16\x1f\xa0\x17^" +
	"\xd1a\x04l\x19q\xc5\xa0a\xf8\x8aA\xa3;)\x96" +
	"\x06\x7f,2\xa4\xcc\x14.\xc3\xb0\xb5\x1b\xdb5K7" +
	"\x13'W{\x7f\xed\xb6\x90\xd6\xe7\xaf\x8dX\x9a\xad9" +
	"vS\xd8g\xfc_\x00\x00\x00\xff\xff\xa1}\xb9m"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b1c2d3e4f5a6b7c8,
		Nodes: []uint64{
			0x812a80e89166a990,
			0x8873f9097b095502,
			0x88afc5ebaaa0711b,
			0x891fa8b6066a4ed5,
			0x898035d58eaa00d0,
			0x8993aa56e597383a,
			0x8a9179019ae6c648,
			0x8b64d73a39434e2f,
			0x8e65dbd5998695ef,
			0x8ef23c1999b62e1f,
			0x8f41a8d77ae30ae5,
			0x92070f51247244e5,
			0x949970f09afa9668,
			0x94e9ec8b264832ae,
			0x97f64db20802dd92,
			0x9c8046fbc9ccf744,
			0x9eb2a626892c0f7c,
			0x9feb9afedcb9d848,
			0xa06014969215eea9,
			0xa178f9d9ca11fd5e,
			0xa26abc09da3e2fb7,
			0xa309701d252a3266,
			0xa77c56c45e37a0a1,
			0xaab5935420e73dab,
			0xaf58ac077ff7f19d,
			0xb02636f995ef5f5f,
			0xb27e81ce62f8604e,
			0xb60a45b81f469adc,
			0xb7b3a92001d42bcc,
			0xb847745bb5ce9501,
			0xc20696166fc14280,
			0xc2787f08c0de0eb1,
			0xc2b6e8aae63a6302,
			0xc80017a258c68a97,
			0xc91ac16c25a26e24,
			0xcac3d8265e93b7f4,
			0xcad77cecc30d0a4f,
			0xcaf44958e96cf3b7,
			0xcb6cee0eecbdac96,
			0xcb99a7f2d8d84d46,
			0xcbc72c91b0c25b3e,
			0xcd61f2c9baeb2c70,
			0xcfd012141738bb7a,
			0xcfdc97e955c82412,
			0xd2a9d23dbaf138f4,
			0xd460053f494a559d,
			0xd750bf88489926d8,
			0xdab8367e68e65473,
			0xdc44ed4a624c7dfb,
			0xde341fe554ef796d,
			0xe229b70fcd90a51f,
			0xe3fb4d1d7a312c49,
			0xe59e5693aad100b1,
			0xe83dabed9b090802,
			0xe841b7d32f4306f9,
			0xea306701414cc0d3,
			0xeb097c133ce0ccbe,
			0xeca03dddeeb9a7c5,
			0xecc66096292a689f,
			0xef6c55360ad6023c,
			0xefa07576d8b04be5,
			0xf0f08b2f6abe32aa,
			0xf49df8ad98c6b0a0,
			0xf511d1824261c2a3,
			0xf69c1e2bdba142bf,
			0xfb041b399a15289a,
			0xfd1c63fc2e1f8798,
			0xfdb3dad79bf47fdb,
			0xfde55e57e0e102e4,
		},
		Compressed: true,
	})
}
