// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	strconv "strconv"
)

type AccountType uint16

// AccountType_TypeID is the unique identifier for the type AccountType.
const AccountType_TypeID = 0xa309701d252a3266

// Values of AccountType.
const (
	AccountType_unknown            AccountType = 0
	AccountType_claudeSubscription AccountType = 1
	AccountType_claudePayAsYouGo   AccountType = 2
	AccountType_codexSubscription  AccountType = 3
	AccountType_geminiSubscription AccountType = 4
	AccountType_geminiApiKey       AccountType = 5
	AccountType_awsBedrock         AccountType = 6
)

// String returns the enum's constant name.
func (c AccountType) String() string {
	switch c {
	case AccountType_unknown:
		return "unknown"
	case AccountType_claudeSubscription:
		return "claudeSubscription"
	case AccountType_claudePayAsYouGo:
		return "claudePayAsYouGo"
	case AccountType_codexSubscription:
		return "codexSubscription"
	case AccountType_geminiSubscription:
		return "geminiSubscription"
	case AccountType_geminiApiKey:
		return "geminiApiKey"
	case AccountType_awsBedrock:
		return "awsBedrock"

	default:
		return ""
	}
}

// AccountTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func AccountTypeFromString(c string) AccountType {
	switch c {
	case "unknown":
		return AccountType_unknown
	case "claudeSubscription":
		return AccountType_claudeSubscription
	case "claudePayAsYouGo":
		return AccountType_claudePayAsYouGo
	case "codexSubscription":
		return AccountType_codexSubscription
	case "geminiSubscription":
		return AccountType_geminiSubscription
	case "geminiApiKey":
		return AccountType_geminiApiKey
	case "awsBedrock":
		return AccountType_awsBedrock

	default:
		return 0
	}
}

type AccountType_List = capnp.EnumList[AccountType]

func NewAccountType_List(s *capnp.Segment, sz int32) (AccountType_List, error) {
	return capnp.NewEnumList[AccountType](s, sz)
}

type ClaudeTokenCredentials capnp.Struct

// ClaudeTokenCredentials_TypeID is the unique identifier for the type ClaudeTokenCredentials.
const ClaudeTokenCredentials_TypeID = 0xf49df8ad98c6b0a0

func NewClaudeTokenCredentials(s *capnp.Segment) (ClaudeTokenCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeTokenCredentials(st), err
}

func NewRootClaudeTokenCredentials(s *capnp.Segment) (ClaudeTokenCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeTokenCredentials(st), err
}

func ReadRootClaudeTokenCredentials(msg *capnp.Message) (ClaudeTokenCredentials, error) {
	root, err := msg.Root()
	return ClaudeTokenCredentials(root.Struct()), err
}

func (s ClaudeTokenCredentials) String() string {
	str, _ := text.Marshal(0xf49df8ad98c6b0a0, capnp.Struct(s))
	return str
}

func (s ClaudeTokenCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeTokenCredentials) DecodeFromPtr(p capnp.Ptr) ClaudeTokenCredentials {
	return ClaudeTokenCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeTokenCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeTokenCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeTokenCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeTokenCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeTokenCredentials) AccessToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeTokenCredentials) HasAccessToken() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeTokenCredentials) AccessTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeTokenCredentials) SetAccessToken(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeTokenCredentials) RefreshToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeTokenCredentials) HasRefreshToken() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeTokenCredentials) RefreshTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeTokenCredentials) SetRefreshToken(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ClaudeTokenCredentials_List is a list of ClaudeTokenCredentials.
type ClaudeTokenCredentials_List = capnp.StructList[ClaudeTokenCredentials]

// NewClaudeTokenCredentials creates a new list of ClaudeTokenCredentials.
func NewClaudeTokenCredentials_List(s *capnp.Segment, sz int32) (ClaudeTokenCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ClaudeTokenCredentials](l), err
}

// ClaudeTokenCredentials_Future is a wrapper for a ClaudeTokenCredentials promised by a client call.
type ClaudeTokenCredentials_Future struct{ *capnp.Future }

func (f ClaudeTokenCredentials_Future) Struct() (ClaudeTokenCredentials, error) {
	p, err := f.Future.Ptr()
	return ClaudeTokenCredentials(p.Struct()), err
}

type ClaudeApiKeyCredentials capnp.Struct

// ClaudeApiKeyCredentials_TypeID is the unique identifier for the type ClaudeApiKeyCredentials.
const ClaudeApiKeyCredentials_TypeID = 0x8ef23c1999b62e1f

func NewClaudeApiKeyCredentials(s *capnp.Segment) (ClaudeApiKeyCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeApiKeyCredentials(st), err
}

func NewRootClaudeApiKeyCredentials(s *capnp.Segment) (ClaudeApiKeyCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeApiKeyCredentials(st), err
}

func ReadRootClaudeApiKeyCredentials(msg *capnp.Message) (ClaudeApiKeyCredentials, error) {
	root, err := msg.Root()
	return ClaudeApiKeyCredentials(root.Struct()), err
}

func (s ClaudeApiKeyCredentials) String() string {
	str, _ := text.Marshal(0x8ef23c1999b62e1f, capnp.Struct(s))
	return str
}

func (s ClaudeApiKeyCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeApiKeyCredentials) DecodeFromPtr(p capnp.Ptr) ClaudeApiKeyCredentials {
	return ClaudeApiKeyCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeApiKeyCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeApiKeyCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeApiKeyCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeApiKeyCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeApiKeyCredentials) ApiKey() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeApiKeyCredentials) HasApiKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeApiKeyCredentials) ApiKeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeApiKeyCredentials) SetApiKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeApiKeyCredentials) BaseUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeApiKeyCredentials) HasBaseUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeApiKeyCredentials) BaseUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeApiKeyCredentials) SetBaseUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ClaudeApiKeyCredentials_List is a list of ClaudeApiKeyCredentials.
type ClaudeApiKeyCredentials_List = capnp.StructList[ClaudeApiKeyCredentials]

// NewClaudeApiKeyCredentials creates a new list of ClaudeApiKeyCredentials.
func NewClaudeApiKeyCredentials_List(s *capnp.Segment, sz int32) (ClaudeApiKeyCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ClaudeApiKeyCredentials](l), err
}

// ClaudeApiKeyCredentials_Future is a wrapper for a ClaudeApiKeyCredentials promised by a client call.
type ClaudeApiKeyCredentials_Future struct{ *capnp.Future }

func (f ClaudeApiKeyCredentials_Future) Struct() (ClaudeApiKeyCredentials, error) {
	p, err := f.Future.Ptr()
	return ClaudeApiKeyCredentials(p.Struct()), err
}

type AccountCredentials capnp.Struct
type AccountCredentials_Which uint16

const (
	AccountCredentials_Which_none              AccountCredentials_Which = 0
	AccountCredentials_Which_claudeSubCreds    AccountCredentials_Which = 1
	AccountCredentials_Which_claudeApiKeyCreds AccountCredentials_Which = 2
)

func (w AccountCredentials_Which) String() string {
	const s = "noneclaudeSubCredsclaudeApiKeyCreds"
	switch w {
	case AccountCredentials_Which_none:
		return s[0:4]
	case AccountCredentials_Which_claudeSubCreds:
		return s[4:18]
	case AccountCredentials_Which_claudeApiKeyCreds:
		return s[18:35]

	}
	return "AccountCredentials_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// AccountCredentials_TypeID is the unique identifier for the type AccountCredentials.
const AccountCredentials_TypeID = 0xc80017a258c68a97

func NewAccountCredentials(s *capnp.Segment) (AccountCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountCredentials(st), err
}

func NewRootAccountCredentials(s *capnp.Segment) (AccountCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountCredentials(st), err
}

func ReadRootAccountCredentials(msg *capnp.Message) (AccountCredentials, error) {
	root, err := msg.Root()
	return AccountCredentials(root.Struct()), err
}

func (s AccountCredentials) String() string {
	str, _ := text.Marshal(0xc80017a258c68a97, capnp.Struct(s))
	return str
}

func (s AccountCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountCredentials) DecodeFromPtr(p capnp.Ptr) AccountCredentials {
	return AccountCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s AccountCredentials) Which() AccountCredentials_Which {
	return AccountCredentials_Which(capnp.Struct(s).Uint16(0))
}
func (s AccountCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountCredentials) SetNone() {
	capnp.Struct(s).SetUint16(0, 0)

}

func (s AccountCredentials) ClaudeSubCreds() (ClaudeTokenCredentials, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != claudeSubCreds")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ClaudeTokenCredentials(p.Struct()), err
}

func (s AccountCredentials) HasClaudeSubCreds() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountCredentials) SetClaudeSubCreds(v ClaudeTokenCredentials) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClaudeSubCreds sets the claudeSubCreds field to a newly
// allocated ClaudeTokenCredentials struct, preferring placement in s's segment.
func (s AccountCredentials) NewClaudeSubCreds() (ClaudeTokenCredentials, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewClaudeTokenCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeTokenCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s AccountCredentials) ClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != claudeApiKeyCreds")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ClaudeApiKeyCredentials(p.Struct()), err
}

func (s AccountCredentials) HasClaudeApiKeyCreds() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountCredentials) SetClaudeApiKeyCreds(v ClaudeApiKeyCredentials) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClaudeApiKeyCreds sets the claudeApiKeyCreds field to a newly
// allocated ClaudeApiKeyCredentials struct, preferring placement in s's segment.
func (s AccountCredentials) NewClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewClaudeApiKeyCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeApiKeyCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountCredentials_List is a list of AccountCredentials.
type AccountCredentials_List = capnp.StructList[AccountCredentials]

// NewAccountCredentials creates a new list of AccountCredentials.
func NewAccountCredentials_List(s *capnp.Segment, sz int32) (AccountCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountCredentials](l), err
}

// AccountCredentials_Future is a wrapper for a AccountCredentials promised by a client call.
type AccountCredentials_Future struct{ *capnp.Future }

func (f AccountCredentials_Future) Struct() (AccountCredentials, error) {
	p, err := f.Future.Ptr()
	return AccountCredentials(p.Struct()), err
}
func (p AccountCredentials_Future) ClaudeSubCreds() ClaudeTokenCredentials_Future {
	return ClaudeTokenCredentials_Future{Future: p.Future.Field(0, nil)}
}
func (p AccountCredentials_Future) ClaudeApiKeyCreds() ClaudeApiKeyCredentials_Future {
	return ClaudeApiKeyCredentials_Future{Future: p.Future.Field(0, nil)}
}

type AccountInfo capnp.Struct

// AccountInfo_TypeID is the unique identifier for the type AccountInfo.
const AccountInfo_TypeID = 0xde341fe554ef796d

func NewAccountInfo(s *capnp.Segment) (AccountInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountInfo(st), err
}

func NewRootAccountInfo(s *capnp.Segment) (AccountInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountInfo(st), err
}

func ReadRootAccountInfo(msg *capnp.Message) (AccountInfo, error) {
	root, err := msg.Root()
	return AccountInfo(root.Struct()), err
}

func (s AccountInfo) String() string {
	str, _ := text.Marshal(0xde341fe554ef796d, capnp.Struct(s))
	return str
}

func (s AccountInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountInfo) DecodeFromPtr(p capnp.Ptr) AccountInfo {
	return AccountInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountInfo) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountInfo) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountInfo) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountInfo) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountInfo) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountInfo) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountInfo) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountInfo) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountInfo) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountInfo) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountInfo) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountInfo) HasVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountInfo) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountInfo) SetVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountInfo) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s AccountInfo) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s AccountInfo) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountInfo) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountInfo) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountInfo) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountInfo) Credentials() (AccountCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return AccountCredentials(p.Struct()), err
}

func (s AccountInfo) HasCredentials() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountInfo) SetCredentials(v AccountCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewCredentials sets the credentials field to a newly
// allocated AccountCredentials struct, preferring placement in s's segment.
func (s AccountInfo) NewCredentials() (AccountCredentials, error) {
	ss, err := NewAccountCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return AccountCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountInfo_List is a list of AccountInfo.
type AccountInfo_List = capnp.StructList[AccountInfo]

// NewAccountInfo creates a new list of AccountInfo.
func NewAccountInfo_List(s *capnp.Segment, sz int32) (AccountInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5}, sz)
	return capnp.StructList[AccountInfo](l), err
}

// AccountInfo_Future is a wrapper for a AccountInfo promised by a client call.
type AccountInfo_Future struct{ *capnp.Future }

func (f AccountInfo_Future) Struct() (AccountInfo, error) {
	p, err := f.Future.Ptr()
	return AccountInfo(p.Struct()), err
}
func (p AccountInfo_Future) Credentials() AccountCredentials_Future {
	return AccountCredentials_Future{Future: p.Future.Field(4, nil)}
}

type AccountService capnp.Client

// AccountService_TypeID is the unique identifier for the type AccountService.
const AccountService_TypeID = 0x8a9179019ae6c648

func (c AccountService) RegisterAccount(ctx context.Context, params func(AccountService_registerAccount_Params) error) (AccountService_registerAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      0,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "registerAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 5}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_registerAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_registerAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) UpdateAccount(ctx context.Context, params func(AccountService_updateAccount_Params) error) (AccountService_updateAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      1,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "updateAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 6}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_updateAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_updateAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) RemoveAccount(ctx context.Context, params func(AccountService_removeAccount_Params) error) (AccountService_removeAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      2,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "removeAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_removeAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_removeAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) ListAccounts(ctx context.Context, params func(AccountService_listAccounts_Params) error) (AccountService_listAccounts_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      3,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "listAccounts",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_listAccounts_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_listAccounts_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c AccountService) String() string {
	return "AccountService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c AccountService) AddRef() AccountService {
	return AccountService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c AccountService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c AccountService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c AccountService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (AccountService) DecodeFromPtr(p capnp.Ptr) AccountService {
	return AccountService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c AccountService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c AccountService) IsSame(other AccountService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c AccountService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c AccountService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A AccountService_Server is a AccountService with a local implementation.
type AccountService_Server interface {
	RegisterAccount(context.Context, AccountService_registerAccount) error

	UpdateAccount(context.Context, AccountService_updateAccount) error

	RemoveAccount(context.Context, AccountService_removeAccount) error

	ListAccounts(context.Context, AccountService_listAccounts) error
}

// AccountService_NewServer creates a new Server from an implementation of AccountService_Server.
func AccountService_NewServer(s AccountService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(AccountService_Methods(nil, s), s, c)
}

// AccountService_ServerToClient creates a new Client from an implementation of AccountService_Server.
// The caller is responsible for calling Release on the returned Client.
func AccountService_ServerToClient(s AccountService_Server) AccountService {
	return AccountService(capnp.NewClient(AccountService_NewServer(s)))
}

// AccountService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func AccountService_Methods(methods []server.Method, s AccountService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      0,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "registerAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RegisterAccount(ctx, AccountService_registerAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      1,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "updateAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.UpdateAccount(ctx, AccountService_updateAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      2,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "removeAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RemoveAccount(ctx, AccountService_removeAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      3,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "listAccounts",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListAccounts(ctx, AccountService_listAccounts{call})
		},
	})

	return methods
}

// AccountService_registerAccount holds the state for a server call to AccountService.registerAccount.
// See server.Call for documentation.
type AccountService_registerAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_registerAccount) Args() AccountService_registerAccount_Params {
	return AccountService_registerAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_registerAccount) AllocResults() (AccountService_registerAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(r), err
}

// AccountService_updateAccount holds the state for a server call to AccountService.updateAccount.
// See server.Call for documentation.
type AccountService_updateAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_updateAccount) Args() AccountService_updateAccount_Params {
	return AccountService_updateAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_updateAccount) AllocResults() (AccountService_updateAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(r), err
}

// AccountService_removeAccount holds the state for a server call to AccountService.removeAccount.
// See server.Call for documentation.
type AccountService_removeAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_removeAccount) Args() AccountService_removeAccount_Params {
	return AccountService_removeAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_removeAccount) AllocResults() (AccountService_removeAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(r), err
}

// AccountService_listAccounts holds the state for a server call to AccountService.listAccounts.
// See server.Call for documentation.
type AccountService_listAccounts struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_listAccounts) Args() AccountService_listAccounts_Params {
	return AccountService_listAccounts_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_listAccounts) AllocResults() (AccountService_listAccounts_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(r), err
}

// AccountService_List is a list of AccountService.
type AccountService_List = capnp.CapList[AccountService]

// NewAccountService_List creates a new list of AccountService.
func NewAccountService_List(s *capnp.Segment, sz int32) (AccountService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[AccountService](l), err
}

type AccountService_registerAccount_Params capnp.Struct

// AccountService_registerAccount_Params_TypeID is the unique identifier for the type AccountService_registerAccount_Params.
const AccountService_registerAccount_Params_TypeID = 0xa77c56c45e37a0a1

func NewAccountService_registerAccount_Params(s *capnp.Segment) (AccountService_registerAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountService_registerAccount_Params(st), err
}

func NewRootAccountService_registerAccount_Params(s *capnp.Segment) (AccountService_registerAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountService_registerAccount_Params(st), err
}

func ReadRootAccountService_registerAccount_Params(msg *capnp.Message) (AccountService_registerAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_registerAccount_Params(root.Struct()), err
}

func (s AccountService_registerAccount_Params) String() string {
	str, _ := text.Marshal(0xa77c56c45e37a0a1, capnp.Struct(s))
	return str
}

func (s AccountService_registerAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_registerAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_registerAccount_Params {
	return AccountService_registerAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_registerAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_registerAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_registerAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_registerAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_registerAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_registerAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountService_registerAccount_Params) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountService_registerAccount_Params) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountService_registerAccount_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountService_registerAccount_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountService_registerAccount_Params) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountService_registerAccount_Params) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountService_registerAccount_Params) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountService_registerAccount_Params) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountService_registerAccount_Params) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s AccountService_registerAccount_Params) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s AccountService_registerAccount_Params) Credentials() (AccountCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return AccountCredentials(p.Struct()), err
}

func (s AccountService_registerAccount_Params) HasCredentials() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountService_registerAccount_Params) SetCredentials(v AccountCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewCredentials sets the credentials field to a newly
// allocated AccountCredentials struct, preferring placement in s's segment.
func (s AccountService_registerAccount_Params) NewCredentials() (AccountCredentials, error) {
	ss, err := NewAccountCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return AccountCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountService_registerAccount_Params_List is a list of AccountService_registerAccount_Params.
type AccountService_registerAccount_Params_List = capnp.StructList[AccountService_registerAccount_Params]

// NewAccountService_registerAccount_Params creates a new list of AccountService_registerAccount_Params.
func NewAccountService_registerAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_registerAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5}, sz)
	return capnp.StructList[AccountService_registerAccount_Params](l), err
}

// AccountService_registerAccount_Params_Future is a wrapper for a AccountService_registerAccount_Params promised by a client call.
type AccountService_registerAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_registerAccount_Params_Future) Struct() (AccountService_registerAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_registerAccount_Params(p.Struct()), err
}
func (p AccountService_registerAccount_Params_Future) Credentials() AccountCredentials_Future {
	return AccountCredentials_Future{Future: p.Future.Field(4, nil)}
}

type AccountService_registerAccount_Results capnp.Struct

// AccountService_registerAccount_Results_TypeID is the unique identifier for the type AccountService_registerAccount_Results.
const AccountService_registerAccount_Results_TypeID = 0xcd61f2c9baeb2c70

func NewAccountService_registerAccount_Results(s *capnp.Segment) (AccountService_registerAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(st), err
}

func NewRootAccountService_registerAccount_Results(s *capnp.Segment) (AccountService_registerAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(st), err
}

func ReadRootAccountService_registerAccount_Results(msg *capnp.Message) (AccountService_registerAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_registerAccount_Results(root.Struct()), err
}

func (s AccountService_registerAccount_Results) String() string {
	str, _ := text.Marshal(0xcd61f2c9baeb2c70, capnp.Struct(s))
	return str
}

func (s AccountService_registerAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_registerAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_registerAccount_Results {
	return AccountService_registerAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_registerAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_registerAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_registerAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_registerAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_registerAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_registerAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_registerAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_registerAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_registerAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_registerAccount_Results_List is a list of AccountService_registerAccount_Results.
type AccountService_registerAccount_Results_List = capnp.StructList[AccountService_registerAccount_Results]

// NewAccountService_registerAccount_Results creates a new list of AccountService_registerAccount_Results.
func NewAccountService_registerAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_registerAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_registerAccount_Results](l), err
}

// AccountService_registerAccount_Results_Future is a wrapper for a AccountService_registerAccount_Results promised by a client call.
type AccountService_registerAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_registerAccount_Results_Future) Struct() (AccountService_registerAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_registerAccount_Results(p.Struct()), err
}

type AccountService_updateAccount_Params capnp.Struct

// AccountService_updateAccount_Params_TypeID is the unique identifier for the type AccountService_updateAccount_Params.
const AccountService_updateAccount_Params_TypeID = 0x891fa8b6066a4ed5

func NewAccountService_updateAccount_Params(s *capnp.Segment) (AccountService_updateAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return AccountService_updateAccount_Params(st), err
}

func NewRootAccountService_updateAccount_Params(s *capnp.Segment) (AccountService_updateAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return AccountService_updateAccount_Params(st), err
}

func ReadRootAccountService_updateAccount_Params(msg *capnp.Message) (AccountService_updateAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_updateAccount_Params(root.Struct()), err
}

func (s AccountService_updateAccount_Params) String() string {
	str, _ := text.Marshal(0x891fa8b6066a4ed5, capnp.Struct(s))
	return str
}

func (s AccountService_updateAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_updateAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_updateAccount_Params {
	return AccountService_updateAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_updateAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_updateAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_updateAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_updateAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_updateAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_updateAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountService_updateAccount_Params) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountService_updateAccount_Params) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountService_updateAccount_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountService_updateAccount_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountService_updateAccount_Params) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountService_updateAccount_Params) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountService_updateAccount_Params) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasVersion() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountService_updateAccount_Params) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetVersion(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountService_updateAccount_Params) ClaudeSubCreds() (ClaudeTokenCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return ClaudeTokenCredentials(p.Struct()), err
}

func (s AccountService_updateAccount_Params) HasClaudeSubCreds() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountService_updateAccount_Params) SetClaudeSubCreds(v ClaudeTokenCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewClaudeSubCreds sets the claudeSubCreds field to a newly
// allocated ClaudeTokenCredentials struct, preferring placement in s's segment.
func (s AccountService_updateAccount_Params) NewClaudeSubCreds() (ClaudeTokenCredentials, error) {
	ss, err := NewClaudeTokenCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeTokenCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s AccountService_updateAccount_Params) ClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return ClaudeApiKeyCredentials(p.Struct()), err
}

func (s AccountService_updateAccount_Params) HasClaudeApiKeyCreds() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s AccountService_updateAccount_Params) SetClaudeApiKeyCreds(v ClaudeApiKeyCredentials) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewClaudeApiKeyCreds sets the claudeApiKeyCreds field to a newly
// allocated ClaudeApiKeyCredentials struct, preferring placement in s's segment.
func (s AccountService_updateAccount_Params) NewClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	ss, err := NewClaudeApiKeyCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeApiKeyCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountService_updateAccount_Params_List is a list of AccountService_updateAccount_Params.
type AccountService_updateAccount_Params_List = capnp.StructList[AccountService_updateAccount_Params]

// NewAccountService_updateAccount_Params creates a new list of AccountService_updateAccount_Params.
func NewAccountService_updateAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_updateAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6}, sz)
	return capnp.StructList[AccountService_updateAccount_Params](l), err
}

// AccountService_updateAccount_Params_Future is a wrapper for a AccountService_updateAccount_Params promised by a client call.
type AccountService_updateAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_updateAccount_Params_Future) Struct() (AccountService_updateAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_updateAccount_Params(p.Struct()), err
}
func (p AccountService_updateAccount_Params_Future) ClaudeSubCreds() ClaudeTokenCredentials_Future {
	return ClaudeTokenCredentials_Future{Future: p.Future.Field(4, nil)}
}
func (p AccountService_updateAccount_Params_Future) ClaudeApiKeyCreds() ClaudeApiKeyCredentials_Future {
	return ClaudeApiKeyCredentials_Future{Future: p.Future.Field(5, nil)}
}

type AccountService_updateAccount_Results capnp.Struct

// AccountService_updateAccount_Results_TypeID is the unique identifier for the type AccountService_updateAccount_Results.
const AccountService_updateAccount_Results_TypeID = 0xe83dabed9b090802

func NewAccountService_updateAccount_Results(s *capnp.Segment) (AccountService_updateAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(st), err
}

func NewRootAccountService_updateAccount_Results(s *capnp.Segment) (AccountService_updateAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(st), err
}

func ReadRootAccountService_updateAccount_Results(msg *capnp.Message) (AccountService_updateAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_updateAccount_Results(root.Struct()), err
}

func (s AccountService_updateAccount_Results) String() string {
	str, _ := text.Marshal(0xe83dabed9b090802, capnp.Struct(s))
	return str
}

func (s AccountService_updateAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_updateAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_updateAccount_Results {
	return AccountService_updateAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_updateAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_updateAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_updateAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_updateAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_updateAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_updateAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_updateAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_updateAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_updateAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_updateAccount_Results_List is a list of AccountService_updateAccount_Results.
type AccountService_updateAccount_Results_List = capnp.StructList[AccountService_updateAccount_Results]

// NewAccountService_updateAccount_Results creates a new list of AccountService_updateAccount_Results.
func NewAccountService_updateAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_updateAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_updateAccount_Results](l), err
}

// AccountService_updateAccount_Results_Future is a wrapper for a AccountService_updateAccount_Results promised by a client call.
type AccountService_updateAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_updateAccount_Results_Future) Struct() (AccountService_updateAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_updateAccount_Results(p.Struct()), err
}

type AccountService_removeAccount_Params capnp.Struct

// AccountService_removeAccount_Params_TypeID is the unique identifier for the type AccountService_removeAccount_Params.
const AccountService_removeAccount_Params_TypeID = 0xcfdc97e955c82412

func NewAccountService_removeAccount_Params(s *capnp.Segment) (AccountService_removeAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_removeAccount_Params(st), err
}

func NewRootAccountService_removeAccount_Params(s *capnp.Segment) (AccountService_removeAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_removeAccount_Params(st), err
}

func ReadRootAccountService_removeAccount_Params(msg *capnp.Message) (AccountService_removeAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_removeAccount_Params(root.Struct()), err
}

func (s AccountService_removeAccount_Params) String() string {
	str, _ := text.Marshal(0xcfdc97e955c82412, capnp.Struct(s))
	return str
}

func (s AccountService_removeAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_removeAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_removeAccount_Params {
	return AccountService_removeAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_removeAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_removeAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_removeAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_removeAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_removeAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_removeAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_removeAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_removeAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_removeAccount_Params_List is a list of AccountService_removeAccount_Params.
type AccountService_removeAccount_Params_List = capnp.StructList[AccountService_removeAccount_Params]

// NewAccountService_removeAccount_Params creates a new list of AccountService_removeAccount_Params.
func NewAccountService_removeAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_removeAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_removeAccount_Params](l), err
}

// AccountService_removeAccount_Params_Future is a wrapper for a AccountService_removeAccount_Params promised by a client call.
type AccountService_removeAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_removeAccount_Params_Future) Struct() (AccountService_removeAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_removeAccount_Params(p.Struct()), err
}

type AccountService_removeAccount_Results capnp.Struct

// AccountService_removeAccount_Results_TypeID is the unique identifier for the type AccountService_removeAccount_Results.
const AccountService_removeAccount_Results_TypeID = 0xf69c1e2bdba142bf

func NewAccountService_removeAccount_Results(s *capnp.Segment) (AccountService_removeAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(st), err
}

func NewRootAccountService_removeAccount_Results(s *capnp.Segment) (AccountService_removeAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(st), err
}

func ReadRootAccountService_removeAccount_Results(msg *capnp.Message) (AccountService_removeAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_removeAccount_Results(root.Struct()), err
}

func (s AccountService_removeAccount_Results) String() string {
	str, _ := text.Marshal(0xf69c1e2bdba142bf, capnp.Struct(s))
	return str
}

func (s AccountService_removeAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_removeAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_removeAccount_Results {
	return AccountService_removeAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_removeAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_removeAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_removeAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_removeAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_removeAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_removeAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_removeAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_removeAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_removeAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_removeAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_removeAccount_Results_List is a list of AccountService_removeAccount_Results.
type AccountService_removeAccount_Results_List = capnp.StructList[AccountService_removeAccount_Results]

// NewAccountService_removeAccount_Results creates a new list of AccountService_removeAccount_Results.
func NewAccountService_removeAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_removeAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_removeAccount_Results](l), err
}

// AccountService_removeAccount_Results_Future is a wrapper for a AccountService_removeAccount_Results promised by a client call.
type AccountService_removeAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_removeAccount_Results_Future) Struct() (AccountService_removeAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_removeAccount_Results(p.Struct()), err
}

type AccountService_listAccounts_Params capnp.Struct

// AccountService_listAccounts_Params_TypeID is the unique identifier for the type AccountService_listAccounts_Params.
const AccountService_listAccounts_Params_TypeID = 0x92070f51247244e5

func NewAccountService_listAccounts_Params(s *capnp.Segment) (AccountService_listAccounts_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AccountService_listAccounts_Params(st), err
}

func NewRootAccountService_listAccounts_Params(s *capnp.Segment) (AccountService_listAccounts_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AccountService_listAccounts_Params(st), err
}

func ReadRootAccountService_listAccounts_Params(msg *capnp.Message) (AccountService_listAccounts_Params, error) {
	root, err := msg.Root()
	return AccountService_listAccounts_Params(root.Struct()), err
}

func (s AccountService_listAccounts_Params) String() string {
	str, _ := text.Marshal(0x92070f51247244e5, capnp.Struct(s))
	return str
}

func (s AccountService_listAccounts_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_listAccounts_Params) DecodeFromPtr(p capnp.Ptr) AccountService_listAccounts_Params {
	return AccountService_listAccounts_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_listAccounts_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_listAccounts_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_listAccounts_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_listAccounts_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// AccountService_listAccounts_Params_List is a list of AccountService_listAccounts_Params.
type AccountService_listAccounts_Params_List = capnp.StructList[AccountService_listAccounts_Params]

// NewAccountService_listAccounts_Params creates a new list of AccountService_listAccounts_Params.
func NewAccountService_listAccounts_Params_List(s *capnp.Segment, sz int32) (AccountService_listAccounts_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[AccountService_listAccounts_Params](l), err
}

// AccountService_listAccounts_Params_Future is a wrapper for a AccountService_listAccounts_Params promised by a client call.
type AccountService_listAccounts_Params_Future struct{ *capnp.Future }

func (f AccountService_listAccounts_Params_Future) Struct() (AccountService_listAccounts_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_listAccounts_Params(p.Struct()), err
}

type AccountService_listAccounts_Results capnp.Struct

// AccountService_listAccounts_Results_TypeID is the unique identifier for the type AccountService_listAccounts_Results.
const AccountService_listAccounts_Results_TypeID = 0xeb097c133ce0ccbe

func NewAccountService_listAccounts_Results(s *capnp.Segment) (AccountService_listAccounts_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(st), err
}

func NewRootAccountService_listAccounts_Results(s *capnp.Segment) (AccountService_listAccounts_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(st), err
}

func ReadRootAccountService_listAccounts_Results(msg *capnp.Message) (AccountService_listAccounts_Results, error) {
	root, err := msg.Root()
	return AccountService_listAccounts_Results(root.Struct()), err
}

func (s AccountService_listAccounts_Results) String() string {
	str, _ := text.Marshal(0xeb097c133ce0ccbe, capnp.Struct(s))
	return str
}

func (s AccountService_listAccounts_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_listAccounts_Results) DecodeFromPtr(p capnp.Ptr) AccountService_listAccounts_Results {
	return AccountService_listAccounts_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_listAccounts_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_listAccounts_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_listAccounts_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_listAccounts_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_listAccounts_Results) Accounts() (AccountInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return AccountInfo_List(p.List()), err
}

func (s AccountService_listAccounts_Results) HasAccounts() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_listAccounts_Results) SetAccounts(v AccountInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewAccounts sets the accounts field to a newly
// allocated AccountInfo_List, preferring placement in s's segment.
func (s AccountService_listAccounts_Results) NewAccounts(n int32) (AccountInfo_List, error) {
	l, err := NewAccountInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return AccountInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// AccountService_listAccounts_Results_List is a list of AccountService_listAccounts_Results.
type AccountService_listAccounts_Results_List = capnp.StructList[AccountService_listAccounts_Results]

// NewAccountService_listAccounts_Results creates a new list of AccountService_listAccounts_Results.
func NewAccountService_listAccounts_Results_List(s *capnp.Segment, sz int32) (AccountService_listAccounts_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_listAccounts_Results](l), err
}

// AccountService_listAccounts_Results_Future is a wrapper for a AccountService_listAccounts_Results promised by a client call.
type AccountService_listAccounts_Results_Future struct{ *capnp.Future }

func (f AccountService_listAccounts_Results_Future) Struct() (AccountService_listAccounts_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_listAccounts_Results(p.Struct()), err
}

const schema_b1c2d3e4f5a6b7c8 = "x\xda\xecZ}x\x15\xe5\x95?g&77\xc1\x84" +
	"\x9ba\x02(\x82\x01L@\x10\x09Bq-\x8f4$" +
	"\x18!)\xdaLn\xd2*\xad\xca\xe4\xde!\x99\xe4\xde" +
	"\x99\x9b\x99\xb9HX(\xd2G\x9fG\xb0\xb6B\xd5\x0a" +
	"\xd5.\xb0m\x15\xba\xae\x82U\xd4\xb5~\xb0~ U" +
	"\x8b_+X\xed\xa3\xbb\xa0\xa2P\xc1\x85]\xd1\xb2w" +
	"\x9f\xf3\xdeyg\xe6\x86K>|\xf4\xe9?\xfd\xef\xde" +
	"3g\xdey\xdf\xdf\xf9>\xe7\x9dvd\xe8\x9c\x82\x0b" +
	"K\x9f?\x13\x84\xe8X\x0c\x15fn\xdd\xb2x\xed\x87" +
	"\xd7O^\x05\xd2\x04\x04\x08a\x18`FC\xc9N\x04" +
	"\x94\xaf*\xa9\x01\xcc\x08\xad\xc5\xffX|\xc2\xbe\x09\x94" +
	"\xb3\x908\x04\xe2XQ\xd2F\x1c\xabK\xee\x07\xcc\x9c" +
	"\xdd\xbdq\xeb\xc7\xcf\xde\x7f\x13Hc\xbc%\xaaJ7" +
	"\x13\xc3\xccRZ\xe2\x8d+:\x0b\x1f\xbe\xb7b5(" +
	"c\xd8\x12\x85\xc4\xd1Z\xba\x0e\x01gh\xa5?E\xc0" +
	"\x93{\xb6\xfe\xe4\x8d\x99\xd7\xafV*Q\xe0\x0c\xc5\x91" +
	"W\x89aL\xe4y\x04\xccl\xcc\xd4w]=\xed\xe6" +
	"5 E\xc4\xcc\xe6\xa3\xef\xee\xdb\xb5\xe37\xc7\x01P" +
	">^\xf6\xb9\x8cR\x18@>Y6O\xae\xa2_\x99" +
	"\xf9\xcf\xbd\xbf\x01{\xd6\xae\x01i\xa8\x98!\xc6\xfd\xaf" +
	"\xed\xdcF\xcc\xa5\xd2G\xf2Y\xc42c\xb8\x14F\xf9" +
	"Y\xc6]}\xc5\xdco\xcez3~sp\xff\xf7I" +
	"\x8f\xd1\xfe\x7f/\xd1\xfe+\xa6>\xbc\xfe\xacK>\xfd" +
	"\x09HC\xd1_.\x8b\xc4;\xd2t\x94\x0f\xb3\xef\x1f" +
	"\x94\xae\x03\xcc\x1c\x18\xf2_\xcb\xde\xbc\xb7\xf6\xa7\xc1\xd5" +
	"\xea\x87\xd1Y\xe5\xd6a\xb4\xda\xd9O\x94}0\xf3\xc7" +
	"\x8bo\x05\xa9\xc2cH\x0f\xb3\x88a\x15c8p\xa9" +
	"U\xa9D\xc2\xeb\xb2+\x14\xd0\xf3M\xc3\xd6 \x14d" +
	":\xee\xf8|\xc3\x91\xd4\xfa\xdb@\x99\xc0\x80\x0c\xd1\xb3" +
	"\xb5\xc3h\xab36\x0d\xfb\x1e\xe1\xf4\xaf\xd3\xe7O\xb8" +
	"\xf9\xd0\xc1\xdb\x02/\x9f\x947\xd0\xcb\x97\xfe\xef\x8b/" +
	"|q\xd9\xf5w\x81R\x8a\x98qO\xb1\x11BE\xb4" +
	"\xf7\xc3\xf2c\xf2q\x99\xb8\x8f\xca\x19Zgyd\xca" +
	"\xea\x09\xbf\xd9\xfeKP\"\x88>\xe0!\x91\xad8\\" +
	"@\xb9x\x04\xbd\x18\x1a\xf1\x01`f\xcb_\x86\xaf\xbb" +
	"\xa3|\xd1F\x90\xce\xf4\xcet`\xc4x:\xd3\xe1\x11" +
	"t\xa6kNJ\xbb\xf7\x9dX\xba)\x88J\xe9H\xa6" +
	"fcF\x12\xc3\x8e\xeao\xbdU\xfcx\xe7f~\xb4" +
	"!\xc41{\xe4n:\x9a2\xf2\x1e\x010\xb3x\xfa" +
	"\xe4\xaa1\xa9\xe2\x7f\x06i\xa8\x90#\xd5\x99\xa3^\x95" +
	"kG\xd1nf\x8f\"\x85\xdc\xb4\xf1\x1f\xaey\xe6\xbb" +
	"\xcb\xef!}\x138L\x8f\x8e\"\x8d\x9c\xf1\xc2(\xd2" +
	"\xb7\xccog\x7f0\xb6\xe5g\x0fm\x05i\x84\xb7\x1f" +
	"}\xf4B\xdaOz4\xed\xe7\xdak?\xb9\xfd\xc4E" +
	"\x13\x1e\x08\xe0\xb8~4\x13\xc2\x15\x8b>k{y\xd5" +
	"\x0f\xb7\x07\x9e\xac\x1e\xfd\x18=y{\xc3e\x15\x8f\xd4" +
	"\x0fy\x18\x82j\xdc3\x9a\x9d\xe1\x96\xd1L\x8d_<" +
	"\xffu\x1c\xbb\xe5\xc1\x1d\x04\xab\xd8\x0bVY;\xe7-" +
	"\xb9\xfb\x1cz)y\x0e\xe3\xc6\xdb_~\xe8\xfb\xce\xbc" +
	"G@\xaa\xa4]2\xec\x1b\xc6ng\xc69\x96Nz" +
	"}\xdd\xd3\xe6\x88;\x0aw\x06q?1v21\xe0" +
	"8:\xc6\xb6\xa1\x7f~\xaah\xe5\xd2\x9d\xa7\x98\xcd\xb8" +
	"q\xdb\xe5I\xe3\xe8\xabU\xe3\x9e\x97\xb7\xd0\xaf\x8c\x10" +
	"\x9b\xf5\xfe\xd6\x0f\x1f\xde\xc9\xcc\xe6A\x97\x9b\x98\xd7\x8e" +
	"\xfbH\xbe{\x1c\xc3`\xdc<\x94W\x8c\x0f\x03<\xf9" +
	"\xf35\xcf]\xb9y\xe4.e(\x06\x8c\xa2\x1e\xc3\"" +
	"\xc0\x0cm\xfc\x10\x94\xd3\xc4&w\x8f\xa7\x8dV\x1a\x9b" +
	"\xab\x12O\x8fz\x01$Y\xccdw\xb1\xff5\x00\x9c" +
	"1\xfc\xdc\xe9(W\x9dK\x9c\xe3\xce}^\xfe5\xfd" +
	"\xca|gH\xe9\xbf\x1fZ\xfe\xe6nPd,\xf0\xd9" +
	"\x09k\xf9\x96s?\x95\xd73\xfe\xdb\xcf%\xd5\xdb\xf1" +
	"\xdf\x89\x83W6\x1c\xdb\xedJ\x92\x19eOe#A" +
	"pc%\x19\xe4e\x97\xef\xdd\xfb\xe9=\xeb\xff\x10\x90" +
	"\xd7\x81\xca\xcd$\xafo}\x7f\xe7\x03k\xa7<\xff\x87" +
	" \xbcoT2\xa5<PI\xbbNM\xf9\xf8\xb1\x17" +
	">U_\xe2\x8e\x8b\xe1{c\xd5V\xe2\xb8\xbd\x8a\x16" +
	"\xdf\xb5vO\xcb\xfd\xab\x86\xbc\x9c5f\xb6\xf8\xd1\xaa" +
	"e\xb4\xf8\xb2\x7f\xbbxd\xf9\xb0=\x7ft\x17\xcf:" +
	"\x8b*\xe6U\x0e\xb3W\x87U\xeej=\xf8\xf3\xb7\xff" +
	"\x184\x89\xcb'0Gq\xf5\x04\x92\xdd\xb1\x8b\x8f>" +
	"6\xfb\xd5-\xaf\x06\xb7\xb7j\xc2n\xf6\xf1\x09\xb4\xbd" +
	"\xbb[\x1b\x1bjB\x8b^\x0f\xae0s\"\xdb]\xfd" +
	"DZa\xef\x84\xf5\xf3oz\xb2\xe9\xcd\xc0\xd1\xb5\x89" +
	"\xdbiwv\xcb\xfb\x1d?\xbc\xe8\x91\xb7@\x1a&f" +
	"\\|w\x92<Z'\x8eGY\x9bH\xac\xea\xc40" +
	"\xca\xc3\xcf#\x81|\xb1bA[\xe3\xe1K\xdf\xce\x82" +
	"\x9c\xf5*\x13\x9bi\xa1d\xcf'-\x07*\xbe\xf1g" +
	"P\x86b\xc0*\x99\xcd\xc9\x07'\xbe*\x1fgk\x1d" +
	"\x9d\xc8\xcc\xae\xe2\xd7\xb7\xbe\x14\xd91\xe9?A*\x11" +
	"3\xae6\xeeg\x1a6i\xb7|\xf7$zg\xfd\xa4" +
	"y\xf2\xb3\xf4\xeb\xe4\xb6W\xb6\xfe\xec\xbb\xbf<\x104" +
	"\xa6\xfb&\x09\x02\xe0\x8c\xa7'1\xf3\x10\x8a\x8a\x7fq" +
	"\xf8\xb7\xb3?\xcc\x11\xcf\xfa\xf37\x10\x00[\xce'\x8c" +
	"O\x14\xce\xad~mG\xed\x87 \x9d\xe51\x84\xa60" +
	"3\x97\xa6\x10B\xaf=\xb5\xa0\x16\xdb\xa7}\xe4b\x9c" +
	"\x85p\xca\xe7\xc4\xd0\xc0\x18\x9ex\xf1\xddK\xe4\xe5\xc5" +
	"\x1f\x071NNaRZ\xc1\x18\x9e\xbd\xe7\xd1\xbf\xbc" +
	"3{\xe3!\xee\xb8\x188\xdb\xa60\x9f\xfc\xf4\x94\x0a" +
	"\xda\xe7?uL\x9et\xc7\xa2\xe7\x0e\x05c\xec\x81\x0b" +
	"\x98\x19\x1f\xbf\x80\xd6\xb8D\xf8\x8f!\x17\xb5&>q" +
	"u\x98-q\xd6\xd4fb\xa8\x9aJJ~\xe0\xdb\x0f" +
	"\xec]\x92\xde\xf8\xc9)\x96\x89\xd5;\xe5\xe2j\xe6\x88" +
	"\xab\xe7\xc9\x17\xd0\xaf\xcc\xd6\xe9OtV\xdf|\xe4H" +
	"\xf0s\xc3\xab\xd9\xe7\xaa\xaa\xe9s\x1b\x1fx\xee\xce\xfb" +
	">\xbb\xfbX\xbex\xd6P=\x19\xe5\xab\xd8\x8a\xad\xd5" +
	"\x04\xe1\x93u\x9b\xfet\xfe9w\xfdO\x0e\xc8\x8fV" +
	"3\x90_`\x1c\x1b\xce\x1b\xbe\xe1\x9bg\x17|\x11P" +
	"\x8e\xaaiL9\xfe\xb4\xf2\xd8/\xde|\xeb\xc1\x93A" +
	"\xdb\x94\xa61\xdb\x1c3\x8d^\xdd/\xbc\xf7\xee\xf7\xae" +
	"9p\x92\x0c\x1d}Cg\x1f\x91WL\xfb\\^=" +
	"\x8d~\xdd8\xed:03\xb1\x84\x9a\x8ek\xd7v\x17" +
	"\xa65\xabgjLM\x19\xa9Ys\x19M!JT" +
	"\xb3\x96\xe81mj\xbb\xe64Y\xe6b=\xa1U6" +
	"\xa9\x96\x9a\xb4A)\x10\x0b\x00\x0a\x10@*m\x06P" +
	"JDT\xce\x140\xa3\xc6bf\xdap\x1a\x00\xe3X" +
	"\x02\x02\x96\x90\xc9[\xe6RZ\xbc\x80Vo\xa2?|" +
	"\xdd\x94e\xb6i\x8cR\xd9\xac\xd9\xe9p\xc2\xb1\x95\x12" +
	"o\xe1\xfa:\x00e\x8e\x88\xca\x02\x01\x11\xcb\x09*\xa9" +
	"\x81h\x97\x8a\xa84\x09(\x09XNz,]N;" +
	"X \xa2r\xa5\x80+\xedt,\xa6\xd96\"\x08\x88" +
	"\x80+\x93\x9am\xab\xedZ\xeen\x1a\x8c\xc5\x80&\x96" +
	"\xf9\x11\x1c\x10\xcb\x00\x09\x10#\xae\xd9SC\x1e\x16\xf4" +
	"\x97\xef\xd7=\x9d\xfb\xd7\xdfs\x00\x8c\xf1\x00J\x91\x88" +
	"J\xb9\x80a{I\x0c%?s\x02D\x09<\x88\xf8" +
	"'js\xd6\x9c\x9aN\xc5UGs\x89Y\xb4\xd1V" +
	"F{\x1fx\x88\xce\xfa;\x11\x95\xa7|P~\xdf\x06" +
	"\xa0<.\xa2\xb2+\x00\xca\xb3\x8d\x00\xca3\"*{" +
	"\x04\x94D\xa1\x1cE\x00\xe9\xa5\x85\x00\xca\x8b\"*{" +
	"\x05\x94\x0a\xc4r,\x00\x90\xde L\xf7\x88\xa8\xbc-" +
	"\xa0\x14*(\xc7\x10\x80\xb4o\x19\x80\xb2WDe\xbf" +
	"\x80Ra\xa8\x1c\x0b\x01\xa4\xf7\xd6\x01(\xfbET\x8e" +
	"\x9cF\xd4.\xad\x05\xc2=)\x0d#~~\x01\x88\x11" +
	"\x0e~\xab\x95\x00\x00\xef\x9d\x98i,\xd6\xdb\x1bm\x10" +
	"M\x83\x13W.\xd1,[\xf7\xff\xbb\x8a\x1aMCM" +
	"\xdb\\K\x8b\xdbX\xe6\x9b\x9c/\xbat\\\xabM\xa1" +
	"\xfem\xad\x87\x98\x90\xb8\xbcD3\x87\xebZ\xb50\xed" +
	"t\xe4(|m\xda\xe9\xe0B\x88\x99\xc9TBs\xb4" +
	"\x05f\xbbn01'\x1c\xb4\x95\xb1\x9e\x14^\xa9\xf3" +
	"q\xe4R\xc8\x81\x91Ka_[\x00F.\x85\xf7:" +
	"\x01\x94wET\x0e\x91\x140+\x85\x83$\xd8\x0fE" +
	"T\x8e\x91\x14\xc4\xac\x14\x8e\x12\xf1\x88\x88\xca_I\x0a" +
	"\x05Y)\x9c\x98\x0e\xa0\x1c\x13\xb1\x19\x05\x94\xc2\xa1r" +
	"\xb2l\xe9$\xc9\xeb\xaf\"F\x8bp\x00F\xa0\xb2\xc7" +
	"-&\x84\xbb4\x1fdK[livG\x0bD\xcc" +
	" Y[\x9a\xd2-\xcdn\x004\xb0\x18\x04,\x86\xbc" +
	"\xc2\xaf\xd0\x92\xaa\x9e\xf0\xde2\xadv\xd5\xd0\x97\xa9P" +
	"\xe3\xe8\xa6\xd1\xe0\xebHLM$\xda\xd4X\x97\xc0\xe1" +
	"w\xffGk\xb2\xe87!*\x05b\x08\xc0K\xeb\x91" +
	"\xa7\x04\x92T\x07\x82\x14\x0a\xaf\x8c\x99\x86\xa1\xc5\x9c9" +
	"\xd8\x84\xbeA\x09\xbd\x0d*\xc2\x97+c\xcb\xf1\x1c\x16" +
	"y\x0e\"u\xff\x08\x04I\x0f\xa3_O!\x0f\x80\xd2" +
	"\xd5\x16\x08Rk\x18\x05/\xab@\xee\xb7\xa5\x06zV" +
	"\x1bF\xd1+,\x90\x075if'\x08\xd2\x05\xe1\x8c" +
	"\xa5\xb5\xeb\xb6\xa3Y\xe8\xee\x07\xe6`\x86\x1b7T0" +
	"\xd2\x1c\x82<i.\xc9\xa1$t\xdb\xa1W \x926" +
	"\x1c;{\xc2\xbe\xbdR\xac\xb7\xfeV6\xd70\x95\xed" +
	"\xc71y\x09K/\xc7$\xe6\x98E\x8a\x9b\x93fT" +
	"8\xba\x9a\xb0\x09\xd0\"o\xddI\xb3\x00\x94J\x11\x95" +
	"i\x02J\xdc\x14. S8OD\xe5\x1b\x02\xd6\xa8" +
	"l\x05\xcf\xb2\xdbT[k\xb5\x12A\xcb\xee\xe3l\xa9" +
	"@\xb8\xf0\x0d\xb1\xcfcy\x09\x91{,\xaeo\x05\xbd" +
	"\xf5\xcd3v\xa6K\x95M\x15,\xb4\x05\x17\x9f\xe5/" +
	"^c\x99i\x92\xa6\xe4\xe7\xff\x03\xf2\xe7\\\x9c$L" +
	"\x1e<\xc1\x8b\xbb\xa1~\xe3n+\xd9\xad/\xd03\xbd" +
	"\xcd\xad'\x8co\x13Q\xd9\xe8\xbb\xa0\xbb\x89v\xa7\x88" +
	"\xca\xaf\x02.h\x13\x05\x82\x8d\"*\xff\x12pA[" +
	"\x88x\xaf\x88\xca\xef\x02\x81`\x1b\xf9\x90\x07DT\x1e" +
	"\x0f\x04\x82G)d<\"\xa2\xf2\xcc\x00\xfc\xcab}" +
	"\x896\xdfL[\xe4\xdf\xcb\xfcT\xc4\xf5\xbd\xb6\xb6D" +
	"3.U{\xfayZ\x13%\x898yX\xb4\xa5\x8e" +
	"\xa5\xb6\xda*\x88\xed\x1a\x96\xf95\xcd\x97\x09\xde$\x0b" +
	"1igbf2i\x1aSc\xa8\xba\xe9I\x0dK" +
	"\x0fLR\xf3J\x0f\xed\xc3\xa3\x02\xde\x99\xc3}\x94\xe0" +
	">$\xa2\xf2\x19\xc1-d\xe1>>+\xe0\xb2E1" +
	"\x0b\xf7\x89\xc9\x01\x97]P\x90\x85\xfbds\xc0ec" +
	"\x88\xc1-\x87p<@3\x8a\x18-A?\xf2\xca\xc5" +
	"\xb8\x0c ZD\xf4r\xe6\xf6\x0b\x99\xdb\x97%\x9c\x0c" +
	"\x10-!\xfa\x99D/\x0a\x97c\x11\x80<\x1c\x1b\x01" +
	"\xa2\xe5D\x1f\x8b\x02\x8az\xca3@\x86\x82\xe5\x19d" +
	"\x0d9*?\xd2Fb\xba\xd3\x13\x8c\xcd\x8enh\x06" +
	"\xa0\xc3ia\xd56\xb0\x08\x04,\"\xdd\xb7\xbf\xc3\xdc" +
	"<\xd4,S\x9d\x9cU\xcc\x84\xe9\xad\xe2\xe8Im\x99" +
	"ih9Q\xdf\xb5B\xd1\xd5\xfe\xa8cijrn" +
	"G\xda\xe8\xaa_\xa2\x19\x0ed\xfd6\xc7_%\xac\x16" +
	"\x89\xa8$|m\xd7I3;DT\x9c\x80\xb6w\x13" +
	"cJDey@\xdb{\x08~GD\xe5\xfa\xd3\xe4" +
	"-1\xfan\x83\x11\x07Q[\xea\x1d\x8e\xf4\xd1i\xe9" +
	"I\x01z\x0a\x1e\x89\xab\x8ez\x8a\xebr\x1df\x9di" +
	":\xb6c\xa9\xa9\xa9j\xda\xe9 \x05\x0b\xf7\xf2'\xd3" +
	"}\x7fR\xe1\xe4\xc4X\xbeTa\x1f\x1e>\xe8\x1a\\" +
	"_\x98\x9b\x88\x9f\xea\x0b\xbd\x1e\x01\xf7\x85\x83\xce\xf7\xf9" +
	"w@\x99\xc6?$\xd7b\x1d@\xf4\x12R\xae\xf9\xe8" +
	"\xc9C\xaeg\xe49D^\x80\xbeH\xe4\x06l\x06\x88" +
	"\xce'z\x0b\xfaR\x91\x15\x9c\x0e\x10]@\xf4+\xd1" +
	"wCr+\xb6\x01D[\x88\xbe\x08}O$_\xcd" +
	"\xd6\xf9\x01\xd1;\x82\xb6\xa11\xdb\x88\x13=\x15\xb4\x8d" +
	"$\xae\x01\x88\xa6\x88\xbe<h\x1b=h\x01D\x97\x12" +
	"\xfd\x06\xa2\x17c9\x16\x03\xc8\xabp+@\xf4\x06\xa2" +
	"\xdfJ\xf4!E\xe58\x04@\xbe\x85\xed\xe7\xc7D\xbf" +
	"\x93\xe8g\x14\x97\xe3\x19\x00\xf2\xed\xb8\x1d z'\xd1" +
	"\x7f5\xc0\xa4\xab\x9f\x9c)\xae\xdb\xa9\x84\xdas\x05\x84" +
	"\xd5\xa4\xff^\xcc\xd2TG\x8b\xd7\x06\x8c\xf0\xf4\xd9\x15" +
	"\x7f\x80Do\xe9Ii\x01\x9b\xb3TG[\xa0'u" +
	"\xa8pZt\xcd\xf2\xe8\x1d\xaa]O\x9e\x15Y\xb0\xa9" +
	"7\xd4H[B\x8b\xf3sd\xda\xf4DB7\xda\xdd" +
	"\xa4\x9e\xbfd\xa7\xdb\xec\x98\xa5\xa7\xd8\x87\xe6Z\x9aZ" +
	"A{tz\x9f\xb6WV\xd6\xd2\x93B\x96\x92\x8d\xce" +
	"VnuL3\xeb7\x00\xa0 \xd5S\x8d$J\xf5" +
	"\xeb\x00\xb0 K\x0cI\xf5\x9d\x00X(\xd5.\x04X" +
	"\x996\xba\x0c\xf3:\xc3\xab\x060\xbb\x05G\x17MN" +
	"lR\xb1\xa7\xd6\xbe\xcaL\xcf3)\xce\x9aqmi" +
	"4\xdd\x86.\x9f\x89F\xa6]K\xea\x86\xde\xeb\xe5," +
	"\xb16\x05\x11JV2\xeauv\x9d\x16\xb7L\x10c" +
	"]\xfd\x04x\x9e\xe7\x05J6f\xf6_Y\xc9FA" +
	"f\x97\x88\xca\xeb\x81H\xfd\xca\xc2`\xc9\x86n\xc9\xd6" +
	"\x1c,\xd9\xdcb\xe1\xbd6\xbf\xd6\xf8\xaaJ\xb6S\xab" +
	"\xb3<%\\\xde\xb2!\xc6\xf2HG\x87\xb0\x9a\xb0\xb1" +
	"\x8c7<y\xfc\xee\x95\xa95\xb3\x94k*\xcb\xbc\x9a" +
	"\xb5\xee\xb4f;Y\x7f$\xe6\xa6\xb6\xfd5 \x06\x91" +
	"b\x063\xb4~S\xee\x1c\x87\\\x93}u`\x05&" +
	"\xaf\xb4(\x06\x04\\\xec\xdf\x0b\xcc\xaf\xa3\xc0d^\xad" +
	"YK\x99\xa2\xe5\x90\xeb\x09\xa0\xdc\x1c@\x94\xc3\xbc\x8f" +
	"\x12\xb8\xd7ET\xde\x0ddu\xefL\xf7aF7\xa9" +
	"\x0b\x9a\x96\x8frg\x10e\xc1E\xd9\x0a\xa2,\xba(" +
	"\x93\x0d\x7f&b\xb4\x80\xc1,d\x83\x16\xe2\xc2@\xfe" +
	"\x97\x0f\x86^\x05UE\xd2\x8ck>*\xba\x91J;" +
	"-f\x17\x845\xc3\xf6R\x193\xed02D\xba\x82" +
	"d\xa7C7\xbat\xa3\x1d*\x16hK\xb4\x84G\xb7" +
	"\x1d\xd5I\xdbsM\x10\xe3\x9aG\x8c\xa7-\x96\xe3\x81" +
	"x\xb9\xed\x1b\xb4\xab\xed\xa1\xbe\xb4\xddvT\xcb\xc9\xf6" +
	"Rx\x91\x15\xe8\xf2\xb5\x05:z\\\x06\x977\xfa\x1d" +
	"=O\x06\xad\xa4\xffM\"*?\x10H\x95\xe2\xba\xa5" +
	"\xc5\x1c\x08\xb7Zzns\xaf?g\xd5g\xd6\xd6\xac" +
	"\xd9\x91\xde\xa5s\x9d\x9fW\xad\xb4\xb3gB\xc9\x1f\xed" +
	"\xf4\xaa3\x91{\xaf\x0a\xe6\xbeH\xe3JX\xff\x81\xb7" +
	"\xa4\x91O\xca$\xa5\x13\x04\xa9!\x8c\xe8\xb5u\x91w" +
	"~\xa5\xd9m H3\xc3(x\xe3\x18\xe4#\x03i" +
	"\x12=\x1b\x17\xcep\xcf\x08\x11\xf2\x8d\xac\x9d\x902-" +
	"\xa7\xd5\x86\xb0\xda\xaey\xff\xe7v@8mt\xe5\xf6" +
	"\x12\x84\xde\x8e\xcd\xeb\x96\x94\xb3\xdd\xf2\xa9'\xf2Y\xb4" +
	"\xb4v\x19\x08\xd2j\xda-\x1f\x82 \x9f\xf3J+\xd6" +
	"\x81 \xf5\xd0n\xf9,\x0f\xf9|RJn\xc8vY" +
	"Do\x02\x88|\xa2+]\xdd\x99\xed\xb2\x14x3%" +
	"\xe4#\x18\xa9\xe1G\xac\xcb\xc2m \x0an\x83h\x8e" +
	"\xd7\xebK#W2\xf4\xa9J\x1a\xb9[\x16\x193w" +
	"\xf0\x10\xe1osI\xb9\x0a\x0a\xb9}$1'\xce\xcf" +
	"uC\x96\x9a\xb0\x01\xb2\xc2,(\xc9d\xb2\xba;\xd9" +
	"\xefP\x97\xe2\xffe\xdc\x1e5y\xca\xf9\"*-\x02" +
	"\x96\x0a'3Y\xedU\xd6\x01(-\"*\x8b\x04\x8c" +
	"\x18T\x0d\x15~\xe5]\xcdn\xf1ty}\x85\xd7Z" +
	"\xcb\xea\"\xbf\xa3\x80|H,)\x0b\xb9.\xf2\xd9\x0a" +
	"\xf2\xd9\xb84\xbb\x91\xeb\"\x1f\x84 \x9f\xd1H\x93\x1a" +
	"\xb3\xba\xc8k\x06\x10\x13\x841o]\x00@\xf6_\xb3" +
	"\x99\xd0l\xf6\xcf\xd5B\xb6a!\xb0a\x96\x83V\xb0" +
	"\xb7N_\xfcy.B\xef\x0cV\x7f\xae\x8b\xe8n\x0b" +
	"V\x7f\xae\x9f\xee!\xe2R\x11\x95\x1b\x04\xcc\xe8v\xbd" +
	"\xa1\xb6%4r\xa8<\xc1M\x9a\x86\xd3\x91\xe8Y\x00" +
	"\x11=\xa9;\x18\x02\x01C\x80\x99\xb4\xad\xc5\x09q\x08" +
	"\xeb\x8e\xedS\x1d=\xa1/S\x1d\x08\x93S9\x03\x04" +
	"<\xa3\x8f\xd4\xc5\xb5\xbf\xb4\xd1\xe5\xa5\x16\xc1\xe6Y\xb3" +
	"\xdf'\xf3\x0ev!\x85\x9a)\"*\x1737\xc7\xd2" +
	"\x9e\x9c0\xc8\x8aU,\xf3\xef\x13\x0c\xa8\xfd\x11\xcbm" +
	"{\xf1<\xf5K\xe4+|\x04\x14\xf0\xe1\x9d_\xd2\x87" +
	"\xe7M\x07\x06\xe2\xc4\x07\x97\x93{N=\x00}\x9d\xdf" +
	"\xb7\xcc\xd7\xb6\xec7\xc3\x19h[\x91\xb7\xee\x06\x1d*" +
	"\xbd\x9e_\xfeM\xfb\xcd\xd6f__VR\x0c\x0bv" +
	"Wm\xcd&\xdc\xf2e\xfc\xa7\xc5.\xdb\x91\xce\x1d@" +
	"\x0d.\xdb\x1e\xec\x84\xc53\x8d\x80J5\xe7S\xa9\xc9" +
	"\xbeg\xf5TJi\x0b\xa8T\x9e\xf3F\xa8\x08<E" +
	"l\x947\x0c\xb4\x09\xdd\xdbt\xf2\xe5\x08\xa7\xf6^\xbc" +
	"\xebU~\xefePM|7U\xf2\xf0\x14O\x87g" +
	"8g\xca\xc1/\xb8 \xbf-!u/\xe4S\x0e~" +
	"\xfd\x01\xf7@\xf6rX`\xca\xc1on \xbfr#" +
	"5t\xf2)\x07\x1f\xe9\xe36\xc8^ \x90fn\x06" +
	"A\xba0\x9c\xe1\xfa\x0a\xa2nPdu\xc5\x0a\x15L" +
	"\xb0sz\xdb\xb8O\xa8E\xb7\xee4\xc3\x8c\xce\x82B" +
	"\xffN\x94\x8f\x00N\xd3^h0\x16#\xeb\xdc~=" +
	"\xd5\xb7\x9b\xe3\xe7\x94\x0d\xbc\x92\xda\xb7\xf0oU}\xe7" +
	"-\xb4\xf3U\xe4}W\xdf|L/\xf4\x1e\xd3g\xd3" +
	"\x9e\xecH\x8e\xdf\xfe@~\x87Q\x92H\xbb\x8a\xc3\x19" +
	">\xcb\x07qiON\x8cW\xc3\x03\x88,\xbc=\x94" +
	"S\x10\xff\xbd\x1e\xfeJ\xea\xe1\xc1\\8\xf0\xda+_" +
	"a\xa4\x1c\xd0\xfd\x0fw\x1c\x13t\xa9\x8d\x81@\x93\xf7" +
	"\xe2\xc0 2\x97\x1c\xfdr[5\x83\x09j\x83\x18\xf2" +
	"\xe5\x9bR\xf2\xa3\x9c\xe7/O\xb90\x0e\x05l\x12\x11" +
	"\xcb\xfc;_\x80D\x1c\xc4\x80\x90\xe5\xd5~\xb2P\xee" +
	"}tE\x9d\x9f\xf6r\xb9\xad\"\xdar\x11\x95\x9b\x02" +
	"&s\xe3\x1a\x00\xe5&\x11\x95\xdb\x02&\xb3\xd6\x02P" +
	"n\x15Q\xb9+\xd0v\\O\x9cw\x89\xa8\xdc;\x00" +
	"\xb1\xe7t\xa2i\x97\x01\xd1]gZ]vJ\x8dA" +
	"\x85FO\xf2\xbfs\x85\x9a\xd4N\x15\xf7\x80g\xa6y" +
	"\xe6\xb9\xfd\xa6.\x03h@\xf2\x8c\xa8\xbf\xf2d\x16\x80" +
	"\x12\x17QI\x05R\x95\xe4\xf4@\xcd\xc2\xcb\x93\xeeF" +
	"\xbff\xc9\x97\xef\xf7\xdd\xef\xd1\x8cx\xca\xd4\x0d\xa7\x97" +
	"a\x04K|\xaf\xc3\x11\xf0\xe3\xfcv1\xf2\xeb\xae\x92" +
	"4\x99]\xad\x88P\x06\x99[\xa3\x0dT\x07\xbf\x04\xe0" +
	"y\xaf\x1c0#u\xcb\xeeH\x9e\x1b\x07m\xf9\x8a\xa6" +
	"N6\xa1B\xe5\x12a\x90\xcev0\xd9\xf0\xd7\xe1\x1d" +
	"\xfbLz\xdc\xe9?Oz\x06\xc0;\xe0*sV\xdf" +
	"UfMvQ,\xf3\xefW\xf7\xea5\x04Kw\xf6" +
	"\xed\x9a&\xcd\xd2\xcd\xf8\xe9\xa5\xe5}\xbb1 \xac\xfc" +
	"\xf5\xb4\xa5\xd9\x9ac\xd7\x06\xd5\xfa\xff\x03\x00\x00\xff\xff" +
	"\xaf\xe2?X"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b1c2d3e4f5a6b7c8,
		Nodes: []uint64{
			0x812a80e89166a990,
			0x8873f9097b095502,
			0x88afc5ebaaa0711b,
			0x891fa8b6066a4ed5,
			0x898035d58eaa00d0,
			0x8a8b305d6b45ffa0,
			0x8a9179019ae6c648,
			0x8b64d73a39434e2f,
			0x8ef23c1999b62e1f,
			0x8f41a8d77ae30ae5,
			0x90668c35e710be1b,
			0x92070f51247244e5,
			0x949970f09afa9668,
			0x94e9ec8b264832ae,
			0x9c8046fbc9ccf744,
			0x9eb2a626892c0f7c,
			0xa06014969215eea9,
			0xa178f9d9ca11fd5e,
			0xa26abc09da3e2fb7,
			0xa309701d252a3266,
			0xa77c56c45e37a0a1,
			0xaab5935420e73dab,
			0xb02636f995ef5f5f,
			0xb27e81ce62f8604e,
			0xb60a45b81f469adc,
			0xb7b3a92001d42bcc,
			0xb847745bb5ce9501,
			0xc20696166fc14280,
			0xc2787f08c0de0eb1,
			0xc2b6e8aae63a6302,
			0xc80017a258c68a97,
			0xc91ac16c25a26e24,
			0xcad77cecc30d0a4f,
			0xcaf44958e96cf3b7,
			0xcb99a7f2d8d84d46,
			0xcbc72c91b0c25b3e,
			0xcd61f2c9baeb2c70,
			0xce0a81af54d091c8,
			0xcfd012141738bb7a,
			0xcfdc97e955c82412,
			0xd2a9d23dbaf138f4,
			0xd460053f494a559d,
			0xd750bf88489926d8,
			0xdab8367e68e65473,
			0xdc44ed4a624c7dfb,
			0xde341fe554ef796d,
			0xe229b70fcd90a51f,
			0xe59e5693aad100b1,
			0xe83dabed9b090802,
			0xe841b7d32f4306f9,
			0xea306701414cc0d3,
			0xeb097c133ce0ccbe,
			0xeca03dddeeb9a7c5,
			0xecc66096292a689f,
			0xef6c55360ad6023c,
			0xefa07576d8b04be5,
			0xf0f08b2f6abe32aa,
			0xf49df8ad98c6b0a0,
			0xf69c1e2bdba142bf,
			0xfb041b399a15289a,
			0xfdb3dad79bf47fdb,
			0xfde55e57e0e102e4,
		},
		Compressed: true,
	})
}
