// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	strconv "strconv"
)

type UsageReport capnp.Struct

// UsageReport_TypeID is the unique identifier for the type UsageReport.
const UsageReport_TypeID = 0xb7b3a92001d42bcc

func NewUsageReport(s *capnp.Segment) (UsageReport, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 3})
	return UsageReport(st), err
}

func NewRootUsageReport(s *capnp.Segment) (UsageReport, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 3})
	return UsageReport(st), err
}

func ReadRootUsageReport(msg *capnp.Message) (UsageReport, error) {
	root, err := msg.Root()
	return UsageReport(root.Struct()), err
}

func (s UsageReport) String() string {
	str, _ := text.Marshal(0xb7b3a92001d42bcc, capnp.Struct(s))
	return str
}

func (s UsageReport) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UsageReport) DecodeFromPtr(p capnp.Ptr) UsageReport {
	return UsageReport(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UsageReport) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UsageReport) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UsageReport) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UsageReport) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UsageReport) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UsageReport) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UsageReport) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UsageReport) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s UsageReport) ApiKey() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s UsageReport) HasApiKey() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UsageReport) ApiKeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s UsageReport) SetApiKey(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s UsageReport) Model() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s UsageReport) HasModel() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s UsageReport) ModelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s UsageReport) SetModel(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s UsageReport) InputTokens() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s UsageReport) SetInputTokens(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s UsageReport) OutputTokens() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s UsageReport) SetOutputTokens(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s UsageReport) ThinkingLevel() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s UsageReport) SetThinkingLevel(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s UsageReport) StatusCode() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s UsageReport) SetStatusCode(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s UsageReport) DurationMs() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s UsageReport) SetDurationMs(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s UsageReport) CacheReadTokens() uint32 {
	return capnp.Struct(s).Uint32(24)
}

func (s UsageReport) SetCacheReadTokens(v uint32) {
	capnp.Struct(s).SetUint32(24, v)
}

func (s UsageReport) CacheWriteTokens() uint32 {
	return capnp.Struct(s).Uint32(28)
}

func (s UsageReport) SetCacheWriteTokens(v uint32) {
	capnp.Struct(s).SetUint32(28, v)
}

// UsageReport_List is a list of UsageReport.
type UsageReport_List = capnp.StructList[UsageReport]

// NewUsageReport creates a new list of UsageReport.
func NewUsageReport_List(s *capnp.Segment, sz int32) (UsageReport_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 3}, sz)
	return capnp.StructList[UsageReport](l), err
}

// UsageReport_Future is a wrapper for a UsageReport promised by a client call.
type UsageReport_Future struct{ *capnp.Future }

func (f UsageReport_Future) Struct() (UsageReport, error) {
	p, err := f.Future.Ptr()
	return UsageReport(p.Struct()), err
}

type StreamChunkEvent capnp.Struct

// StreamChunkEvent_TypeID is the unique identifier for the type StreamChunkEvent.
const StreamChunkEvent_TypeID = 0x9eb2a626892c0f7c

func NewStreamChunkEvent(s *capnp.Segment) (StreamChunkEvent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return StreamChunkEvent(st), err
}

func NewRootStreamChunkEvent(s *capnp.Segment) (StreamChunkEvent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return StreamChunkEvent(st), err
}

func ReadRootStreamChunkEvent(msg *capnp.Message) (StreamChunkEvent, error) {
	root, err := msg.Root()
	return StreamChunkEvent(root.Struct()), err
}

func (s StreamChunkEvent) String() string {
	str, _ := text.Marshal(0x9eb2a626892c0f7c, capnp.Struct(s))
	return str
}

func (s StreamChunkEvent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StreamChunkEvent) DecodeFromPtr(p capnp.Ptr) StreamChunkEvent {
	return StreamChunkEvent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StreamChunkEvent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StreamChunkEvent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StreamChunkEvent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StreamChunkEvent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StreamChunkEvent) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StreamChunkEvent) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StreamChunkEvent) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StreamChunkEvent) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s StreamChunkEvent) ChunkIndex() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s StreamChunkEvent) SetChunkIndex(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s StreamChunkEvent) EventType() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s StreamChunkEvent) HasEventType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s StreamChunkEvent) EventTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s StreamChunkEvent) SetEventType(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s StreamChunkEvent) Data() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s StreamChunkEvent) HasData() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s StreamChunkEvent) DataBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s StreamChunkEvent) SetData(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// StreamChunkEvent_List is a list of StreamChunkEvent.
type StreamChunkEvent_List = capnp.StructList[StreamChunkEvent]

// NewStreamChunkEvent creates a new list of StreamChunkEvent.
func NewStreamChunkEvent_List(s *capnp.Segment, sz int32) (StreamChunkEvent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[StreamChunkEvent](l), err
}

// StreamChunkEvent_Future is a wrapper for a StreamChunkEvent promised by a client call.
type StreamChunkEvent_Future struct{ *capnp.Future }

func (f StreamChunkEvent_Future) Struct() (StreamChunkEvent, error) {
	p, err := f.Future.Ptr()
	return StreamChunkEvent(p.Struct()), err
}

type ThinkingLevelOverride uint16

// ThinkingLevelOverride_TypeID is the unique identifier for the type ThinkingLevelOverride.
const ThinkingLevelOverride_TypeID = 0x8e65dbd5998695ef

// Values of ThinkingLevelOverride.
const (
	ThinkingLevelOverride_noOverride ThinkingLevelOverride = 0
	ThinkingLevelOverride_disabled   ThinkingLevelOverride = 1
	ThinkingLevelOverride_low        ThinkingLevelOverride = 2
	ThinkingLevelOverride_medium     ThinkingLevelOverride = 3
	ThinkingLevelOverride_high       ThinkingLevelOverride = 4
	ThinkingLevelOverride_xhigh      ThinkingLevelOverride = 5
)

// String returns the enum's constant name.
func (c ThinkingLevelOverride) String() string {
	switch c {
	case ThinkingLevelOverride_noOverride:
		return "noOverride"
	case ThinkingLevelOverride_disabled:
		return "disabled"
	case ThinkingLevelOverride_low:
		return "low"
	case ThinkingLevelOverride_medium:
		return "medium"
	case ThinkingLevelOverride_high:
		return "high"
	case ThinkingLevelOverride_xhigh:
		return "xhigh"

	default:
		return ""
	}
}

// ThinkingLevelOverrideFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ThinkingLevelOverrideFromString(c string) ThinkingLevelOverride {
	switch c {
	case "noOverride":
		return ThinkingLevelOverride_noOverride
	case "disabled":
		return ThinkingLevelOverride_disabled
	case "low":
		return ThinkingLevelOverride_low
	case "medium":
		return ThinkingLevelOverride_medium
	case "high":
		return ThinkingLevelOverride_high
	case "xhigh":
		return ThinkingLevelOverride_xhigh

	default:
		return 0
	}
}

type ThinkingLevelOverride_List = capnp.EnumList[ThinkingLevelOverride]

func NewThinkingLevelOverride_List(s *capnp.Segment, sz int32) (ThinkingLevelOverride_List, error) {
	return capnp.NewEnumList[ThinkingLevelOverride](s, sz)
}

type RouteResult capnp.Struct
type RouteResult_routed RouteResult
type RouteResult_rejected RouteResult
type RouteResult_Which uint16

const (
	RouteResult_Which_routed   RouteResult_Which = 0
	RouteResult_Which_rejected RouteResult_Which = 1
)

func (w RouteResult_Which) String() string {
	const s = "routedrejected"
	switch w {
	case RouteResult_Which_routed:
		return s[0:6]
	case RouteResult_Which_rejected:
		return s[6:14]

	}
	return "RouteResult_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// RouteResult_TypeID is the unique identifier for the type RouteResult.
const RouteResult_TypeID = 0xcb6cee0eecbdac96

func NewRouteResult(s *capnp.Segment) (RouteResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return RouteResult(st), err
}

func NewRootRouteResult(s *capnp.Segment) (RouteResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return RouteResult(st), err
}

func ReadRootRouteResult(msg *capnp.Message) (RouteResult, error) {
	root, err := msg.Root()
	return RouteResult(root.Struct()), err
}

func (s RouteResult) String() string {
	str, _ := text.Marshal(0xcb6cee0eecbdac96, capnp.Struct(s))
	return str
}

func (s RouteResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RouteResult) DecodeFromPtr(p capnp.Ptr) RouteResult {
	return RouteResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RouteResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s RouteResult) Which() RouteResult_Which {
	return RouteResult_Which(capnp.Struct(s).Uint16(2))
}
func (s RouteResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RouteResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RouteResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RouteResult) Routed() RouteResult_routed { return RouteResult_routed(s) }

func (s RouteResult) SetRouted() {
	capnp.Struct(s).SetUint16(2, 0)
}

func (s RouteResult_routed) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RouteResult_routed) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RouteResult_routed) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RouteResult_routed) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RouteResult_routed) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RouteResult_routed) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RouteResult_routed) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RouteResult_routed) ModelOverride() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s RouteResult_routed) HasModelOverride() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RouteResult_routed) ModelOverrideBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s RouteResult_routed) SetModelOverride(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s RouteResult_routed) ThinkingLevelOverride() ThinkingLevelOverride {
	return ThinkingLevelOverride(capnp.Struct(s).Uint16(0))
}

func (s RouteResult_routed) SetThinkingLevelOverride(v ThinkingLevelOverride) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s RouteResult_routed) SkipBillingCheck() bool {
	return capnp.Struct(s).Bit(32)
}

func (s RouteResult_routed) SetSkipBillingCheck(v bool) {
	capnp.Struct(s).SetBit(32, v)
}

func (s RouteResult) Rejected() RouteResult_rejected { return RouteResult_rejected(s) }

func (s RouteResult) SetRejected() {
	capnp.Struct(s).SetUint16(2, 1)
}

func (s RouteResult_rejected) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RouteResult_rejected) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RouteResult_rejected) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RouteResult_rejected) StatusCode() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s RouteResult_rejected) SetStatusCode(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

func (s RouteResult_rejected) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RouteResult_rejected) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RouteResult_rejected) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RouteResult_rejected) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// RouteResult_List is a list of RouteResult.
type RouteResult_List = capnp.StructList[RouteResult]

// NewRouteResult creates a new list of RouteResult.
func NewRouteResult_List(s *capnp.Segment, sz int32) (RouteResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[RouteResult](l), err
}

// RouteResult_Future is a wrapper for a RouteResult promised by a client call.
type RouteResult_Future struct{ *capnp.Future }

func (f RouteResult_Future) Struct() (RouteResult, error) {
	p, err := f.Future.Ptr()
	return RouteResult(p.Struct()), err
}
func (p RouteResult_Future) Routed() RouteResult_routed_Future {
	return RouteResult_routed_Future{p.Future}
}

// RouteResult_routed_Future is a wrapper for a RouteResult_routed promised by a client call.
type RouteResult_routed_Future struct{ *capnp.Future }

func (f RouteResult_routed_Future) Struct() (RouteResult_routed, error) {
	p, err := f.Future.Ptr()
	return RouteResult_routed(p.Struct()), err
}
func (p RouteResult_Future) Rejected() RouteResult_rejected_Future {
	return RouteResult_rejected_Future{p.Future}
}

// RouteResult_rejected_Future is a wrapper for a RouteResult_rejected promised by a client call.
type RouteResult_rejected_Future struct{ *capnp.Future }

func (f RouteResult_rejected_Future) Struct() (RouteResult_rejected, error) {
	p, err := f.Future.Ptr()
	return RouteResult_rejected(p.Struct()), err
}

type AccountEventKind uint16

// AccountEventKind_TypeID is the unique identifier for the type AccountEventKind.
const AccountEventKind_TypeID = 0x9feb9afedcb9d848

// Values of AccountEventKind.
const (
	AccountEventKind_added         AccountEventKind = 0
	AccountEventKind_removed       AccountEventKind = 1
	AccountEventKind_refreshed     AccountEventKind = 2
	AccountEventKind_configUpdated AccountEventKind = 3
)

// String returns the enum's constant name.
func (c AccountEventKind) String() string {
	switch c {
	case AccountEventKind_added:
		return "added"
	case AccountEventKind_removed:
		return "removed"
	case AccountEventKind_refreshed:
		return "refreshed"
	case AccountEventKind_configUpdated:
		return "configUpdated"

	default:
		return ""
	}
}

// AccountEventKindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func AccountEventKindFromString(c string) AccountEventKind {
	switch c {
	case "added":
		return AccountEventKind_added
	case "removed":
		return AccountEventKind_removed
	case "refreshed":
		return AccountEventKind_refreshed
	case "configUpdated":
		return AccountEventKind_configUpdated

	default:
		return 0
	}
}

type AccountEventKind_List = capnp.EnumList[AccountEventKind]

func NewAccountEventKind_List(s *capnp.Segment, sz int32) (AccountEventKind_List, error) {
	return capnp.NewEnumList[AccountEventKind](s, sz)
}

type Router capnp.Client

// Router_TypeID is the unique identifier for the type Router.
const Router_TypeID = 0xc2787f08c0de0eb1

func (c Router) RouteRequest(ctx context.Context, params func(Router_routeRequest_Params) error) (Router_routeRequest_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      0,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "routeRequest",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 7}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Router_routeRequest_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Router_routeRequest_Results_Future{Future: ans.Future()}, release

}

func (c Router) ReportUsage(ctx context.Context, params func(Router_reportUsage_Params) error) (Router_reportUsage_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      1,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "reportUsage",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Router_reportUsage_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Router_reportUsage_Results_Future{Future: ans.Future()}, release

}

func (c Router) ReportChunk(ctx context.Context, params func(Router_reportChunk_Params) error) (Router_reportChunk_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      2,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "reportChunk",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Router_reportChunk_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Router_reportChunk_Results_Future{Future: ans.Future()}, release

}

func (c Router) OnAccountEvent(ctx context.Context, params func(Router_onAccountEvent_Params) error) (Router_onAccountEvent_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      3,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "onAccountEvent",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Router_onAccountEvent_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Router_onAccountEvent_Results_Future{Future: ans.Future()}, release

}

func (c Router) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Router) String() string {
	return "Router(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Router) AddRef() Router {
	return Router(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Router) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Router) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Router) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Router) DecodeFromPtr(p capnp.Ptr) Router {
	return Router(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Router) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Router) IsSame(other Router) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Router) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Router) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Router_Server is a Router with a local implementation.
type Router_Server interface {
	RouteRequest(context.Context, Router_routeRequest) error

	ReportUsage(context.Context, Router_reportUsage) error

	ReportChunk(context.Context, Router_reportChunk) error

	OnAccountEvent(context.Context, Router_onAccountEvent) error
}

// Router_NewServer creates a new Server from an implementation of Router_Server.
func Router_NewServer(s Router_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Router_Methods(nil, s), s, c)
}

// Router_ServerToClient creates a new Client from an implementation of Router_Server.
// The caller is responsible for calling Release on the returned Client.
func Router_ServerToClient(s Router_Server) Router {
	return Router(capnp.NewClient(Router_NewServer(s)))
}

// Router_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Router_Methods(methods []server.Method, s Router_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      0,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "routeRequest",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RouteRequest(ctx, Router_routeRequest{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      1,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "reportUsage",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ReportUsage(ctx, Router_reportUsage{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      2,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "reportChunk",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ReportChunk(ctx, Router_reportChunk{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2787f08c0de0eb1,
			MethodID:      3,
			InterfaceName: "callback.capnp:Router",
			MethodName:    "onAccountEvent",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.OnAccountEvent(ctx, Router_onAccountEvent{call})
		},
	})

	return methods
}

// Router_routeRequest holds the state for a server call to Router.routeRequest.
// See server.Call for documentation.
type Router_routeRequest struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Router_routeRequest) Args() Router_routeRequest_Params {
	return Router_routeRequest_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Router_routeRequest) AllocResults() (Router_routeRequest_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Router_routeRequest_Results(r), err
}

// Router_reportUsage holds the state for a server call to Router.reportUsage.
// See server.Call for documentation.
type Router_reportUsage struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Router_reportUsage) Args() Router_reportUsage_Params {
	return Router_reportUsage_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Router_reportUsage) AllocResults() (Router_reportUsage_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_reportUsage_Results(r), err
}

// Router_reportChunk holds the state for a server call to Router.reportChunk.
// See server.Call for documentation.
type Router_reportChunk struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Router_reportChunk) Args() Router_reportChunk_Params {
	return Router_reportChunk_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Router_reportChunk) AllocResults() (Router_reportChunk_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_reportChunk_Results(r), err
}

// Router_onAccountEvent holds the state for a server call to Router.onAccountEvent.
// See server.Call for documentation.
type Router_onAccountEvent struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Router_onAccountEvent) Args() Router_onAccountEvent_Params {
	return Router_onAccountEvent_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Router_onAccountEvent) AllocResults() (Router_onAccountEvent_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_onAccountEvent_Results(r), err
}

// Router_List is a list of Router.
type Router_List = capnp.CapList[Router]

// NewRouter_List creates a new list of Router.
func NewRouter_List(s *capnp.Segment, sz int32) (Router_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Router](l), err
}

type Router_routeRequest_Params capnp.Struct

// Router_routeRequest_Params_TypeID is the unique identifier for the type Router_routeRequest_Params.
const Router_routeRequest_Params_TypeID = 0xef6c55360ad6023c

func NewRouter_routeRequest_Params(s *capnp.Segment) (Router_routeRequest_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7})
	return Router_routeRequest_Params(st), err
}

func NewRootRouter_routeRequest_Params(s *capnp.Segment) (Router_routeRequest_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7})
	return Router_routeRequest_Params(st), err
}

func ReadRootRouter_routeRequest_Params(msg *capnp.Message) (Router_routeRequest_Params, error) {
	root, err := msg.Root()
	return Router_routeRequest_Params(root.Struct()), err
}

func (s Router_routeRequest_Params) String() string {
	str, _ := text.Marshal(0xef6c55360ad6023c, capnp.Struct(s))
	return str
}

func (s Router_routeRequest_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_routeRequest_Params) DecodeFromPtr(p capnp.Ptr) Router_routeRequest_Params {
	return Router_routeRequest_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_routeRequest_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_routeRequest_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_routeRequest_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_routeRequest_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Router_routeRequest_Params) RequestId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Router_routeRequest_Params) HasRequestId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Router_routeRequest_Params) RequestIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Router_routeRequest_Params) SetRequestId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Router_routeRequest_Params) ApiKey() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Router_routeRequest_Params) HasApiKey() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Router_routeRequest_Params) ApiKeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Router_routeRequest_Params) SetApiKey(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Router_routeRequest_Params) Model() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Router_routeRequest_Params) HasModel() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Router_routeRequest_Params) ModelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Router_routeRequest_Params) SetModel(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Router_routeRequest_Params) Endpoint() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Router_routeRequest_Params) HasEndpoint() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Router_routeRequest_Params) EndpointBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Router_routeRequest_Params) SetEndpoint(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Router_routeRequest_Params) UserAgent() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Router_routeRequest_Params) HasUserAgent() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Router_routeRequest_Params) UserAgentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Router_routeRequest_Params) SetUserAgent(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Router_routeRequest_Params) SessionId() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Router_routeRequest_Params) HasSessionId() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Router_routeRequest_Params) SessionIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Router_routeRequest_Params) SetSessionId(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Router_routeRequest_Params) ClientRequestId() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s Router_routeRequest_Params) HasClientRequestId() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Router_routeRequest_Params) ClientRequestIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s Router_routeRequest_Params) SetClientRequestId(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

// Router_routeRequest_Params_List is a list of Router_routeRequest_Params.
type Router_routeRequest_Params_List = capnp.StructList[Router_routeRequest_Params]

// NewRouter_routeRequest_Params creates a new list of Router_routeRequest_Params.
func NewRouter_routeRequest_Params_List(s *capnp.Segment, sz int32) (Router_routeRequest_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7}, sz)
	return capnp.StructList[Router_routeRequest_Params](l), err
}

// Router_routeRequest_Params_Future is a wrapper for a Router_routeRequest_Params promised by a client call.
type Router_routeRequest_Params_Future struct{ *capnp.Future }

func (f Router_routeRequest_Params_Future) Struct() (Router_routeRequest_Params, error) {
	p, err := f.Future.Ptr()
	return Router_routeRequest_Params(p.Struct()), err
}

type Router_routeRequest_Results capnp.Struct

// Router_routeRequest_Results_TypeID is the unique identifier for the type Router_routeRequest_Results.
const Router_routeRequest_Results_TypeID = 0xaab5935420e73dab

func NewRouter_routeRequest_Results(s *capnp.Segment) (Router_routeRequest_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Router_routeRequest_Results(st), err
}

func NewRootRouter_routeRequest_Results(s *capnp.Segment) (Router_routeRequest_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Router_routeRequest_Results(st), err
}

func ReadRootRouter_routeRequest_Results(msg *capnp.Message) (Router_routeRequest_Results, error) {
	root, err := msg.Root()
	return Router_routeRequest_Results(root.Struct()), err
}

func (s Router_routeRequest_Results) String() string {
	str, _ := text.Marshal(0xaab5935420e73dab, capnp.Struct(s))
	return str
}

func (s Router_routeRequest_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_routeRequest_Results) DecodeFromPtr(p capnp.Ptr) Router_routeRequest_Results {
	return Router_routeRequest_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_routeRequest_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_routeRequest_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_routeRequest_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_routeRequest_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Router_routeRequest_Results) Result() (RouteResult, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return RouteResult(p.Struct()), err
}

func (s Router_routeRequest_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Router_routeRequest_Results) SetResult(v RouteResult) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResult sets the result field to a newly
// allocated RouteResult struct, preferring placement in s's segment.
func (s Router_routeRequest_Results) NewResult() (RouteResult, error) {
	ss, err := NewRouteResult(capnp.Struct(s).Segment())
	if err != nil {
		return RouteResult{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Router_routeRequest_Results_List is a list of Router_routeRequest_Results.
type Router_routeRequest_Results_List = capnp.StructList[Router_routeRequest_Results]

// NewRouter_routeRequest_Results creates a new list of Router_routeRequest_Results.
func NewRouter_routeRequest_Results_List(s *capnp.Segment, sz int32) (Router_routeRequest_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Router_routeRequest_Results](l), err
}

// Router_routeRequest_Results_Future is a wrapper for a Router_routeRequest_Results promised by a client call.
type Router_routeRequest_Results_Future struct{ *capnp.Future }

func (f Router_routeRequest_Results_Future) Struct() (Router_routeRequest_Results, error) {
	p, err := f.Future.Ptr()
	return Router_routeRequest_Results(p.Struct()), err
}
func (p Router_routeRequest_Results_Future) Result() RouteResult_Future {
	return RouteResult_Future{Future: p.Future.Field(0, nil)}
}

type Router_reportUsage_Params capnp.Struct

// Router_reportUsage_Params_TypeID is the unique identifier for the type Router_reportUsage_Params.
const Router_reportUsage_Params_TypeID = 0xfdb3dad79bf47fdb

func NewRouter_reportUsage_Params(s *capnp.Segment) (Router_reportUsage_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Router_reportUsage_Params(st), err
}

func NewRootRouter_reportUsage_Params(s *capnp.Segment) (Router_reportUsage_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Router_reportUsage_Params(st), err
}

func ReadRootRouter_reportUsage_Params(msg *capnp.Message) (Router_reportUsage_Params, error) {
	root, err := msg.Root()
	return Router_reportUsage_Params(root.Struct()), err
}

func (s Router_reportUsage_Params) String() string {
	str, _ := text.Marshal(0xfdb3dad79bf47fdb, capnp.Struct(s))
	return str
}

func (s Router_reportUsage_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_reportUsage_Params) DecodeFromPtr(p capnp.Ptr) Router_reportUsage_Params {
	return Router_reportUsage_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_reportUsage_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_reportUsage_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_reportUsage_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_reportUsage_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Router_reportUsage_Params) RequestId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Router_reportUsage_Params) HasRequestId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Router_reportUsage_Params) RequestIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Router_reportUsage_Params) SetRequestId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Router_reportUsage_Params) Report() (UsageReport, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return UsageReport(p.Struct()), err
}

func (s Router_reportUsage_Params) HasReport() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Router_reportUsage_Params) SetReport(v UsageReport) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewReport sets the report field to a newly
// allocated UsageReport struct, preferring placement in s's segment.
func (s Router_reportUsage_Params) NewReport() (UsageReport, error) {
	ss, err := NewUsageReport(capnp.Struct(s).Segment())
	if err != nil {
		return UsageReport{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Router_reportUsage_Params_List is a list of Router_reportUsage_Params.
type Router_reportUsage_Params_List = capnp.StructList[Router_reportUsage_Params]

// NewRouter_reportUsage_Params creates a new list of Router_reportUsage_Params.
func NewRouter_reportUsage_Params_List(s *capnp.Segment, sz int32) (Router_reportUsage_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Router_reportUsage_Params](l), err
}

// Router_reportUsage_Params_Future is a wrapper for a Router_reportUsage_Params promised by a client call.
type Router_reportUsage_Params_Future struct{ *capnp.Future }

func (f Router_reportUsage_Params_Future) Struct() (Router_reportUsage_Params, error) {
	p, err := f.Future.Ptr()
	return Router_reportUsage_Params(p.Struct()), err
}
func (p Router_reportUsage_Params_Future) Report() UsageReport_Future {
	return UsageReport_Future{Future: p.Future.Field(1, nil)}
}

type Router_reportUsage_Results capnp.Struct

// Router_reportUsage_Results_TypeID is the unique identifier for the type Router_reportUsage_Results.
const Router_reportUsage_Results_TypeID = 0xfb041b399a15289a

func NewRouter_reportUsage_Results(s *capnp.Segment) (Router_reportUsage_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_reportUsage_Results(st), err
}

func NewRootRouter_reportUsage_Results(s *capnp.Segment) (Router_reportUsage_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_reportUsage_Results(st), err
}

func ReadRootRouter_reportUsage_Results(msg *capnp.Message) (Router_reportUsage_Results, error) {
	root, err := msg.Root()
	return Router_reportUsage_Results(root.Struct()), err
}

func (s Router_reportUsage_Results) String() string {
	str, _ := text.Marshal(0xfb041b399a15289a, capnp.Struct(s))
	return str
}

func (s Router_reportUsage_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_reportUsage_Results) DecodeFromPtr(p capnp.Ptr) Router_reportUsage_Results {
	return Router_reportUsage_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_reportUsage_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_reportUsage_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_reportUsage_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_reportUsage_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Router_reportUsage_Results_List is a list of Router_reportUsage_Results.
type Router_reportUsage_Results_List = capnp.StructList[Router_reportUsage_Results]

// NewRouter_reportUsage_Results creates a new list of Router_reportUsage_Results.
func NewRouter_reportUsage_Results_List(s *capnp.Segment, sz int32) (Router_reportUsage_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Router_reportUsage_Results](l), err
}

// Router_reportUsage_Results_Future is a wrapper for a Router_reportUsage_Results promised by a client call.
type Router_reportUsage_Results_Future struct{ *capnp.Future }

func (f Router_reportUsage_Results_Future) Struct() (Router_reportUsage_Results, error) {
	p, err := f.Future.Ptr()
	return Router_reportUsage_Results(p.Struct()), err
}

type Router_reportChunk_Params capnp.Struct

// Router_reportChunk_Params_TypeID is the unique identifier for the type Router_reportChunk_Params.
const Router_reportChunk_Params_TypeID = 0xcaf44958e96cf3b7

func NewRouter_reportChunk_Params(s *capnp.Segment) (Router_reportChunk_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Router_reportChunk_Params(st), err
}

func NewRootRouter_reportChunk_Params(s *capnp.Segment) (Router_reportChunk_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Router_reportChunk_Params(st), err
}

func ReadRootRouter_reportChunk_Params(msg *capnp.Message) (Router_reportChunk_Params, error) {
	root, err := msg.Root()
	return Router_reportChunk_Params(root.Struct()), err
}

func (s Router_reportChunk_Params) String() string {
	str, _ := text.Marshal(0xcaf44958e96cf3b7, capnp.Struct(s))
	return str
}

func (s Router_reportChunk_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_reportChunk_Params) DecodeFromPtr(p capnp.Ptr) Router_reportChunk_Params {
	return Router_reportChunk_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_reportChunk_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_reportChunk_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_reportChunk_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_reportChunk_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Router_reportChunk_Params) RequestId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Router_reportChunk_Params) HasRequestId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Router_reportChunk_Params) RequestIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Router_reportChunk_Params) SetRequestId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Router_reportChunk_Params) Chunk() (StreamChunkEvent, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return StreamChunkEvent(p.Struct()), err
}

func (s Router_reportChunk_Params) HasChunk() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Router_reportChunk_Params) SetChunk(v StreamChunkEvent) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewChunk sets the chunk field to a newly
// allocated StreamChunkEvent struct, preferring placement in s's segment.
func (s Router_reportChunk_Params) NewChunk() (StreamChunkEvent, error) {
	ss, err := NewStreamChunkEvent(capnp.Struct(s).Segment())
	if err != nil {
		return StreamChunkEvent{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Router_reportChunk_Params_List is a list of Router_reportChunk_Params.
type Router_reportChunk_Params_List = capnp.StructList[Router_reportChunk_Params]

// NewRouter_reportChunk_Params creates a new list of Router_reportChunk_Params.
func NewRouter_reportChunk_Params_List(s *capnp.Segment, sz int32) (Router_reportChunk_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Router_reportChunk_Params](l), err
}

// Router_reportChunk_Params_Future is a wrapper for a Router_reportChunk_Params promised by a client call.
type Router_reportChunk_Params_Future struct{ *capnp.Future }

func (f Router_reportChunk_Params_Future) Struct() (Router_reportChunk_Params, error) {
	p, err := f.Future.Ptr()
	return Router_reportChunk_Params(p.Struct()), err
}
func (p Router_reportChunk_Params_Future) Chunk() StreamChunkEvent_Future {
	return StreamChunkEvent_Future{Future: p.Future.Field(1, nil)}
}

type Router_reportChunk_Results capnp.Struct

// Router_reportChunk_Results_TypeID is the unique identifier for the type Router_reportChunk_Results.
const Router_reportChunk_Results_TypeID = 0xdc44ed4a624c7dfb

func NewRouter_reportChunk_Results(s *capnp.Segment) (Router_reportChunk_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_reportChunk_Results(st), err
}

func NewRootRouter_reportChunk_Results(s *capnp.Segment) (Router_reportChunk_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_reportChunk_Results(st), err
}

func ReadRootRouter_reportChunk_Results(msg *capnp.Message) (Router_reportChunk_Results, error) {
	root, err := msg.Root()
	return Router_reportChunk_Results(root.Struct()), err
}

func (s Router_reportChunk_Results) String() string {
	str, _ := text.Marshal(0xdc44ed4a624c7dfb, capnp.Struct(s))
	return str
}

func (s Router_reportChunk_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_reportChunk_Results) DecodeFromPtr(p capnp.Ptr) Router_reportChunk_Results {
	return Router_reportChunk_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_reportChunk_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_reportChunk_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_reportChunk_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_reportChunk_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Router_reportChunk_Results_List is a list of Router_reportChunk_Results.
type Router_reportChunk_Results_List = capnp.StructList[Router_reportChunk_Results]

// NewRouter_reportChunk_Results creates a new list of Router_reportChunk_Results.
func NewRouter_reportChunk_Results_List(s *capnp.Segment, sz int32) (Router_reportChunk_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Router_reportChunk_Results](l), err
}

// Router_reportChunk_Results_Future is a wrapper for a Router_reportChunk_Results promised by a client call.
type Router_reportChunk_Results_Future struct{ *capnp.Future }

func (f Router_reportChunk_Results_Future) Struct() (Router_reportChunk_Results, error) {
	p, err := f.Future.Ptr()
	return Router_reportChunk_Results(p.Struct()), err
}

type Router_onAccountEvent_Params capnp.Struct

// Router_onAccountEvent_Params_TypeID is the unique identifier for the type Router_onAccountEvent_Params.
const Router_onAccountEvent_Params_TypeID = 0x8993aa56e597383a

func NewRouter_onAccountEvent_Params(s *capnp.Segment) (Router_onAccountEvent_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Router_onAccountEvent_Params(st), err
}

func NewRootRouter_onAccountEvent_Params(s *capnp.Segment) (Router_onAccountEvent_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Router_onAccountEvent_Params(st), err
}

func ReadRootRouter_onAccountEvent_Params(msg *capnp.Message) (Router_onAccountEvent_Params, error) {
	root, err := msg.Root()
	return Router_onAccountEvent_Params(root.Struct()), err
}

func (s Router_onAccountEvent_Params) String() string {
	str, _ := text.Marshal(0x8993aa56e597383a, capnp.Struct(s))
	return str
}

func (s Router_onAccountEvent_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_onAccountEvent_Params) DecodeFromPtr(p capnp.Ptr) Router_onAccountEvent_Params {
	return Router_onAccountEvent_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_onAccountEvent_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_onAccountEvent_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_onAccountEvent_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_onAccountEvent_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Router_onAccountEvent_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Router_onAccountEvent_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Router_onAccountEvent_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Router_onAccountEvent_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Router_onAccountEvent_Params) Kind() AccountEventKind {
	return AccountEventKind(capnp.Struct(s).Uint16(0))
}

func (s Router_onAccountEvent_Params) SetKind(v AccountEventKind) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

// Router_onAccountEvent_Params_List is a list of Router_onAccountEvent_Params.
type Router_onAccountEvent_Params_List = capnp.StructList[Router_onAccountEvent_Params]

// NewRouter_onAccountEvent_Params creates a new list of Router_onAccountEvent_Params.
func NewRouter_onAccountEvent_Params_List(s *capnp.Segment, sz int32) (Router_onAccountEvent_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Router_onAccountEvent_Params](l), err
}

// Router_onAccountEvent_Params_Future is a wrapper for a Router_onAccountEvent_Params promised by a client call.
type Router_onAccountEvent_Params_Future struct{ *capnp.Future }

func (f Router_onAccountEvent_Params_Future) Struct() (Router_onAccountEvent_Params, error) {
	p, err := f.Future.Ptr()
	return Router_onAccountEvent_Params(p.Struct()), err
}

type Router_onAccountEvent_Results capnp.Struct

// Router_onAccountEvent_Results_TypeID is the unique identifier for the type Router_onAccountEvent_Results.
const Router_onAccountEvent_Results_TypeID = 0xcac3d8265e93b7f4

func NewRouter_onAccountEvent_Results(s *capnp.Segment) (Router_onAccountEvent_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_onAccountEvent_Results(st), err
}

func NewRootRouter_onAccountEvent_Results(s *capnp.Segment) (Router_onAccountEvent_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Router_onAccountEvent_Results(st), err
}

func ReadRootRouter_onAccountEvent_Results(msg *capnp.Message) (Router_onAccountEvent_Results, error) {
	root, err := msg.Root()
	return Router_onAccountEvent_Results(root.Struct()), err
}

func (s Router_onAccountEvent_Results) String() string {
	str, _ := text.Marshal(0xcac3d8265e93b7f4, capnp.Struct(s))
	return str
}

func (s Router_onAccountEvent_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Router_onAccountEvent_Results) DecodeFromPtr(p capnp.Ptr) Router_onAccountEvent_Results {
	return Router_onAccountEvent_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Router_onAccountEvent_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Router_onAccountEvent_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Router_onAccountEvent_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Router_onAccountEvent_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Router_onAccountEvent_Results_List is a list of Router_onAccountEvent_Results.
type Router_onAccountEvent_Results_List = capnp.StructList[Router_onAccountEvent_Results]

// NewRouter_onAccountEvent_Results creates a new list of Router_onAccountEvent_Results.
func NewRouter_onAccountEvent_Results_List(s *capnp.Segment, sz int32) (Router_onAccountEvent_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Router_onAccountEvent_Results](l), err
}

// Router_onAccountEvent_Results_Future is a wrapper for a Router_onAccountEvent_Results promised by a client call.
type Router_onAccountEvent_Results_Future struct{ *capnp.Future }

func (f Router_onAccountEvent_Results_Future) Struct() (Router_onAccountEvent_Results, error) {
	p, err := f.Future.Ptr()
	return Router_onAccountEvent_Results(p.Struct()), err
}

type PolicyService capnp.Client

// PolicyService_TypeID is the unique identifier for the type PolicyService.
const PolicyService_TypeID = 0x97f64db20802dd92

func (c PolicyService) Connect(ctx context.Context, params func(PolicyService_connect_Params) error) (PolicyService_connect_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x97f64db20802dd92,
			MethodID:      0,
			InterfaceName: "callback.capnp:PolicyService",
			MethodName:    "connect",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(PolicyService_connect_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return PolicyService_connect_Results_Future{Future: ans.Future()}, release

}

func (c PolicyService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c PolicyService) String() string {
	return "PolicyService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c PolicyService) AddRef() PolicyService {
	return PolicyService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c PolicyService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c PolicyService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c PolicyService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (PolicyService) DecodeFromPtr(p capnp.Ptr) PolicyService {
	return PolicyService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c PolicyService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c PolicyService) IsSame(other PolicyService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c PolicyService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c PolicyService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A PolicyService_Server is a PolicyService with a local implementation.
type PolicyService_Server interface {
	Connect(context.Context, PolicyService_connect) error
}

// PolicyService_NewServer creates a new Server from an implementation of PolicyService_Server.
func PolicyService_NewServer(s PolicyService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(PolicyService_Methods(nil, s), s, c)
}

// PolicyService_ServerToClient creates a new Client from an implementation of PolicyService_Server.
// The caller is responsible for calling Release on the returned Client.
func PolicyService_ServerToClient(s PolicyService_Server) PolicyService {
	return PolicyService(capnp.NewClient(PolicyService_NewServer(s)))
}

// PolicyService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func PolicyService_Methods(methods []server.Method, s PolicyService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x97f64db20802dd92,
			MethodID:      0,
			InterfaceName: "callback.capnp:PolicyService",
			MethodName:    "connect",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Connect(ctx, PolicyService_connect{call})
		},
	})

	return methods
}

// PolicyService_connect holds the state for a server call to PolicyService.connect.
// See server.Call for documentation.
type PolicyService_connect struct {
	*server.Call
}

// Args returns the call's arguments.
func (c PolicyService_connect) Args() PolicyService_connect_Params {
	return PolicyService_connect_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c PolicyService_connect) AllocResults() (PolicyService_connect_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return PolicyService_connect_Results(r), err
}

// PolicyService_List is a list of PolicyService.
type PolicyService_List = capnp.CapList[PolicyService]

// NewPolicyService_List creates a new list of PolicyService.
func NewPolicyService_List(s *capnp.Segment, sz int32) (PolicyService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[PolicyService](l), err
}

type PolicyService_connect_Params capnp.Struct

// PolicyService_connect_Params_TypeID is the unique identifier for the type PolicyService_connect_Params.
const PolicyService_connect_Params_TypeID = 0xf511d1824261c2a3

func NewPolicyService_connect_Params(s *capnp.Segment) (PolicyService_connect_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PolicyService_connect_Params(st), err
}

func NewRootPolicyService_connect_Params(s *capnp.Segment) (PolicyService_connect_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PolicyService_connect_Params(st), err
}

func ReadRootPolicyService_connect_Params(msg *capnp.Message) (PolicyService_connect_Params, error) {
	root, err := msg.Root()
	return PolicyService_connect_Params(root.Struct()), err
}

func (s PolicyService_connect_Params) String() string {
	str, _ := text.Marshal(0xf511d1824261c2a3, capnp.Struct(s))
	return str
}

func (s PolicyService_connect_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PolicyService_connect_Params) DecodeFromPtr(p capnp.Ptr) PolicyService_connect_Params {
	return PolicyService_connect_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PolicyService_connect_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PolicyService_connect_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PolicyService_connect_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PolicyService_connect_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PolicyService_connect_Params) Router() Router {
	p, _ := capnp.Struct(s).Ptr(0)
	return Router(p.Interface().Client())
}

func (s PolicyService_connect_Params) HasRouter() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PolicyService_connect_Params) SetRouter(v Router) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// PolicyService_connect_Params_List is a list of PolicyService_connect_Params.
type PolicyService_connect_Params_List = capnp.StructList[PolicyService_connect_Params]

// NewPolicyService_connect_Params creates a new list of PolicyService_connect_Params.
func NewPolicyService_connect_Params_List(s *capnp.Segment, sz int32) (PolicyService_connect_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[PolicyService_connect_Params](l), err
}

// PolicyService_connect_Params_Future is a wrapper for a PolicyService_connect_Params promised by a client call.
type PolicyService_connect_Params_Future struct{ *capnp.Future }

func (f PolicyService_connect_Params_Future) Struct() (PolicyService_connect_Params, error) {
	p, err := f.Future.Ptr()
	return PolicyService_connect_Params(p.Struct()), err
}
func (p PolicyService_connect_Params_Future) Router() Router {
	return Router(p.Future.Field(0, nil).Client())
}

type PolicyService_connect_Results capnp.Struct

// PolicyService_connect_Results_TypeID is the unique identifier for the type PolicyService_connect_Results.
const PolicyService_connect_Results_TypeID = 0xe3fb4d1d7a312c49

func NewPolicyService_connect_Results(s *capnp.Segment) (PolicyService_connect_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return PolicyService_connect_Results(st), err
}

func NewRootPolicyService_connect_Results(s *capnp.Segment) (PolicyService_connect_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return PolicyService_connect_Results(st), err
}

func ReadRootPolicyService_connect_Results(msg *capnp.Message) (PolicyService_connect_Results, error) {
	root, err := msg.Root()
	return PolicyService_connect_Results(root.Struct()), err
}

func (s PolicyService_connect_Results) String() string {
	str, _ := text.Marshal(0xe3fb4d1d7a312c49, capnp.Struct(s))
	return str
}

func (s PolicyService_connect_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PolicyService_connect_Results) DecodeFromPtr(p capnp.Ptr) PolicyService_connect_Results {
	return PolicyService_connect_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PolicyService_connect_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PolicyService_connect_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PolicyService_connect_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PolicyService_connect_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// PolicyService_connect_Results_List is a list of PolicyService_connect_Results.
type PolicyService_connect_Results_List = capnp.StructList[PolicyService_connect_Results]

// NewPolicyService_connect_Results creates a new list of PolicyService_connect_Results.
func NewPolicyService_connect_Results_List(s *capnp.Segment, sz int32) (PolicyService_connect_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[PolicyService_connect_Results](l), err
}

// PolicyService_connect_Results_Future is a wrapper for a PolicyService_connect_Results promised by a client call.
type PolicyService_connect_Results_Future struct{ *capnp.Future }

func (f PolicyService_connect_Results_Future) Struct() (PolicyService_connect_Results, error) {
	p, err := f.Future.Ptr()
	return PolicyService_connect_Results(p.Struct()), err
}
