// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type Bootstrap capnp.Client

// Bootstrap_TypeID is the unique identifier for the type Bootstrap.
const Bootstrap_TypeID = 0xefa07576d8b04be5

func (c Bootstrap) Auth(ctx context.Context, params func(Bootstrap_auth_Params) error) (Bootstrap_auth_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xefa07576d8b04be5,
			MethodID:      0,
			InterfaceName: "clandes.capnp:Bootstrap",
			MethodName:    "auth",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Bootstrap_auth_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Bootstrap_auth_Results_Future{Future: ans.Future()}, release

}

func (c Bootstrap) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Bootstrap) String() string {
	return "Bootstrap(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Bootstrap) AddRef() Bootstrap {
	return Bootstrap(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Bootstrap) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Bootstrap) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Bootstrap) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Bootstrap) DecodeFromPtr(p capnp.Ptr) Bootstrap {
	return Bootstrap(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Bootstrap) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Bootstrap) IsSame(other Bootstrap) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Bootstrap) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Bootstrap) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Bootstrap_Server is a Bootstrap with a local implementation.
type Bootstrap_Server interface {
	Auth(context.Context, Bootstrap_auth) error
}

// Bootstrap_NewServer creates a new Server from an implementation of Bootstrap_Server.
func Bootstrap_NewServer(s Bootstrap_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Bootstrap_Methods(nil, s), s, c)
}

// Bootstrap_ServerToClient creates a new Client from an implementation of Bootstrap_Server.
// The caller is responsible for calling Release on the returned Client.
func Bootstrap_ServerToClient(s Bootstrap_Server) Bootstrap {
	return Bootstrap(capnp.NewClient(Bootstrap_NewServer(s)))
}

// Bootstrap_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Bootstrap_Methods(methods []server.Method, s Bootstrap_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xefa07576d8b04be5,
			MethodID:      0,
			InterfaceName: "clandes.capnp:Bootstrap",
			MethodName:    "auth",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Auth(ctx, Bootstrap_auth{call})
		},
	})

	return methods
}

// Bootstrap_auth holds the state for a server call to Bootstrap.auth.
// See server.Call for documentation.
type Bootstrap_auth struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Bootstrap_auth) Args() Bootstrap_auth_Params {
	return Bootstrap_auth_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Bootstrap_auth) AllocResults() (Bootstrap_auth_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Bootstrap_auth_Results(r), err
}

// Bootstrap_List is a list of Bootstrap.
type Bootstrap_List = capnp.CapList[Bootstrap]

// NewBootstrap_List creates a new list of Bootstrap.
func NewBootstrap_List(s *capnp.Segment, sz int32) (Bootstrap_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Bootstrap](l), err
}

type Bootstrap_auth_Params capnp.Struct

// Bootstrap_auth_Params_TypeID is the unique identifier for the type Bootstrap_auth_Params.
const Bootstrap_auth_Params_TypeID = 0xa06014969215eea9

func NewBootstrap_auth_Params(s *capnp.Segment) (Bootstrap_auth_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Bootstrap_auth_Params(st), err
}

func NewRootBootstrap_auth_Params(s *capnp.Segment) (Bootstrap_auth_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Bootstrap_auth_Params(st), err
}

func ReadRootBootstrap_auth_Params(msg *capnp.Message) (Bootstrap_auth_Params, error) {
	root, err := msg.Root()
	return Bootstrap_auth_Params(root.Struct()), err
}

func (s Bootstrap_auth_Params) String() string {
	str, _ := text.Marshal(0xa06014969215eea9, capnp.Struct(s))
	return str
}

func (s Bootstrap_auth_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Bootstrap_auth_Params) DecodeFromPtr(p capnp.Ptr) Bootstrap_auth_Params {
	return Bootstrap_auth_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Bootstrap_auth_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Bootstrap_auth_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Bootstrap_auth_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Bootstrap_auth_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Bootstrap_auth_Params) Token() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Bootstrap_auth_Params) HasToken() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Bootstrap_auth_Params) TokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Bootstrap_auth_Params) SetToken(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Bootstrap_auth_Params_List is a list of Bootstrap_auth_Params.
type Bootstrap_auth_Params_List = capnp.StructList[Bootstrap_auth_Params]

// NewBootstrap_auth_Params creates a new list of Bootstrap_auth_Params.
func NewBootstrap_auth_Params_List(s *capnp.Segment, sz int32) (Bootstrap_auth_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Bootstrap_auth_Params](l), err
}

// Bootstrap_auth_Params_Future is a wrapper for a Bootstrap_auth_Params promised by a client call.
type Bootstrap_auth_Params_Future struct{ *capnp.Future }

func (f Bootstrap_auth_Params_Future) Struct() (Bootstrap_auth_Params, error) {
	p, err := f.Future.Ptr()
	return Bootstrap_auth_Params(p.Struct()), err
}

type Bootstrap_auth_Results capnp.Struct

// Bootstrap_auth_Results_TypeID is the unique identifier for the type Bootstrap_auth_Results.
const Bootstrap_auth_Results_TypeID = 0xc20696166fc14280

func NewBootstrap_auth_Results(s *capnp.Segment) (Bootstrap_auth_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Bootstrap_auth_Results(st), err
}

func NewRootBootstrap_auth_Results(s *capnp.Segment) (Bootstrap_auth_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Bootstrap_auth_Results(st), err
}

func ReadRootBootstrap_auth_Results(msg *capnp.Message) (Bootstrap_auth_Results, error) {
	root, err := msg.Root()
	return Bootstrap_auth_Results(root.Struct()), err
}

func (s Bootstrap_auth_Results) String() string {
	str, _ := text.Marshal(0xc20696166fc14280, capnp.Struct(s))
	return str
}

func (s Bootstrap_auth_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Bootstrap_auth_Results) DecodeFromPtr(p capnp.Ptr) Bootstrap_auth_Results {
	return Bootstrap_auth_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Bootstrap_auth_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Bootstrap_auth_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Bootstrap_auth_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Bootstrap_auth_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Bootstrap_auth_Results) Service() ClandesService {
	p, _ := capnp.Struct(s).Ptr(0)
	return ClandesService(p.Interface().Client())
}

func (s Bootstrap_auth_Results) HasService() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Bootstrap_auth_Results) SetService(v ClandesService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// Bootstrap_auth_Results_List is a list of Bootstrap_auth_Results.
type Bootstrap_auth_Results_List = capnp.StructList[Bootstrap_auth_Results]

// NewBootstrap_auth_Results creates a new list of Bootstrap_auth_Results.
func NewBootstrap_auth_Results_List(s *capnp.Segment, sz int32) (Bootstrap_auth_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Bootstrap_auth_Results](l), err
}

// Bootstrap_auth_Results_Future is a wrapper for a Bootstrap_auth_Results promised by a client call.
type Bootstrap_auth_Results_Future struct{ *capnp.Future }

func (f Bootstrap_auth_Results_Future) Struct() (Bootstrap_auth_Results, error) {
	p, err := f.Future.Ptr()
	return Bootstrap_auth_Results(p.Struct()), err
}
func (p Bootstrap_auth_Results_Future) Service() ClandesService {
	return ClandesService(p.Future.Field(0, nil).Client())
}

type ClandesService capnp.Client

// ClandesService_TypeID is the unique identifier for the type ClandesService.
const ClandesService_TypeID = 0xc2b6e8aae63a6302

func (c ClandesService) AccountService(ctx context.Context, params func(ClandesService_accountService_Params) error) (ClandesService_accountService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      0,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "accountService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_accountService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_accountService_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) ClaudeAuthService(ctx context.Context, params func(ClandesService_claudeAuthService_Params) error) (ClandesService_claudeAuthService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      1,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "claudeAuthService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_claudeAuthService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_claudeAuthService_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) ClaudeQueryService(ctx context.Context, params func(ClandesService_claudeQueryService_Params) error) (ClandesService_claudeQueryService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      2,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "claudeQueryService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_claudeQueryService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_claudeQueryService_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) ProxyService(ctx context.Context, params func(ClandesService_proxyService_Params) error) (ClandesService_proxyService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      3,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "proxyService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_proxyService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_proxyService_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) PolicyService(ctx context.Context, params func(ClandesService_policyService_Params) error) (ClandesService_policyService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      4,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "policyService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_policyService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_policyService_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) GetVersion(ctx context.Context, params func(ClandesService_getVersion_Params) error) (ClandesService_getVersion_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      5,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "getVersion",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_getVersion_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_getVersion_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) CodexAuthService(ctx context.Context, params func(ClandesService_codexAuthService_Params) error) (ClandesService_codexAuthService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      6,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "codexAuthService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_codexAuthService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_codexAuthService_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) CodexQueryService(ctx context.Context, params func(ClandesService_codexQueryService_Params) error) (ClandesService_codexQueryService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      7,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "codexQueryService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClandesService_codexQueryService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClandesService_codexQueryService_Results_Future{Future: ans.Future()}, release

}

func (c ClandesService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c ClandesService) String() string {
	return "ClandesService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c ClandesService) AddRef() ClandesService {
	return ClandesService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c ClandesService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c ClandesService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c ClandesService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (ClandesService) DecodeFromPtr(p capnp.Ptr) ClandesService {
	return ClandesService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c ClandesService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c ClandesService) IsSame(other ClandesService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c ClandesService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c ClandesService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A ClandesService_Server is a ClandesService with a local implementation.
type ClandesService_Server interface {
	AccountService(context.Context, ClandesService_accountService) error

	ClaudeAuthService(context.Context, ClandesService_claudeAuthService) error

	ClaudeQueryService(context.Context, ClandesService_claudeQueryService) error

	ProxyService(context.Context, ClandesService_proxyService) error

	PolicyService(context.Context, ClandesService_policyService) error

	GetVersion(context.Context, ClandesService_getVersion) error

	CodexAuthService(context.Context, ClandesService_codexAuthService) error

	CodexQueryService(context.Context, ClandesService_codexQueryService) error
}

// ClandesService_NewServer creates a new Server from an implementation of ClandesService_Server.
func ClandesService_NewServer(s ClandesService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ClandesService_Methods(nil, s), s, c)
}

// ClandesService_ServerToClient creates a new Client from an implementation of ClandesService_Server.
// The caller is responsible for calling Release on the returned Client.
func ClandesService_ServerToClient(s ClandesService_Server) ClandesService {
	return ClandesService(capnp.NewClient(ClandesService_NewServer(s)))
}

// ClandesService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ClandesService_Methods(methods []server.Method, s ClandesService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 8)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      0,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "accountService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.AccountService(ctx, ClandesService_accountService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      1,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "claudeAuthService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ClaudeAuthService(ctx, ClandesService_claudeAuthService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      2,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "claudeQueryService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ClaudeQueryService(ctx, ClandesService_claudeQueryService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      3,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "proxyService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ProxyService(ctx, ClandesService_proxyService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      4,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "policyService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.PolicyService(ctx, ClandesService_policyService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      5,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "getVersion",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetVersion(ctx, ClandesService_getVersion{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      6,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "codexAuthService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CodexAuthService(ctx, ClandesService_codexAuthService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc2b6e8aae63a6302,
			MethodID:      7,
			InterfaceName: "clandes.capnp:ClandesService",
			MethodName:    "codexQueryService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CodexQueryService(ctx, ClandesService_codexQueryService{call})
		},
	})

	return methods
}

// ClandesService_accountService holds the state for a server call to ClandesService.accountService.
// See server.Call for documentation.
type ClandesService_accountService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_accountService) Args() ClandesService_accountService_Params {
	return ClandesService_accountService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_accountService) AllocResults() (ClandesService_accountService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_accountService_Results(r), err
}

// ClandesService_claudeAuthService holds the state for a server call to ClandesService.claudeAuthService.
// See server.Call for documentation.
type ClandesService_claudeAuthService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_claudeAuthService) Args() ClandesService_claudeAuthService_Params {
	return ClandesService_claudeAuthService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_claudeAuthService) AllocResults() (ClandesService_claudeAuthService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_claudeAuthService_Results(r), err
}

// ClandesService_claudeQueryService holds the state for a server call to ClandesService.claudeQueryService.
// See server.Call for documentation.
type ClandesService_claudeQueryService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_claudeQueryService) Args() ClandesService_claudeQueryService_Params {
	return ClandesService_claudeQueryService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_claudeQueryService) AllocResults() (ClandesService_claudeQueryService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_claudeQueryService_Results(r), err
}

// ClandesService_proxyService holds the state for a server call to ClandesService.proxyService.
// See server.Call for documentation.
type ClandesService_proxyService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_proxyService) Args() ClandesService_proxyService_Params {
	return ClandesService_proxyService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_proxyService) AllocResults() (ClandesService_proxyService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_proxyService_Results(r), err
}

// ClandesService_policyService holds the state for a server call to ClandesService.policyService.
// See server.Call for documentation.
type ClandesService_policyService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_policyService) Args() ClandesService_policyService_Params {
	return ClandesService_policyService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_policyService) AllocResults() (ClandesService_policyService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_policyService_Results(r), err
}

// ClandesService_getVersion holds the state for a server call to ClandesService.getVersion.
// See server.Call for documentation.
type ClandesService_getVersion struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_getVersion) Args() ClandesService_getVersion_Params {
	return ClandesService_getVersion_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_getVersion) AllocResults() (ClandesService_getVersion_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_getVersion_Results(r), err
}

// ClandesService_codexAuthService holds the state for a server call to ClandesService.codexAuthService.
// See server.Call for documentation.
type ClandesService_codexAuthService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_codexAuthService) Args() ClandesService_codexAuthService_Params {
	return ClandesService_codexAuthService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_codexAuthService) AllocResults() (ClandesService_codexAuthService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_codexAuthService_Results(r), err
}

// ClandesService_codexQueryService holds the state for a server call to ClandesService.codexQueryService.
// See server.Call for documentation.
type ClandesService_codexQueryService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClandesService_codexQueryService) Args() ClandesService_codexQueryService_Params {
	return ClandesService_codexQueryService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClandesService_codexQueryService) AllocResults() (ClandesService_codexQueryService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_codexQueryService_Results(r), err
}

// ClandesService_List is a list of ClandesService.
type ClandesService_List = capnp.CapList[ClandesService]

// NewClandesService_List creates a new list of ClandesService.
func NewClandesService_List(s *capnp.Segment, sz int32) (ClandesService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[ClandesService](l), err
}

type ClandesService_accountService_Params capnp.Struct

// ClandesService_accountService_Params_TypeID is the unique identifier for the type ClandesService_accountService_Params.
const ClandesService_accountService_Params_TypeID = 0x94e9ec8b264832ae

func NewClandesService_accountService_Params(s *capnp.Segment) (ClandesService_accountService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_accountService_Params(st), err
}

func NewRootClandesService_accountService_Params(s *capnp.Segment) (ClandesService_accountService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_accountService_Params(st), err
}

func ReadRootClandesService_accountService_Params(msg *capnp.Message) (ClandesService_accountService_Params, error) {
	root, err := msg.Root()
	return ClandesService_accountService_Params(root.Struct()), err
}

func (s ClandesService_accountService_Params) String() string {
	str, _ := text.Marshal(0x94e9ec8b264832ae, capnp.Struct(s))
	return str
}

func (s ClandesService_accountService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_accountService_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_accountService_Params {
	return ClandesService_accountService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_accountService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_accountService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_accountService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_accountService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_accountService_Params_List is a list of ClandesService_accountService_Params.
type ClandesService_accountService_Params_List = capnp.StructList[ClandesService_accountService_Params]

// NewClandesService_accountService_Params creates a new list of ClandesService_accountService_Params.
func NewClandesService_accountService_Params_List(s *capnp.Segment, sz int32) (ClandesService_accountService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_accountService_Params](l), err
}

// ClandesService_accountService_Params_Future is a wrapper for a ClandesService_accountService_Params promised by a client call.
type ClandesService_accountService_Params_Future struct{ *capnp.Future }

func (f ClandesService_accountService_Params_Future) Struct() (ClandesService_accountService_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_accountService_Params(p.Struct()), err
}

type ClandesService_accountService_Results capnp.Struct

// ClandesService_accountService_Results_TypeID is the unique identifier for the type ClandesService_accountService_Results.
const ClandesService_accountService_Results_TypeID = 0x88afc5ebaaa0711b

func NewClandesService_accountService_Results(s *capnp.Segment) (ClandesService_accountService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_accountService_Results(st), err
}

func NewRootClandesService_accountService_Results(s *capnp.Segment) (ClandesService_accountService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_accountService_Results(st), err
}

func ReadRootClandesService_accountService_Results(msg *capnp.Message) (ClandesService_accountService_Results, error) {
	root, err := msg.Root()
	return ClandesService_accountService_Results(root.Struct()), err
}

func (s ClandesService_accountService_Results) String() string {
	str, _ := text.Marshal(0x88afc5ebaaa0711b, capnp.Struct(s))
	return str
}

func (s ClandesService_accountService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_accountService_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_accountService_Results {
	return ClandesService_accountService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_accountService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_accountService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_accountService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_accountService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_accountService_Results) Svc() AccountService {
	p, _ := capnp.Struct(s).Ptr(0)
	return AccountService(p.Interface().Client())
}

func (s ClandesService_accountService_Results) HasSvc() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_accountService_Results) SetSvc(v AccountService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ClandesService_accountService_Results_List is a list of ClandesService_accountService_Results.
type ClandesService_accountService_Results_List = capnp.StructList[ClandesService_accountService_Results]

// NewClandesService_accountService_Results creates a new list of ClandesService_accountService_Results.
func NewClandesService_accountService_Results_List(s *capnp.Segment, sz int32) (ClandesService_accountService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_accountService_Results](l), err
}

// ClandesService_accountService_Results_Future is a wrapper for a ClandesService_accountService_Results promised by a client call.
type ClandesService_accountService_Results_Future struct{ *capnp.Future }

func (f ClandesService_accountService_Results_Future) Struct() (ClandesService_accountService_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_accountService_Results(p.Struct()), err
}
func (p ClandesService_accountService_Results_Future) Svc() AccountService {
	return AccountService(p.Future.Field(0, nil).Client())
}

type ClandesService_claudeAuthService_Params capnp.Struct

// ClandesService_claudeAuthService_Params_TypeID is the unique identifier for the type ClandesService_claudeAuthService_Params.
const ClandesService_claudeAuthService_Params_TypeID = 0xd750bf88489926d8

func NewClandesService_claudeAuthService_Params(s *capnp.Segment) (ClandesService_claudeAuthService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_claudeAuthService_Params(st), err
}

func NewRootClandesService_claudeAuthService_Params(s *capnp.Segment) (ClandesService_claudeAuthService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_claudeAuthService_Params(st), err
}

func ReadRootClandesService_claudeAuthService_Params(msg *capnp.Message) (ClandesService_claudeAuthService_Params, error) {
	root, err := msg.Root()
	return ClandesService_claudeAuthService_Params(root.Struct()), err
}

func (s ClandesService_claudeAuthService_Params) String() string {
	str, _ := text.Marshal(0xd750bf88489926d8, capnp.Struct(s))
	return str
}

func (s ClandesService_claudeAuthService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_claudeAuthService_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_claudeAuthService_Params {
	return ClandesService_claudeAuthService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_claudeAuthService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_claudeAuthService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_claudeAuthService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_claudeAuthService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_claudeAuthService_Params_List is a list of ClandesService_claudeAuthService_Params.
type ClandesService_claudeAuthService_Params_List = capnp.StructList[ClandesService_claudeAuthService_Params]

// NewClandesService_claudeAuthService_Params creates a new list of ClandesService_claudeAuthService_Params.
func NewClandesService_claudeAuthService_Params_List(s *capnp.Segment, sz int32) (ClandesService_claudeAuthService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_claudeAuthService_Params](l), err
}

// ClandesService_claudeAuthService_Params_Future is a wrapper for a ClandesService_claudeAuthService_Params promised by a client call.
type ClandesService_claudeAuthService_Params_Future struct{ *capnp.Future }

func (f ClandesService_claudeAuthService_Params_Future) Struct() (ClandesService_claudeAuthService_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_claudeAuthService_Params(p.Struct()), err
}

type ClandesService_claudeAuthService_Results capnp.Struct

// ClandesService_claudeAuthService_Results_TypeID is the unique identifier for the type ClandesService_claudeAuthService_Results.
const ClandesService_claudeAuthService_Results_TypeID = 0x8b64d73a39434e2f

func NewClandesService_claudeAuthService_Results(s *capnp.Segment) (ClandesService_claudeAuthService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_claudeAuthService_Results(st), err
}

func NewRootClandesService_claudeAuthService_Results(s *capnp.Segment) (ClandesService_claudeAuthService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_claudeAuthService_Results(st), err
}

func ReadRootClandesService_claudeAuthService_Results(msg *capnp.Message) (ClandesService_claudeAuthService_Results, error) {
	root, err := msg.Root()
	return ClandesService_claudeAuthService_Results(root.Struct()), err
}

func (s ClandesService_claudeAuthService_Results) String() string {
	str, _ := text.Marshal(0x8b64d73a39434e2f, capnp.Struct(s))
	return str
}

func (s ClandesService_claudeAuthService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_claudeAuthService_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_claudeAuthService_Results {
	return ClandesService_claudeAuthService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_claudeAuthService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_claudeAuthService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_claudeAuthService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_claudeAuthService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_claudeAuthService_Results) Svc() ClaudeAuthService {
	p, _ := capnp.Struct(s).Ptr(0)
	return ClaudeAuthService(p.Interface().Client())
}

func (s ClandesService_claudeAuthService_Results) HasSvc() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_claudeAuthService_Results) SetSvc(v ClaudeAuthService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ClandesService_claudeAuthService_Results_List is a list of ClandesService_claudeAuthService_Results.
type ClandesService_claudeAuthService_Results_List = capnp.StructList[ClandesService_claudeAuthService_Results]

// NewClandesService_claudeAuthService_Results creates a new list of ClandesService_claudeAuthService_Results.
func NewClandesService_claudeAuthService_Results_List(s *capnp.Segment, sz int32) (ClandesService_claudeAuthService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_claudeAuthService_Results](l), err
}

// ClandesService_claudeAuthService_Results_Future is a wrapper for a ClandesService_claudeAuthService_Results promised by a client call.
type ClandesService_claudeAuthService_Results_Future struct{ *capnp.Future }

func (f ClandesService_claudeAuthService_Results_Future) Struct() (ClandesService_claudeAuthService_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_claudeAuthService_Results(p.Struct()), err
}
func (p ClandesService_claudeAuthService_Results_Future) Svc() ClaudeAuthService {
	return ClaudeAuthService(p.Future.Field(0, nil).Client())
}

type ClandesService_claudeQueryService_Params capnp.Struct

// ClandesService_claudeQueryService_Params_TypeID is the unique identifier for the type ClandesService_claudeQueryService_Params.
const ClandesService_claudeQueryService_Params_TypeID = 0xb27e81ce62f8604e

func NewClandesService_claudeQueryService_Params(s *capnp.Segment) (ClandesService_claudeQueryService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_claudeQueryService_Params(st), err
}

func NewRootClandesService_claudeQueryService_Params(s *capnp.Segment) (ClandesService_claudeQueryService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_claudeQueryService_Params(st), err
}

func ReadRootClandesService_claudeQueryService_Params(msg *capnp.Message) (ClandesService_claudeQueryService_Params, error) {
	root, err := msg.Root()
	return ClandesService_claudeQueryService_Params(root.Struct()), err
}

func (s ClandesService_claudeQueryService_Params) String() string {
	str, _ := text.Marshal(0xb27e81ce62f8604e, capnp.Struct(s))
	return str
}

func (s ClandesService_claudeQueryService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_claudeQueryService_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_claudeQueryService_Params {
	return ClandesService_claudeQueryService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_claudeQueryService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_claudeQueryService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_claudeQueryService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_claudeQueryService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_claudeQueryService_Params_List is a list of ClandesService_claudeQueryService_Params.
type ClandesService_claudeQueryService_Params_List = capnp.StructList[ClandesService_claudeQueryService_Params]

// NewClandesService_claudeQueryService_Params creates a new list of ClandesService_claudeQueryService_Params.
func NewClandesService_claudeQueryService_Params_List(s *capnp.Segment, sz int32) (ClandesService_claudeQueryService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_claudeQueryService_Params](l), err
}

// ClandesService_claudeQueryService_Params_Future is a wrapper for a ClandesService_claudeQueryService_Params promised by a client call.
type ClandesService_claudeQueryService_Params_Future struct{ *capnp.Future }

func (f ClandesService_claudeQueryService_Params_Future) Struct() (ClandesService_claudeQueryService_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_claudeQueryService_Params(p.Struct()), err
}

type ClandesService_claudeQueryService_Results capnp.Struct

// ClandesService_claudeQueryService_Results_TypeID is the unique identifier for the type ClandesService_claudeQueryService_Results.
const ClandesService_claudeQueryService_Results_TypeID = 0xa178f9d9ca11fd5e

func NewClandesService_claudeQueryService_Results(s *capnp.Segment) (ClandesService_claudeQueryService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_claudeQueryService_Results(st), err
}

func NewRootClandesService_claudeQueryService_Results(s *capnp.Segment) (ClandesService_claudeQueryService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_claudeQueryService_Results(st), err
}

func ReadRootClandesService_claudeQueryService_Results(msg *capnp.Message) (ClandesService_claudeQueryService_Results, error) {
	root, err := msg.Root()
	return ClandesService_claudeQueryService_Results(root.Struct()), err
}

func (s ClandesService_claudeQueryService_Results) String() string {
	str, _ := text.Marshal(0xa178f9d9ca11fd5e, capnp.Struct(s))
	return str
}

func (s ClandesService_claudeQueryService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_claudeQueryService_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_claudeQueryService_Results {
	return ClandesService_claudeQueryService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_claudeQueryService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_claudeQueryService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_claudeQueryService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_claudeQueryService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_claudeQueryService_Results) Svc() ClaudeQueryService {
	p, _ := capnp.Struct(s).Ptr(0)
	return ClaudeQueryService(p.Interface().Client())
}

func (s ClandesService_claudeQueryService_Results) HasSvc() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_claudeQueryService_Results) SetSvc(v ClaudeQueryService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ClandesService_claudeQueryService_Results_List is a list of ClandesService_claudeQueryService_Results.
type ClandesService_claudeQueryService_Results_List = capnp.StructList[ClandesService_claudeQueryService_Results]

// NewClandesService_claudeQueryService_Results creates a new list of ClandesService_claudeQueryService_Results.
func NewClandesService_claudeQueryService_Results_List(s *capnp.Segment, sz int32) (ClandesService_claudeQueryService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_claudeQueryService_Results](l), err
}

// ClandesService_claudeQueryService_Results_Future is a wrapper for a ClandesService_claudeQueryService_Results promised by a client call.
type ClandesService_claudeQueryService_Results_Future struct{ *capnp.Future }

func (f ClandesService_claudeQueryService_Results_Future) Struct() (ClandesService_claudeQueryService_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_claudeQueryService_Results(p.Struct()), err
}
func (p ClandesService_claudeQueryService_Results_Future) Svc() ClaudeQueryService {
	return ClaudeQueryService(p.Future.Field(0, nil).Client())
}

type ClandesService_proxyService_Params capnp.Struct

// ClandesService_proxyService_Params_TypeID is the unique identifier for the type ClandesService_proxyService_Params.
const ClandesService_proxyService_Params_TypeID = 0xb02636f995ef5f5f

func NewClandesService_proxyService_Params(s *capnp.Segment) (ClandesService_proxyService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_proxyService_Params(st), err
}

func NewRootClandesService_proxyService_Params(s *capnp.Segment) (ClandesService_proxyService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_proxyService_Params(st), err
}

func ReadRootClandesService_proxyService_Params(msg *capnp.Message) (ClandesService_proxyService_Params, error) {
	root, err := msg.Root()
	return ClandesService_proxyService_Params(root.Struct()), err
}

func (s ClandesService_proxyService_Params) String() string {
	str, _ := text.Marshal(0xb02636f995ef5f5f, capnp.Struct(s))
	return str
}

func (s ClandesService_proxyService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_proxyService_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_proxyService_Params {
	return ClandesService_proxyService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_proxyService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_proxyService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_proxyService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_proxyService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_proxyService_Params_List is a list of ClandesService_proxyService_Params.
type ClandesService_proxyService_Params_List = capnp.StructList[ClandesService_proxyService_Params]

// NewClandesService_proxyService_Params creates a new list of ClandesService_proxyService_Params.
func NewClandesService_proxyService_Params_List(s *capnp.Segment, sz int32) (ClandesService_proxyService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_proxyService_Params](l), err
}

// ClandesService_proxyService_Params_Future is a wrapper for a ClandesService_proxyService_Params promised by a client call.
type ClandesService_proxyService_Params_Future struct{ *capnp.Future }

func (f ClandesService_proxyService_Params_Future) Struct() (ClandesService_proxyService_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_proxyService_Params(p.Struct()), err
}

type ClandesService_proxyService_Results capnp.Struct

// ClandesService_proxyService_Results_TypeID is the unique identifier for the type ClandesService_proxyService_Results.
const ClandesService_proxyService_Results_TypeID = 0x8f41a8d77ae30ae5

func NewClandesService_proxyService_Results(s *capnp.Segment) (ClandesService_proxyService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_proxyService_Results(st), err
}

func NewRootClandesService_proxyService_Results(s *capnp.Segment) (ClandesService_proxyService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_proxyService_Results(st), err
}

func ReadRootClandesService_proxyService_Results(msg *capnp.Message) (ClandesService_proxyService_Results, error) {
	root, err := msg.Root()
	return ClandesService_proxyService_Results(root.Struct()), err
}

func (s ClandesService_proxyService_Results) String() string {
	str, _ := text.Marshal(0x8f41a8d77ae30ae5, capnp.Struct(s))
	return str
}

func (s ClandesService_proxyService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_proxyService_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_proxyService_Results {
	return ClandesService_proxyService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_proxyService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_proxyService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_proxyService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_proxyService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_proxyService_Results) Svc() ProxyService {
	p, _ := capnp.Struct(s).Ptr(0)
	return ProxyService(p.Interface().Client())
}

func (s ClandesService_proxyService_Results) HasSvc() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_proxyService_Results) SetSvc(v ProxyService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ClandesService_proxyService_Results_List is a list of ClandesService_proxyService_Results.
type ClandesService_proxyService_Results_List = capnp.StructList[ClandesService_proxyService_Results]

// NewClandesService_proxyService_Results creates a new list of ClandesService_proxyService_Results.
func NewClandesService_proxyService_Results_List(s *capnp.Segment, sz int32) (ClandesService_proxyService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_proxyService_Results](l), err
}

// ClandesService_proxyService_Results_Future is a wrapper for a ClandesService_proxyService_Results promised by a client call.
type ClandesService_proxyService_Results_Future struct{ *capnp.Future }

func (f ClandesService_proxyService_Results_Future) Struct() (ClandesService_proxyService_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_proxyService_Results(p.Struct()), err
}
func (p ClandesService_proxyService_Results_Future) Svc() ProxyService {
	return ProxyService(p.Future.Field(0, nil).Client())
}

type ClandesService_policyService_Params capnp.Struct

// ClandesService_policyService_Params_TypeID is the unique identifier for the type ClandesService_policyService_Params.
const ClandesService_policyService_Params_TypeID = 0xcb99a7f2d8d84d46

func NewClandesService_policyService_Params(s *capnp.Segment) (ClandesService_policyService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_policyService_Params(st), err
}

func NewRootClandesService_policyService_Params(s *capnp.Segment) (ClandesService_policyService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_policyService_Params(st), err
}

func ReadRootClandesService_policyService_Params(msg *capnp.Message) (ClandesService_policyService_Params, error) {
	root, err := msg.Root()
	return ClandesService_policyService_Params(root.Struct()), err
}

func (s ClandesService_policyService_Params) String() string {
	str, _ := text.Marshal(0xcb99a7f2d8d84d46, capnp.Struct(s))
	return str
}

func (s ClandesService_policyService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_policyService_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_policyService_Params {
	return ClandesService_policyService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_policyService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_policyService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_policyService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_policyService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_policyService_Params_List is a list of ClandesService_policyService_Params.
type ClandesService_policyService_Params_List = capnp.StructList[ClandesService_policyService_Params]

// NewClandesService_policyService_Params creates a new list of ClandesService_policyService_Params.
func NewClandesService_policyService_Params_List(s *capnp.Segment, sz int32) (ClandesService_policyService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_policyService_Params](l), err
}

// ClandesService_policyService_Params_Future is a wrapper for a ClandesService_policyService_Params promised by a client call.
type ClandesService_policyService_Params_Future struct{ *capnp.Future }

func (f ClandesService_policyService_Params_Future) Struct() (ClandesService_policyService_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_policyService_Params(p.Struct()), err
}

type ClandesService_policyService_Results capnp.Struct

// ClandesService_policyService_Results_TypeID is the unique identifier for the type ClandesService_policyService_Results.
const ClandesService_policyService_Results_TypeID = 0xd460053f494a559d

func NewClandesService_policyService_Results(s *capnp.Segment) (ClandesService_policyService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_policyService_Results(st), err
}

func NewRootClandesService_policyService_Results(s *capnp.Segment) (ClandesService_policyService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_policyService_Results(st), err
}

func ReadRootClandesService_policyService_Results(msg *capnp.Message) (ClandesService_policyService_Results, error) {
	root, err := msg.Root()
	return ClandesService_policyService_Results(root.Struct()), err
}

func (s ClandesService_policyService_Results) String() string {
	str, _ := text.Marshal(0xd460053f494a559d, capnp.Struct(s))
	return str
}

func (s ClandesService_policyService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_policyService_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_policyService_Results {
	return ClandesService_policyService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_policyService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_policyService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_policyService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_policyService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_policyService_Results) Svc() PolicyService {
	p, _ := capnp.Struct(s).Ptr(0)
	return PolicyService(p.Interface().Client())
}

func (s ClandesService_policyService_Results) HasSvc() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_policyService_Results) SetSvc(v PolicyService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ClandesService_policyService_Results_List is a list of ClandesService_policyService_Results.
type ClandesService_policyService_Results_List = capnp.StructList[ClandesService_policyService_Results]

// NewClandesService_policyService_Results creates a new list of ClandesService_policyService_Results.
func NewClandesService_policyService_Results_List(s *capnp.Segment, sz int32) (ClandesService_policyService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_policyService_Results](l), err
}

// ClandesService_policyService_Results_Future is a wrapper for a ClandesService_policyService_Results promised by a client call.
type ClandesService_policyService_Results_Future struct{ *capnp.Future }

func (f ClandesService_policyService_Results_Future) Struct() (ClandesService_policyService_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_policyService_Results(p.Struct()), err
}
func (p ClandesService_policyService_Results_Future) Svc() PolicyService {
	return PolicyService(p.Future.Field(0, nil).Client())
}

type ClandesService_getVersion_Params capnp.Struct

// ClandesService_getVersion_Params_TypeID is the unique identifier for the type ClandesService_getVersion_Params.
const ClandesService_getVersion_Params_TypeID = 0x8a269637f1cc83d2

func NewClandesService_getVersion_Params(s *capnp.Segment) (ClandesService_getVersion_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_getVersion_Params(st), err
}

func NewRootClandesService_getVersion_Params(s *capnp.Segment) (ClandesService_getVersion_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_getVersion_Params(st), err
}

func ReadRootClandesService_getVersion_Params(msg *capnp.Message) (ClandesService_getVersion_Params, error) {
	root, err := msg.Root()
	return ClandesService_getVersion_Params(root.Struct()), err
}

func (s ClandesService_getVersion_Params) String() string {
	str, _ := text.Marshal(0x8a269637f1cc83d2, capnp.Struct(s))
	return str
}

func (s ClandesService_getVersion_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_getVersion_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_getVersion_Params {
	return ClandesService_getVersion_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_getVersion_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_getVersion_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_getVersion_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_getVersion_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_getVersion_Params_List is a list of ClandesService_getVersion_Params.
type ClandesService_getVersion_Params_List = capnp.StructList[ClandesService_getVersion_Params]

// NewClandesService_getVersion_Params creates a new list of ClandesService_getVersion_Params.
func NewClandesService_getVersion_Params_List(s *capnp.Segment, sz int32) (ClandesService_getVersion_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_getVersion_Params](l), err
}

// ClandesService_getVersion_Params_Future is a wrapper for a ClandesService_getVersion_Params promised by a client call.
type ClandesService_getVersion_Params_Future struct{ *capnp.Future }

func (f ClandesService_getVersion_Params_Future) Struct() (ClandesService_getVersion_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_getVersion_Params(p.Struct()), err
}

type ClandesService_getVersion_Results capnp.Struct

// ClandesService_getVersion_Results_TypeID is the unique identifier for the type ClandesService_getVersion_Results.
const ClandesService_getVersion_Results_TypeID = 0xcbe105196a238925

func NewClandesService_getVersion_Results(s *capnp.Segment) (ClandesService_getVersion_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_getVersion_Results(st), err
}

func NewRootClandesService_getVersion_Results(s *capnp.Segment) (ClandesService_getVersion_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_getVersion_Results(st), err
}

func ReadRootClandesService_getVersion_Results(msg *capnp.Message) (ClandesService_getVersion_Results, error) {
	root, err := msg.Root()
	return ClandesService_getVersion_Results(root.Struct()), err
}

func (s ClandesService_getVersion_Results) String() string {
	str, _ := text.Marshal(0xcbe105196a238925, capnp.Struct(s))
	return str
}

func (s ClandesService_getVersion_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_getVersion_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_getVersion_Results {
	return ClandesService_getVersion_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_getVersion_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_getVersion_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_getVersion_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_getVersion_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_getVersion_Results) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClandesService_getVersion_Results) HasVersion() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_getVersion_Results) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClandesService_getVersion_Results) SetVersion(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ClandesService_getVersion_Results_List is a list of ClandesService_getVersion_Results.
type ClandesService_getVersion_Results_List = capnp.StructList[ClandesService_getVersion_Results]

// NewClandesService_getVersion_Results creates a new list of ClandesService_getVersion_Results.
func NewClandesService_getVersion_Results_List(s *capnp.Segment, sz int32) (ClandesService_getVersion_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_getVersion_Results](l), err
}

// ClandesService_getVersion_Results_Future is a wrapper for a ClandesService_getVersion_Results promised by a client call.
type ClandesService_getVersion_Results_Future struct{ *capnp.Future }

func (f ClandesService_getVersion_Results_Future) Struct() (ClandesService_getVersion_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_getVersion_Results(p.Struct()), err
}

type ClandesService_codexAuthService_Params capnp.Struct

// ClandesService_codexAuthService_Params_TypeID is the unique identifier for the type ClandesService_codexAuthService_Params.
const ClandesService_codexAuthService_Params_TypeID = 0xcfcac07cdc82940d

func NewClandesService_codexAuthService_Params(s *capnp.Segment) (ClandesService_codexAuthService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_codexAuthService_Params(st), err
}

func NewRootClandesService_codexAuthService_Params(s *capnp.Segment) (ClandesService_codexAuthService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_codexAuthService_Params(st), err
}

func ReadRootClandesService_codexAuthService_Params(msg *capnp.Message) (ClandesService_codexAuthService_Params, error) {
	root, err := msg.Root()
	return ClandesService_codexAuthService_Params(root.Struct()), err
}

func (s ClandesService_codexAuthService_Params) String() string {
	str, _ := text.Marshal(0xcfcac07cdc82940d, capnp.Struct(s))
	return str
}

func (s ClandesService_codexAuthService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_codexAuthService_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_codexAuthService_Params {
	return ClandesService_codexAuthService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_codexAuthService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_codexAuthService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_codexAuthService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_codexAuthService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_codexAuthService_Params_List is a list of ClandesService_codexAuthService_Params.
type ClandesService_codexAuthService_Params_List = capnp.StructList[ClandesService_codexAuthService_Params]

// NewClandesService_codexAuthService_Params creates a new list of ClandesService_codexAuthService_Params.
func NewClandesService_codexAuthService_Params_List(s *capnp.Segment, sz int32) (ClandesService_codexAuthService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_codexAuthService_Params](l), err
}

// ClandesService_codexAuthService_Params_Future is a wrapper for a ClandesService_codexAuthService_Params promised by a client call.
type ClandesService_codexAuthService_Params_Future struct{ *capnp.Future }

func (f ClandesService_codexAuthService_Params_Future) Struct() (ClandesService_codexAuthService_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_codexAuthService_Params(p.Struct()), err
}

type ClandesService_codexAuthService_Results capnp.Struct

// ClandesService_codexAuthService_Results_TypeID is the unique identifier for the type ClandesService_codexAuthService_Results.
const ClandesService_codexAuthService_Results_TypeID = 0x864a5410653ed036

func NewClandesService_codexAuthService_Results(s *capnp.Segment) (ClandesService_codexAuthService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_codexAuthService_Results(st), err
}

func NewRootClandesService_codexAuthService_Results(s *capnp.Segment) (ClandesService_codexAuthService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_codexAuthService_Results(st), err
}

func ReadRootClandesService_codexAuthService_Results(msg *capnp.Message) (ClandesService_codexAuthService_Results, error) {
	root, err := msg.Root()
	return ClandesService_codexAuthService_Results(root.Struct()), err
}

func (s ClandesService_codexAuthService_Results) String() string {
	str, _ := text.Marshal(0x864a5410653ed036, capnp.Struct(s))
	return str
}

func (s ClandesService_codexAuthService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_codexAuthService_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_codexAuthService_Results {
	return ClandesService_codexAuthService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_codexAuthService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_codexAuthService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_codexAuthService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_codexAuthService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_codexAuthService_Results) Svc() CodexAuthService {
	p, _ := capnp.Struct(s).Ptr(0)
	return CodexAuthService(p.Interface().Client())
}

func (s ClandesService_codexAuthService_Results) HasSvc() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_codexAuthService_Results) SetSvc(v CodexAuthService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ClandesService_codexAuthService_Results_List is a list of ClandesService_codexAuthService_Results.
type ClandesService_codexAuthService_Results_List = capnp.StructList[ClandesService_codexAuthService_Results]

// NewClandesService_codexAuthService_Results creates a new list of ClandesService_codexAuthService_Results.
func NewClandesService_codexAuthService_Results_List(s *capnp.Segment, sz int32) (ClandesService_codexAuthService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_codexAuthService_Results](l), err
}

// ClandesService_codexAuthService_Results_Future is a wrapper for a ClandesService_codexAuthService_Results promised by a client call.
type ClandesService_codexAuthService_Results_Future struct{ *capnp.Future }

func (f ClandesService_codexAuthService_Results_Future) Struct() (ClandesService_codexAuthService_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_codexAuthService_Results(p.Struct()), err
}
func (p ClandesService_codexAuthService_Results_Future) Svc() CodexAuthService {
	return CodexAuthService(p.Future.Field(0, nil).Client())
}

type ClandesService_codexQueryService_Params capnp.Struct

// ClandesService_codexQueryService_Params_TypeID is the unique identifier for the type ClandesService_codexQueryService_Params.
const ClandesService_codexQueryService_Params_TypeID = 0xbb180e0af8c3a17d

func NewClandesService_codexQueryService_Params(s *capnp.Segment) (ClandesService_codexQueryService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_codexQueryService_Params(st), err
}

func NewRootClandesService_codexQueryService_Params(s *capnp.Segment) (ClandesService_codexQueryService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ClandesService_codexQueryService_Params(st), err
}

func ReadRootClandesService_codexQueryService_Params(msg *capnp.Message) (ClandesService_codexQueryService_Params, error) {
	root, err := msg.Root()
	return ClandesService_codexQueryService_Params(root.Struct()), err
}

func (s ClandesService_codexQueryService_Params) String() string {
	str, _ := text.Marshal(0xbb180e0af8c3a17d, capnp.Struct(s))
	return str
}

func (s ClandesService_codexQueryService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_codexQueryService_Params) DecodeFromPtr(p capnp.Ptr) ClandesService_codexQueryService_Params {
	return ClandesService_codexQueryService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_codexQueryService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_codexQueryService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_codexQueryService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_codexQueryService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ClandesService_codexQueryService_Params_List is a list of ClandesService_codexQueryService_Params.
type ClandesService_codexQueryService_Params_List = capnp.StructList[ClandesService_codexQueryService_Params]

// NewClandesService_codexQueryService_Params creates a new list of ClandesService_codexQueryService_Params.
func NewClandesService_codexQueryService_Params_List(s *capnp.Segment, sz int32) (ClandesService_codexQueryService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ClandesService_codexQueryService_Params](l), err
}

// ClandesService_codexQueryService_Params_Future is a wrapper for a ClandesService_codexQueryService_Params promised by a client call.
type ClandesService_codexQueryService_Params_Future struct{ *capnp.Future }

func (f ClandesService_codexQueryService_Params_Future) Struct() (ClandesService_codexQueryService_Params, error) {
	p, err := f.Future.Ptr()
	return ClandesService_codexQueryService_Params(p.Struct()), err
}

type ClandesService_codexQueryService_Results capnp.Struct

// ClandesService_codexQueryService_Results_TypeID is the unique identifier for the type ClandesService_codexQueryService_Results.
const ClandesService_codexQueryService_Results_TypeID = 0xb9afdabfcfebc339

func NewClandesService_codexQueryService_Results(s *capnp.Segment) (ClandesService_codexQueryService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_codexQueryService_Results(st), err
}

func NewRootClandesService_codexQueryService_Results(s *capnp.Segment) (ClandesService_codexQueryService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClandesService_codexQueryService_Results(st), err
}

func ReadRootClandesService_codexQueryService_Results(msg *capnp.Message) (ClandesService_codexQueryService_Results, error) {
	root, err := msg.Root()
	return ClandesService_codexQueryService_Results(root.Struct()), err
}

func (s ClandesService_codexQueryService_Results) String() string {
	str, _ := text.Marshal(0xb9afdabfcfebc339, capnp.Struct(s))
	return str
}

func (s ClandesService_codexQueryService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClandesService_codexQueryService_Results) DecodeFromPtr(p capnp.Ptr) ClandesService_codexQueryService_Results {
	return ClandesService_codexQueryService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClandesService_codexQueryService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClandesService_codexQueryService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClandesService_codexQueryService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClandesService_codexQueryService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClandesService_codexQueryService_Results) Svc() CodexQueryService {
	p, _ := capnp.Struct(s).Ptr(0)
	return CodexQueryService(p.Interface().Client())
}

func (s ClandesService_codexQueryService_Results) HasSvc() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClandesService_codexQueryService_Results) SetSvc(v CodexQueryService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ClandesService_codexQueryService_Results_List is a list of ClandesService_codexQueryService_Results.
type ClandesService_codexQueryService_Results_List = capnp.StructList[ClandesService_codexQueryService_Results]

// NewClandesService_codexQueryService_Results creates a new list of ClandesService_codexQueryService_Results.
func NewClandesService_codexQueryService_Results_List(s *capnp.Segment, sz int32) (ClandesService_codexQueryService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClandesService_codexQueryService_Results](l), err
}

// ClandesService_codexQueryService_Results_Future is a wrapper for a ClandesService_codexQueryService_Results promised by a client call.
type ClandesService_codexQueryService_Results_Future struct{ *capnp.Future }

func (f ClandesService_codexQueryService_Results_Future) Struct() (ClandesService_codexQueryService_Results, error) {
	p, err := f.Future.Ptr()
	return ClandesService_codexQueryService_Results(p.Struct()), err
}
func (p ClandesService_codexQueryService_Results_Future) Svc() CodexQueryService {
	return CodexQueryService(p.Future.Field(0, nil).Client())
}
