// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	math "math"
)

type UsagePeriod capnp.Struct

// UsagePeriod_TypeID is the unique identifier for the type UsagePeriod.
const UsagePeriod_TypeID = 0xfde55e57e0e102e4

func NewUsagePeriod(s *capnp.Segment) (UsagePeriod, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UsagePeriod(st), err
}

func NewRootUsagePeriod(s *capnp.Segment) (UsagePeriod, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UsagePeriod(st), err
}

func ReadRootUsagePeriod(msg *capnp.Message) (UsagePeriod, error) {
	root, err := msg.Root()
	return UsagePeriod(root.Struct()), err
}

func (s UsagePeriod) String() string {
	str, _ := text.Marshal(0xfde55e57e0e102e4, capnp.Struct(s))
	return str
}

func (s UsagePeriod) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UsagePeriod) DecodeFromPtr(p capnp.Ptr) UsagePeriod {
	return UsagePeriod(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UsagePeriod) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UsagePeriod) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UsagePeriod) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UsagePeriod) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UsagePeriod) Utilization() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s UsagePeriod) SetUtilization(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s UsagePeriod) ResetsAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UsagePeriod) HasResetsAt() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UsagePeriod) ResetsAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UsagePeriod) SetResetsAt(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// UsagePeriod_List is a list of UsagePeriod.
type UsagePeriod_List = capnp.StructList[UsagePeriod]

// NewUsagePeriod creates a new list of UsagePeriod.
func NewUsagePeriod_List(s *capnp.Segment, sz int32) (UsagePeriod_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[UsagePeriod](l), err
}

// UsagePeriod_Future is a wrapper for a UsagePeriod promised by a client call.
type UsagePeriod_Future struct{ *capnp.Future }

func (f UsagePeriod_Future) Struct() (UsagePeriod, error) {
	p, err := f.Future.Ptr()
	return UsagePeriod(p.Struct()), err
}

type ExtraUsage capnp.Struct

// ExtraUsage_TypeID is the unique identifier for the type ExtraUsage.
const ExtraUsage_TypeID = 0xcad77cecc30d0a4f

func NewExtraUsage(s *capnp.Segment) (ExtraUsage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return ExtraUsage(st), err
}

func NewRootExtraUsage(s *capnp.Segment) (ExtraUsage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return ExtraUsage(st), err
}

func ReadRootExtraUsage(msg *capnp.Message) (ExtraUsage, error) {
	root, err := msg.Root()
	return ExtraUsage(root.Struct()), err
}

func (s ExtraUsage) String() string {
	str, _ := text.Marshal(0xcad77cecc30d0a4f, capnp.Struct(s))
	return str
}

func (s ExtraUsage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ExtraUsage) DecodeFromPtr(p capnp.Ptr) ExtraUsage {
	return ExtraUsage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ExtraUsage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ExtraUsage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ExtraUsage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ExtraUsage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ExtraUsage) IsEnabled() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ExtraUsage) SetIsEnabled(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ExtraUsage) MonthlyLimit() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s ExtraUsage) SetMonthlyLimit(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s ExtraUsage) UsedCredits() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s ExtraUsage) SetUsedCredits(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s ExtraUsage) Utilization() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s ExtraUsage) SetUtilization(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

// ExtraUsage_List is a list of ExtraUsage.
type ExtraUsage_List = capnp.StructList[ExtraUsage]

// NewExtraUsage creates a new list of ExtraUsage.
func NewExtraUsage_List(s *capnp.Segment, sz int32) (ExtraUsage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0}, sz)
	return capnp.StructList[ExtraUsage](l), err
}

// ExtraUsage_Future is a wrapper for a ExtraUsage promised by a client call.
type ExtraUsage_Future struct{ *capnp.Future }

func (f ExtraUsage_Future) Struct() (ExtraUsage, error) {
	p, err := f.Future.Ptr()
	return ExtraUsage(p.Struct()), err
}

type ClaudeQueryService capnp.Client

// ClaudeQueryService_TypeID is the unique identifier for the type ClaudeQueryService.
const ClaudeQueryService_TypeID = 0xc91ac16c25a26e24

func (c ClaudeQueryService) GetProfile(ctx context.Context, params func(ClaudeQueryService_getProfile_Params) error) (ClaudeQueryService_getProfile_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc91ac16c25a26e24,
			MethodID:      0,
			InterfaceName: "claude_query.capnp:ClaudeQueryService",
			MethodName:    "getProfile",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClaudeQueryService_getProfile_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClaudeQueryService_getProfile_Results_Future{Future: ans.Future()}, release

}

func (c ClaudeQueryService) GetUsage(ctx context.Context, params func(ClaudeQueryService_getUsage_Params) error) (ClaudeQueryService_getUsage_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc91ac16c25a26e24,
			MethodID:      1,
			InterfaceName: "claude_query.capnp:ClaudeQueryService",
			MethodName:    "getUsage",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClaudeQueryService_getUsage_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClaudeQueryService_getUsage_Results_Future{Future: ans.Future()}, release

}

func (c ClaudeQueryService) GetRoles(ctx context.Context, params func(ClaudeQueryService_getRoles_Params) error) (ClaudeQueryService_getRoles_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc91ac16c25a26e24,
			MethodID:      2,
			InterfaceName: "claude_query.capnp:ClaudeQueryService",
			MethodName:    "getRoles",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ClaudeQueryService_getRoles_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ClaudeQueryService_getRoles_Results_Future{Future: ans.Future()}, release

}

func (c ClaudeQueryService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c ClaudeQueryService) String() string {
	return "ClaudeQueryService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c ClaudeQueryService) AddRef() ClaudeQueryService {
	return ClaudeQueryService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c ClaudeQueryService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c ClaudeQueryService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c ClaudeQueryService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (ClaudeQueryService) DecodeFromPtr(p capnp.Ptr) ClaudeQueryService {
	return ClaudeQueryService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c ClaudeQueryService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c ClaudeQueryService) IsSame(other ClaudeQueryService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c ClaudeQueryService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c ClaudeQueryService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A ClaudeQueryService_Server is a ClaudeQueryService with a local implementation.
type ClaudeQueryService_Server interface {
	GetProfile(context.Context, ClaudeQueryService_getProfile) error

	GetUsage(context.Context, ClaudeQueryService_getUsage) error

	GetRoles(context.Context, ClaudeQueryService_getRoles) error
}

// ClaudeQueryService_NewServer creates a new Server from an implementation of ClaudeQueryService_Server.
func ClaudeQueryService_NewServer(s ClaudeQueryService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ClaudeQueryService_Methods(nil, s), s, c)
}

// ClaudeQueryService_ServerToClient creates a new Client from an implementation of ClaudeQueryService_Server.
// The caller is responsible for calling Release on the returned Client.
func ClaudeQueryService_ServerToClient(s ClaudeQueryService_Server) ClaudeQueryService {
	return ClaudeQueryService(capnp.NewClient(ClaudeQueryService_NewServer(s)))
}

// ClaudeQueryService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ClaudeQueryService_Methods(methods []server.Method, s ClaudeQueryService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc91ac16c25a26e24,
			MethodID:      0,
			InterfaceName: "claude_query.capnp:ClaudeQueryService",
			MethodName:    "getProfile",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetProfile(ctx, ClaudeQueryService_getProfile{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc91ac16c25a26e24,
			MethodID:      1,
			InterfaceName: "claude_query.capnp:ClaudeQueryService",
			MethodName:    "getUsage",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetUsage(ctx, ClaudeQueryService_getUsage{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc91ac16c25a26e24,
			MethodID:      2,
			InterfaceName: "claude_query.capnp:ClaudeQueryService",
			MethodName:    "getRoles",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetRoles(ctx, ClaudeQueryService_getRoles{call})
		},
	})

	return methods
}

// ClaudeQueryService_getProfile holds the state for a server call to ClaudeQueryService.getProfile.
// See server.Call for documentation.
type ClaudeQueryService_getProfile struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClaudeQueryService_getProfile) Args() ClaudeQueryService_getProfile_Params {
	return ClaudeQueryService_getProfile_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClaudeQueryService_getProfile) AllocResults() (ClaudeQueryService_getProfile_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 10})
	return ClaudeQueryService_getProfile_Results(r), err
}

// ClaudeQueryService_getUsage holds the state for a server call to ClaudeQueryService.getUsage.
// See server.Call for documentation.
type ClaudeQueryService_getUsage struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClaudeQueryService_getUsage) Args() ClaudeQueryService_getUsage_Params {
	return ClaudeQueryService_getUsage_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClaudeQueryService_getUsage) AllocResults() (ClaudeQueryService_getUsage_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return ClaudeQueryService_getUsage_Results(r), err
}

// ClaudeQueryService_getRoles holds the state for a server call to ClaudeQueryService.getRoles.
// See server.Call for documentation.
type ClaudeQueryService_getRoles struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ClaudeQueryService_getRoles) Args() ClaudeQueryService_getRoles_Params {
	return ClaudeQueryService_getRoles_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ClaudeQueryService_getRoles) AllocResults() (ClaudeQueryService_getRoles_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return ClaudeQueryService_getRoles_Results(r), err
}

// ClaudeQueryService_List is a list of ClaudeQueryService.
type ClaudeQueryService_List = capnp.CapList[ClaudeQueryService]

// NewClaudeQueryService_List creates a new list of ClaudeQueryService.
func NewClaudeQueryService_List(s *capnp.Segment, sz int32) (ClaudeQueryService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[ClaudeQueryService](l), err
}

type ClaudeQueryService_getProfile_Params capnp.Struct

// ClaudeQueryService_getProfile_Params_TypeID is the unique identifier for the type ClaudeQueryService_getProfile_Params.
const ClaudeQueryService_getProfile_Params_TypeID = 0x812a80e89166a990

func NewClaudeQueryService_getProfile_Params(s *capnp.Segment) (ClaudeQueryService_getProfile_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClaudeQueryService_getProfile_Params(st), err
}

func NewRootClaudeQueryService_getProfile_Params(s *capnp.Segment) (ClaudeQueryService_getProfile_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClaudeQueryService_getProfile_Params(st), err
}

func ReadRootClaudeQueryService_getProfile_Params(msg *capnp.Message) (ClaudeQueryService_getProfile_Params, error) {
	root, err := msg.Root()
	return ClaudeQueryService_getProfile_Params(root.Struct()), err
}

func (s ClaudeQueryService_getProfile_Params) String() string {
	str, _ := text.Marshal(0x812a80e89166a990, capnp.Struct(s))
	return str
}

func (s ClaudeQueryService_getProfile_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeQueryService_getProfile_Params) DecodeFromPtr(p capnp.Ptr) ClaudeQueryService_getProfile_Params {
	return ClaudeQueryService_getProfile_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeQueryService_getProfile_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeQueryService_getProfile_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeQueryService_getProfile_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeQueryService_getProfile_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeQueryService_getProfile_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeQueryService_getProfile_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ClaudeQueryService_getProfile_Params_List is a list of ClaudeQueryService_getProfile_Params.
type ClaudeQueryService_getProfile_Params_List = capnp.StructList[ClaudeQueryService_getProfile_Params]

// NewClaudeQueryService_getProfile_Params creates a new list of ClaudeQueryService_getProfile_Params.
func NewClaudeQueryService_getProfile_Params_List(s *capnp.Segment, sz int32) (ClaudeQueryService_getProfile_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClaudeQueryService_getProfile_Params](l), err
}

// ClaudeQueryService_getProfile_Params_Future is a wrapper for a ClaudeQueryService_getProfile_Params promised by a client call.
type ClaudeQueryService_getProfile_Params_Future struct{ *capnp.Future }

func (f ClaudeQueryService_getProfile_Params_Future) Struct() (ClaudeQueryService_getProfile_Params, error) {
	p, err := f.Future.Ptr()
	return ClaudeQueryService_getProfile_Params(p.Struct()), err
}

type ClaudeQueryService_getProfile_Results capnp.Struct

// ClaudeQueryService_getProfile_Results_TypeID is the unique identifier for the type ClaudeQueryService_getProfile_Results.
const ClaudeQueryService_getProfile_Results_TypeID = 0xa26abc09da3e2fb7

func NewClaudeQueryService_getProfile_Results(s *capnp.Segment) (ClaudeQueryService_getProfile_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 10})
	return ClaudeQueryService_getProfile_Results(st), err
}

func NewRootClaudeQueryService_getProfile_Results(s *capnp.Segment) (ClaudeQueryService_getProfile_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 10})
	return ClaudeQueryService_getProfile_Results(st), err
}

func ReadRootClaudeQueryService_getProfile_Results(msg *capnp.Message) (ClaudeQueryService_getProfile_Results, error) {
	root, err := msg.Root()
	return ClaudeQueryService_getProfile_Results(root.Struct()), err
}

func (s ClaudeQueryService_getProfile_Results) String() string {
	str, _ := text.Marshal(0xa26abc09da3e2fb7, capnp.Struct(s))
	return str
}

func (s ClaudeQueryService_getProfile_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeQueryService_getProfile_Results) DecodeFromPtr(p capnp.Ptr) ClaudeQueryService_getProfile_Results {
	return ClaudeQueryService_getProfile_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeQueryService_getProfile_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeQueryService_getProfile_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeQueryService_getProfile_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeQueryService_getProfile_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeQueryService_getProfile_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ClaudeQueryService_getProfile_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ClaudeQueryService_getProfile_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeQueryService_getProfile_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeQueryService_getProfile_Results) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeQueryService_getProfile_Results) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ClaudeQueryService_getProfile_Results) Email() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasEmail() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ClaudeQueryService_getProfile_Results) EmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetEmail(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ClaudeQueryService_getProfile_Results) DisplayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasDisplayName() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ClaudeQueryService_getProfile_Results) DisplayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetDisplayName(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ClaudeQueryService_getProfile_Results) CreatedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasCreatedAt() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ClaudeQueryService_getProfile_Results) CreatedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetCreatedAt(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ClaudeQueryService_getProfile_Results) OrganizationId() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasOrganizationId() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ClaudeQueryService_getProfile_Results) OrganizationIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetOrganizationId(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s ClaudeQueryService_getProfile_Results) OrganizationType() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasOrganizationType() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s ClaudeQueryService_getProfile_Results) OrganizationTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetOrganizationType(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s ClaudeQueryService_getProfile_Results) RateLimitTier() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasRateLimitTier() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s ClaudeQueryService_getProfile_Results) RateLimitTierBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetRateLimitTier(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s ClaudeQueryService_getProfile_Results) HasExtraUsageEnabled() bool {
	return capnp.Struct(s).Bit(1)
}

func (s ClaudeQueryService_getProfile_Results) SetHasExtraUsageEnabled(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s ClaudeQueryService_getProfile_Results) BillingType() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasBillingType() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s ClaudeQueryService_getProfile_Results) BillingTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetBillingType(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s ClaudeQueryService_getProfile_Results) SubscriptionCreatedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.Text(), err
}

func (s ClaudeQueryService_getProfile_Results) HasSubscriptionCreatedAt() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s ClaudeQueryService_getProfile_Results) SubscriptionCreatedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getProfile_Results) SetSubscriptionCreatedAt(v string) error {
	return capnp.Struct(s).SetText(9, v)
}

// ClaudeQueryService_getProfile_Results_List is a list of ClaudeQueryService_getProfile_Results.
type ClaudeQueryService_getProfile_Results_List = capnp.StructList[ClaudeQueryService_getProfile_Results]

// NewClaudeQueryService_getProfile_Results creates a new list of ClaudeQueryService_getProfile_Results.
func NewClaudeQueryService_getProfile_Results_List(s *capnp.Segment, sz int32) (ClaudeQueryService_getProfile_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 10}, sz)
	return capnp.StructList[ClaudeQueryService_getProfile_Results](l), err
}

// ClaudeQueryService_getProfile_Results_Future is a wrapper for a ClaudeQueryService_getProfile_Results promised by a client call.
type ClaudeQueryService_getProfile_Results_Future struct{ *capnp.Future }

func (f ClaudeQueryService_getProfile_Results_Future) Struct() (ClaudeQueryService_getProfile_Results, error) {
	p, err := f.Future.Ptr()
	return ClaudeQueryService_getProfile_Results(p.Struct()), err
}

type ClaudeQueryService_getUsage_Params capnp.Struct

// ClaudeQueryService_getUsage_Params_TypeID is the unique identifier for the type ClaudeQueryService_getUsage_Params.
const ClaudeQueryService_getUsage_Params_TypeID = 0xecc66096292a689f

func NewClaudeQueryService_getUsage_Params(s *capnp.Segment) (ClaudeQueryService_getUsage_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClaudeQueryService_getUsage_Params(st), err
}

func NewRootClaudeQueryService_getUsage_Params(s *capnp.Segment) (ClaudeQueryService_getUsage_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClaudeQueryService_getUsage_Params(st), err
}

func ReadRootClaudeQueryService_getUsage_Params(msg *capnp.Message) (ClaudeQueryService_getUsage_Params, error) {
	root, err := msg.Root()
	return ClaudeQueryService_getUsage_Params(root.Struct()), err
}

func (s ClaudeQueryService_getUsage_Params) String() string {
	str, _ := text.Marshal(0xecc66096292a689f, capnp.Struct(s))
	return str
}

func (s ClaudeQueryService_getUsage_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeQueryService_getUsage_Params) DecodeFromPtr(p capnp.Ptr) ClaudeQueryService_getUsage_Params {
	return ClaudeQueryService_getUsage_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeQueryService_getUsage_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeQueryService_getUsage_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeQueryService_getUsage_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeQueryService_getUsage_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeQueryService_getUsage_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeQueryService_getUsage_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeQueryService_getUsage_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getUsage_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ClaudeQueryService_getUsage_Params_List is a list of ClaudeQueryService_getUsage_Params.
type ClaudeQueryService_getUsage_Params_List = capnp.StructList[ClaudeQueryService_getUsage_Params]

// NewClaudeQueryService_getUsage_Params creates a new list of ClaudeQueryService_getUsage_Params.
func NewClaudeQueryService_getUsage_Params_List(s *capnp.Segment, sz int32) (ClaudeQueryService_getUsage_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClaudeQueryService_getUsage_Params](l), err
}

// ClaudeQueryService_getUsage_Params_Future is a wrapper for a ClaudeQueryService_getUsage_Params promised by a client call.
type ClaudeQueryService_getUsage_Params_Future struct{ *capnp.Future }

func (f ClaudeQueryService_getUsage_Params_Future) Struct() (ClaudeQueryService_getUsage_Params, error) {
	p, err := f.Future.Ptr()
	return ClaudeQueryService_getUsage_Params(p.Struct()), err
}

type ClaudeQueryService_getUsage_Results capnp.Struct

// ClaudeQueryService_getUsage_Results_TypeID is the unique identifier for the type ClaudeQueryService_getUsage_Results.
const ClaudeQueryService_getUsage_Results_TypeID = 0x949970f09afa9668

func NewClaudeQueryService_getUsage_Results(s *capnp.Segment) (ClaudeQueryService_getUsage_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return ClaudeQueryService_getUsage_Results(st), err
}

func NewRootClaudeQueryService_getUsage_Results(s *capnp.Segment) (ClaudeQueryService_getUsage_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return ClaudeQueryService_getUsage_Results(st), err
}

func ReadRootClaudeQueryService_getUsage_Results(msg *capnp.Message) (ClaudeQueryService_getUsage_Results, error) {
	root, err := msg.Root()
	return ClaudeQueryService_getUsage_Results(root.Struct()), err
}

func (s ClaudeQueryService_getUsage_Results) String() string {
	str, _ := text.Marshal(0x949970f09afa9668, capnp.Struct(s))
	return str
}

func (s ClaudeQueryService_getUsage_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeQueryService_getUsage_Results) DecodeFromPtr(p capnp.Ptr) ClaudeQueryService_getUsage_Results {
	return ClaudeQueryService_getUsage_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeQueryService_getUsage_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeQueryService_getUsage_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeQueryService_getUsage_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeQueryService_getUsage_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeQueryService_getUsage_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ClaudeQueryService_getUsage_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ClaudeQueryService_getUsage_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeQueryService_getUsage_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeQueryService_getUsage_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getUsage_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeQueryService_getUsage_Results) FiveHour() (UsagePeriod, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return UsagePeriod(p.Struct()), err
}

func (s ClaudeQueryService_getUsage_Results) HasFiveHour() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeQueryService_getUsage_Results) SetFiveHour(v UsagePeriod) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewFiveHour sets the fiveHour field to a newly
// allocated UsagePeriod struct, preferring placement in s's segment.
func (s ClaudeQueryService_getUsage_Results) NewFiveHour() (UsagePeriod, error) {
	ss, err := NewUsagePeriod(capnp.Struct(s).Segment())
	if err != nil {
		return UsagePeriod{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ClaudeQueryService_getUsage_Results) SevenDay() (UsagePeriod, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return UsagePeriod(p.Struct()), err
}

func (s ClaudeQueryService_getUsage_Results) HasSevenDay() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ClaudeQueryService_getUsage_Results) SetSevenDay(v UsagePeriod) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewSevenDay sets the sevenDay field to a newly
// allocated UsagePeriod struct, preferring placement in s's segment.
func (s ClaudeQueryService_getUsage_Results) NewSevenDay() (UsagePeriod, error) {
	ss, err := NewUsagePeriod(capnp.Struct(s).Segment())
	if err != nil {
		return UsagePeriod{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ClaudeQueryService_getUsage_Results) SevenDaySonnet() (UsagePeriod, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return UsagePeriod(p.Struct()), err
}

func (s ClaudeQueryService_getUsage_Results) HasSevenDaySonnet() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ClaudeQueryService_getUsage_Results) SetSevenDaySonnet(v UsagePeriod) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewSevenDaySonnet sets the sevenDaySonnet field to a newly
// allocated UsagePeriod struct, preferring placement in s's segment.
func (s ClaudeQueryService_getUsage_Results) NewSevenDaySonnet() (UsagePeriod, error) {
	ss, err := NewUsagePeriod(capnp.Struct(s).Segment())
	if err != nil {
		return UsagePeriod{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ClaudeQueryService_getUsage_Results) ExtraUsage() (ExtraUsage, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return ExtraUsage(p.Struct()), err
}

func (s ClaudeQueryService_getUsage_Results) HasExtraUsage() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ClaudeQueryService_getUsage_Results) SetExtraUsage(v ExtraUsage) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewExtraUsage sets the extraUsage field to a newly
// allocated ExtraUsage struct, preferring placement in s's segment.
func (s ClaudeQueryService_getUsage_Results) NewExtraUsage() (ExtraUsage, error) {
	ss, err := NewExtraUsage(capnp.Struct(s).Segment())
	if err != nil {
		return ExtraUsage{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ClaudeQueryService_getUsage_Results_List is a list of ClaudeQueryService_getUsage_Results.
type ClaudeQueryService_getUsage_Results_List = capnp.StructList[ClaudeQueryService_getUsage_Results]

// NewClaudeQueryService_getUsage_Results creates a new list of ClaudeQueryService_getUsage_Results.
func NewClaudeQueryService_getUsage_Results_List(s *capnp.Segment, sz int32) (ClaudeQueryService_getUsage_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5}, sz)
	return capnp.StructList[ClaudeQueryService_getUsage_Results](l), err
}

// ClaudeQueryService_getUsage_Results_Future is a wrapper for a ClaudeQueryService_getUsage_Results promised by a client call.
type ClaudeQueryService_getUsage_Results_Future struct{ *capnp.Future }

func (f ClaudeQueryService_getUsage_Results_Future) Struct() (ClaudeQueryService_getUsage_Results, error) {
	p, err := f.Future.Ptr()
	return ClaudeQueryService_getUsage_Results(p.Struct()), err
}
func (p ClaudeQueryService_getUsage_Results_Future) FiveHour() UsagePeriod_Future {
	return UsagePeriod_Future{Future: p.Future.Field(1, nil)}
}
func (p ClaudeQueryService_getUsage_Results_Future) SevenDay() UsagePeriod_Future {
	return UsagePeriod_Future{Future: p.Future.Field(2, nil)}
}
func (p ClaudeQueryService_getUsage_Results_Future) SevenDaySonnet() UsagePeriod_Future {
	return UsagePeriod_Future{Future: p.Future.Field(3, nil)}
}
func (p ClaudeQueryService_getUsage_Results_Future) ExtraUsage() ExtraUsage_Future {
	return ExtraUsage_Future{Future: p.Future.Field(4, nil)}
}

type ClaudeQueryService_getRoles_Params capnp.Struct

// ClaudeQueryService_getRoles_Params_TypeID is the unique identifier for the type ClaudeQueryService_getRoles_Params.
const ClaudeQueryService_getRoles_Params_TypeID = 0xf0f08b2f6abe32aa

func NewClaudeQueryService_getRoles_Params(s *capnp.Segment) (ClaudeQueryService_getRoles_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClaudeQueryService_getRoles_Params(st), err
}

func NewRootClaudeQueryService_getRoles_Params(s *capnp.Segment) (ClaudeQueryService_getRoles_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClaudeQueryService_getRoles_Params(st), err
}

func ReadRootClaudeQueryService_getRoles_Params(msg *capnp.Message) (ClaudeQueryService_getRoles_Params, error) {
	root, err := msg.Root()
	return ClaudeQueryService_getRoles_Params(root.Struct()), err
}

func (s ClaudeQueryService_getRoles_Params) String() string {
	str, _ := text.Marshal(0xf0f08b2f6abe32aa, capnp.Struct(s))
	return str
}

func (s ClaudeQueryService_getRoles_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeQueryService_getRoles_Params) DecodeFromPtr(p capnp.Ptr) ClaudeQueryService_getRoles_Params {
	return ClaudeQueryService_getRoles_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeQueryService_getRoles_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeQueryService_getRoles_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeQueryService_getRoles_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeQueryService_getRoles_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeQueryService_getRoles_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeQueryService_getRoles_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeQueryService_getRoles_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getRoles_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ClaudeQueryService_getRoles_Params_List is a list of ClaudeQueryService_getRoles_Params.
type ClaudeQueryService_getRoles_Params_List = capnp.StructList[ClaudeQueryService_getRoles_Params]

// NewClaudeQueryService_getRoles_Params creates a new list of ClaudeQueryService_getRoles_Params.
func NewClaudeQueryService_getRoles_Params_List(s *capnp.Segment, sz int32) (ClaudeQueryService_getRoles_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClaudeQueryService_getRoles_Params](l), err
}

// ClaudeQueryService_getRoles_Params_Future is a wrapper for a ClaudeQueryService_getRoles_Params promised by a client call.
type ClaudeQueryService_getRoles_Params_Future struct{ *capnp.Future }

func (f ClaudeQueryService_getRoles_Params_Future) Struct() (ClaudeQueryService_getRoles_Params, error) {
	p, err := f.Future.Ptr()
	return ClaudeQueryService_getRoles_Params(p.Struct()), err
}

type ClaudeQueryService_getRoles_Results capnp.Struct

// ClaudeQueryService_getRoles_Results_TypeID is the unique identifier for the type ClaudeQueryService_getRoles_Results.
const ClaudeQueryService_getRoles_Results_TypeID = 0xeca03dddeeb9a7c5

func NewClaudeQueryService_getRoles_Results(s *capnp.Segment) (ClaudeQueryService_getRoles_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return ClaudeQueryService_getRoles_Results(st), err
}

func NewRootClaudeQueryService_getRoles_Results(s *capnp.Segment) (ClaudeQueryService_getRoles_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return ClaudeQueryService_getRoles_Results(st), err
}

func ReadRootClaudeQueryService_getRoles_Results(msg *capnp.Message) (ClaudeQueryService_getRoles_Results, error) {
	root, err := msg.Root()
	return ClaudeQueryService_getRoles_Results(root.Struct()), err
}

func (s ClaudeQueryService_getRoles_Results) String() string {
	str, _ := text.Marshal(0xeca03dddeeb9a7c5, capnp.Struct(s))
	return str
}

func (s ClaudeQueryService_getRoles_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeQueryService_getRoles_Results) DecodeFromPtr(p capnp.Ptr) ClaudeQueryService_getRoles_Results {
	return ClaudeQueryService_getRoles_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeQueryService_getRoles_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeQueryService_getRoles_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeQueryService_getRoles_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeQueryService_getRoles_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeQueryService_getRoles_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ClaudeQueryService_getRoles_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ClaudeQueryService_getRoles_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeQueryService_getRoles_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeQueryService_getRoles_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getRoles_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeQueryService_getRoles_Results) OrganizationRole() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeQueryService_getRoles_Results) HasOrganizationRole() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeQueryService_getRoles_Results) OrganizationRoleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getRoles_Results) SetOrganizationRole(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ClaudeQueryService_getRoles_Results) WorkspaceRole() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ClaudeQueryService_getRoles_Results) HasWorkspaceRole() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ClaudeQueryService_getRoles_Results) WorkspaceRoleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getRoles_Results) SetWorkspaceRole(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ClaudeQueryService_getRoles_Results) OrganizationName() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ClaudeQueryService_getRoles_Results) HasOrganizationName() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ClaudeQueryService_getRoles_Results) OrganizationNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ClaudeQueryService_getRoles_Results) SetOrganizationName(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// ClaudeQueryService_getRoles_Results_List is a list of ClaudeQueryService_getRoles_Results.
type ClaudeQueryService_getRoles_Results_List = capnp.StructList[ClaudeQueryService_getRoles_Results]

// NewClaudeQueryService_getRoles_Results creates a new list of ClaudeQueryService_getRoles_Results.
func NewClaudeQueryService_getRoles_Results_List(s *capnp.Segment, sz int32) (ClaudeQueryService_getRoles_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[ClaudeQueryService_getRoles_Results](l), err
}

// ClaudeQueryService_getRoles_Results_Future is a wrapper for a ClaudeQueryService_getRoles_Results promised by a client call.
type ClaudeQueryService_getRoles_Results_Future struct{ *capnp.Future }

func (f ClaudeQueryService_getRoles_Results_Future) Struct() (ClaudeQueryService_getRoles_Results, error) {
	p, err := f.Future.Ptr()
	return ClaudeQueryService_getRoles_Results(p.Struct()), err
}
