// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type CodexAuthService capnp.Client

// CodexAuthService_TypeID is the unique identifier for the type CodexAuthService.
const CodexAuthService_TypeID = 0xfa467d4512810ace

func (c CodexAuthService) StartLogin(ctx context.Context, params func(CodexAuthService_startLogin_Params) error) (CodexAuthService_startLogin_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      0,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "startLogin",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CodexAuthService_startLogin_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CodexAuthService_startLogin_Results_Future{Future: ans.Future()}, release

}

func (c CodexAuthService) CompleteLogin(ctx context.Context, params func(CodexAuthService_completeLogin_Params) error) (CodexAuthService_completeLogin_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      1,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "completeLogin",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CodexAuthService_completeLogin_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CodexAuthService_completeLogin_Results_Future{Future: ans.Future()}, release

}

func (c CodexAuthService) RefreshAccountToken(ctx context.Context, params func(CodexAuthService_refreshAccountToken_Params) error) (CodexAuthService_refreshAccountToken_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      2,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "refreshAccountToken",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CodexAuthService_refreshAccountToken_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CodexAuthService_refreshAccountToken_Results_Future{Future: ans.Future()}, release

}

func (c CodexAuthService) RevokeToken(ctx context.Context, params func(CodexAuthService_revokeToken_Params) error) (CodexAuthService_revokeToken_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      3,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "revokeToken",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CodexAuthService_revokeToken_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CodexAuthService_revokeToken_Results_Future{Future: ans.Future()}, release

}

func (c CodexAuthService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c CodexAuthService) String() string {
	return "CodexAuthService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c CodexAuthService) AddRef() CodexAuthService {
	return CodexAuthService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c CodexAuthService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c CodexAuthService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c CodexAuthService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CodexAuthService) DecodeFromPtr(p capnp.Ptr) CodexAuthService {
	return CodexAuthService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c CodexAuthService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c CodexAuthService) IsSame(other CodexAuthService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c CodexAuthService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c CodexAuthService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A CodexAuthService_Server is a CodexAuthService with a local implementation.
type CodexAuthService_Server interface {
	StartLogin(context.Context, CodexAuthService_startLogin) error

	CompleteLogin(context.Context, CodexAuthService_completeLogin) error

	RefreshAccountToken(context.Context, CodexAuthService_refreshAccountToken) error

	RevokeToken(context.Context, CodexAuthService_revokeToken) error
}

// CodexAuthService_NewServer creates a new Server from an implementation of CodexAuthService_Server.
func CodexAuthService_NewServer(s CodexAuthService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CodexAuthService_Methods(nil, s), s, c)
}

// CodexAuthService_ServerToClient creates a new Client from an implementation of CodexAuthService_Server.
// The caller is responsible for calling Release on the returned Client.
func CodexAuthService_ServerToClient(s CodexAuthService_Server) CodexAuthService {
	return CodexAuthService(capnp.NewClient(CodexAuthService_NewServer(s)))
}

// CodexAuthService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CodexAuthService_Methods(methods []server.Method, s CodexAuthService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      0,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "startLogin",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StartLogin(ctx, CodexAuthService_startLogin{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      1,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "completeLogin",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CompleteLogin(ctx, CodexAuthService_completeLogin{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      2,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "refreshAccountToken",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RefreshAccountToken(ctx, CodexAuthService_refreshAccountToken{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfa467d4512810ace,
			MethodID:      3,
			InterfaceName: "codex_auth.capnp:CodexAuthService",
			MethodName:    "revokeToken",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RevokeToken(ctx, CodexAuthService_revokeToken{call})
		},
	})

	return methods
}

// CodexAuthService_startLogin holds the state for a server call to CodexAuthService.startLogin.
// See server.Call for documentation.
type CodexAuthService_startLogin struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CodexAuthService_startLogin) Args() CodexAuthService_startLogin_Params {
	return CodexAuthService_startLogin_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CodexAuthService_startLogin) AllocResults() (CodexAuthService_startLogin_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CodexAuthService_startLogin_Results(r), err
}

// CodexAuthService_completeLogin holds the state for a server call to CodexAuthService.completeLogin.
// See server.Call for documentation.
type CodexAuthService_completeLogin struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CodexAuthService_completeLogin) Args() CodexAuthService_completeLogin_Params {
	return CodexAuthService_completeLogin_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CodexAuthService_completeLogin) AllocResults() (CodexAuthService_completeLogin_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 16, PointerCount: 8})
	return CodexAuthService_completeLogin_Results(r), err
}

// CodexAuthService_refreshAccountToken holds the state for a server call to CodexAuthService.refreshAccountToken.
// See server.Call for documentation.
type CodexAuthService_refreshAccountToken struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CodexAuthService_refreshAccountToken) Args() CodexAuthService_refreshAccountToken_Params {
	return CodexAuthService_refreshAccountToken_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CodexAuthService_refreshAccountToken) AllocResults() (CodexAuthService_refreshAccountToken_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 16, PointerCount: 4})
	return CodexAuthService_refreshAccountToken_Results(r), err
}

// CodexAuthService_revokeToken holds the state for a server call to CodexAuthService.revokeToken.
// See server.Call for documentation.
type CodexAuthService_revokeToken struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CodexAuthService_revokeToken) Args() CodexAuthService_revokeToken_Params {
	return CodexAuthService_revokeToken_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CodexAuthService_revokeToken) AllocResults() (CodexAuthService_revokeToken_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CodexAuthService_revokeToken_Results(r), err
}

// CodexAuthService_List is a list of CodexAuthService.
type CodexAuthService_List = capnp.CapList[CodexAuthService]

// NewCodexAuthService_List creates a new list of CodexAuthService.
func NewCodexAuthService_List(s *capnp.Segment, sz int32) (CodexAuthService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CodexAuthService](l), err
}

type CodexAuthService_startLogin_Params capnp.Struct

// CodexAuthService_startLogin_Params_TypeID is the unique identifier for the type CodexAuthService_startLogin_Params.
const CodexAuthService_startLogin_Params_TypeID = 0xce63532dcd967e3a

func NewCodexAuthService_startLogin_Params(s *capnp.Segment) (CodexAuthService_startLogin_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CodexAuthService_startLogin_Params(st), err
}

func NewRootCodexAuthService_startLogin_Params(s *capnp.Segment) (CodexAuthService_startLogin_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CodexAuthService_startLogin_Params(st), err
}

func ReadRootCodexAuthService_startLogin_Params(msg *capnp.Message) (CodexAuthService_startLogin_Params, error) {
	root, err := msg.Root()
	return CodexAuthService_startLogin_Params(root.Struct()), err
}

func (s CodexAuthService_startLogin_Params) String() string {
	str, _ := text.Marshal(0xce63532dcd967e3a, capnp.Struct(s))
	return str
}

func (s CodexAuthService_startLogin_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_startLogin_Params) DecodeFromPtr(p capnp.Ptr) CodexAuthService_startLogin_Params {
	return CodexAuthService_startLogin_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_startLogin_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_startLogin_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_startLogin_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_startLogin_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_startLogin_Params) RedirectUri() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_startLogin_Params) HasRedirectUri() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_startLogin_Params) RedirectUriBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_startLogin_Params) SetRedirectUri(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CodexAuthService_startLogin_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CodexAuthService_startLogin_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CodexAuthService_startLogin_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CodexAuthService_startLogin_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CodexAuthService_startLogin_Params_List is a list of CodexAuthService_startLogin_Params.
type CodexAuthService_startLogin_Params_List = capnp.StructList[CodexAuthService_startLogin_Params]

// NewCodexAuthService_startLogin_Params creates a new list of CodexAuthService_startLogin_Params.
func NewCodexAuthService_startLogin_Params_List(s *capnp.Segment, sz int32) (CodexAuthService_startLogin_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CodexAuthService_startLogin_Params](l), err
}

// CodexAuthService_startLogin_Params_Future is a wrapper for a CodexAuthService_startLogin_Params promised by a client call.
type CodexAuthService_startLogin_Params_Future struct{ *capnp.Future }

func (f CodexAuthService_startLogin_Params_Future) Struct() (CodexAuthService_startLogin_Params, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_startLogin_Params(p.Struct()), err
}

type CodexAuthService_startLogin_Results capnp.Struct

// CodexAuthService_startLogin_Results_TypeID is the unique identifier for the type CodexAuthService_startLogin_Results.
const CodexAuthService_startLogin_Results_TypeID = 0x9ab7ab6682b87847

func NewCodexAuthService_startLogin_Results(s *capnp.Segment) (CodexAuthService_startLogin_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CodexAuthService_startLogin_Results(st), err
}

func NewRootCodexAuthService_startLogin_Results(s *capnp.Segment) (CodexAuthService_startLogin_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CodexAuthService_startLogin_Results(st), err
}

func ReadRootCodexAuthService_startLogin_Results(msg *capnp.Message) (CodexAuthService_startLogin_Results, error) {
	root, err := msg.Root()
	return CodexAuthService_startLogin_Results(root.Struct()), err
}

func (s CodexAuthService_startLogin_Results) String() string {
	str, _ := text.Marshal(0x9ab7ab6682b87847, capnp.Struct(s))
	return str
}

func (s CodexAuthService_startLogin_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_startLogin_Results) DecodeFromPtr(p capnp.Ptr) CodexAuthService_startLogin_Results {
	return CodexAuthService_startLogin_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_startLogin_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_startLogin_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_startLogin_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_startLogin_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_startLogin_Results) AuthUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_startLogin_Results) HasAuthUrl() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_startLogin_Results) AuthUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_startLogin_Results) SetAuthUrl(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CodexAuthService_startLogin_Results) SessionId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CodexAuthService_startLogin_Results) HasSessionId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CodexAuthService_startLogin_Results) SessionIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CodexAuthService_startLogin_Results) SetSessionId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CodexAuthService_startLogin_Results_List is a list of CodexAuthService_startLogin_Results.
type CodexAuthService_startLogin_Results_List = capnp.StructList[CodexAuthService_startLogin_Results]

// NewCodexAuthService_startLogin_Results creates a new list of CodexAuthService_startLogin_Results.
func NewCodexAuthService_startLogin_Results_List(s *capnp.Segment, sz int32) (CodexAuthService_startLogin_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CodexAuthService_startLogin_Results](l), err
}

// CodexAuthService_startLogin_Results_Future is a wrapper for a CodexAuthService_startLogin_Results promised by a client call.
type CodexAuthService_startLogin_Results_Future struct{ *capnp.Future }

func (f CodexAuthService_startLogin_Results_Future) Struct() (CodexAuthService_startLogin_Results, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_startLogin_Results(p.Struct()), err
}

type CodexAuthService_completeLogin_Params capnp.Struct

// CodexAuthService_completeLogin_Params_TypeID is the unique identifier for the type CodexAuthService_completeLogin_Params.
const CodexAuthService_completeLogin_Params_TypeID = 0xbc2a075d5524b19f

func NewCodexAuthService_completeLogin_Params(s *capnp.Segment) (CodexAuthService_completeLogin_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CodexAuthService_completeLogin_Params(st), err
}

func NewRootCodexAuthService_completeLogin_Params(s *capnp.Segment) (CodexAuthService_completeLogin_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CodexAuthService_completeLogin_Params(st), err
}

func ReadRootCodexAuthService_completeLogin_Params(msg *capnp.Message) (CodexAuthService_completeLogin_Params, error) {
	root, err := msg.Root()
	return CodexAuthService_completeLogin_Params(root.Struct()), err
}

func (s CodexAuthService_completeLogin_Params) String() string {
	str, _ := text.Marshal(0xbc2a075d5524b19f, capnp.Struct(s))
	return str
}

func (s CodexAuthService_completeLogin_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_completeLogin_Params) DecodeFromPtr(p capnp.Ptr) CodexAuthService_completeLogin_Params {
	return CodexAuthService_completeLogin_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_completeLogin_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_completeLogin_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_completeLogin_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_completeLogin_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_completeLogin_Params) SessionId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Params) HasSessionId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_completeLogin_Params) SessionIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Params) SetSessionId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CodexAuthService_completeLogin_Params) Code() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Params) HasCode() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CodexAuthService_completeLogin_Params) CodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Params) SetCode(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CodexAuthService_completeLogin_Params_List is a list of CodexAuthService_completeLogin_Params.
type CodexAuthService_completeLogin_Params_List = capnp.StructList[CodexAuthService_completeLogin_Params]

// NewCodexAuthService_completeLogin_Params creates a new list of CodexAuthService_completeLogin_Params.
func NewCodexAuthService_completeLogin_Params_List(s *capnp.Segment, sz int32) (CodexAuthService_completeLogin_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CodexAuthService_completeLogin_Params](l), err
}

// CodexAuthService_completeLogin_Params_Future is a wrapper for a CodexAuthService_completeLogin_Params promised by a client call.
type CodexAuthService_completeLogin_Params_Future struct{ *capnp.Future }

func (f CodexAuthService_completeLogin_Params_Future) Struct() (CodexAuthService_completeLogin_Params, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_completeLogin_Params(p.Struct()), err
}

type CodexAuthService_completeLogin_Results capnp.Struct

// CodexAuthService_completeLogin_Results_TypeID is the unique identifier for the type CodexAuthService_completeLogin_Results.
const CodexAuthService_completeLogin_Results_TypeID = 0xc99f674f821f3d74

func NewCodexAuthService_completeLogin_Results(s *capnp.Segment) (CodexAuthService_completeLogin_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8})
	return CodexAuthService_completeLogin_Results(st), err
}

func NewRootCodexAuthService_completeLogin_Results(s *capnp.Segment) (CodexAuthService_completeLogin_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8})
	return CodexAuthService_completeLogin_Results(st), err
}

func ReadRootCodexAuthService_completeLogin_Results(msg *capnp.Message) (CodexAuthService_completeLogin_Results, error) {
	root, err := msg.Root()
	return CodexAuthService_completeLogin_Results(root.Struct()), err
}

func (s CodexAuthService_completeLogin_Results) String() string {
	str, _ := text.Marshal(0xc99f674f821f3d74, capnp.Struct(s))
	return str
}

func (s CodexAuthService_completeLogin_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_completeLogin_Results) DecodeFromPtr(p capnp.Ptr) CodexAuthService_completeLogin_Results {
	return CodexAuthService_completeLogin_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_completeLogin_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_completeLogin_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_completeLogin_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_completeLogin_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_completeLogin_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CodexAuthService_completeLogin_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s CodexAuthService_completeLogin_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_completeLogin_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CodexAuthService_completeLogin_Results) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CodexAuthService_completeLogin_Results) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CodexAuthService_completeLogin_Results) AccessToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasAccessToken() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CodexAuthService_completeLogin_Results) AccessTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetAccessToken(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s CodexAuthService_completeLogin_Results) RefreshToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasRefreshToken() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CodexAuthService_completeLogin_Results) RefreshTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetRefreshToken(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s CodexAuthService_completeLogin_Results) IdToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasIdToken() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s CodexAuthService_completeLogin_Results) IdTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetIdToken(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s CodexAuthService_completeLogin_Results) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s CodexAuthService_completeLogin_Results) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s CodexAuthService_completeLogin_Results) ChatgptAccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasChatgptAccountId() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s CodexAuthService_completeLogin_Results) ChatgptAccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetChatgptAccountId(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s CodexAuthService_completeLogin_Results) Email() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasEmail() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s CodexAuthService_completeLogin_Results) EmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetEmail(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s CodexAuthService_completeLogin_Results) PlanType() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s CodexAuthService_completeLogin_Results) HasPlanType() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s CodexAuthService_completeLogin_Results) PlanTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s CodexAuthService_completeLogin_Results) SetPlanType(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

// CodexAuthService_completeLogin_Results_List is a list of CodexAuthService_completeLogin_Results.
type CodexAuthService_completeLogin_Results_List = capnp.StructList[CodexAuthService_completeLogin_Results]

// NewCodexAuthService_completeLogin_Results creates a new list of CodexAuthService_completeLogin_Results.
func NewCodexAuthService_completeLogin_Results_List(s *capnp.Segment, sz int32) (CodexAuthService_completeLogin_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8}, sz)
	return capnp.StructList[CodexAuthService_completeLogin_Results](l), err
}

// CodexAuthService_completeLogin_Results_Future is a wrapper for a CodexAuthService_completeLogin_Results promised by a client call.
type CodexAuthService_completeLogin_Results_Future struct{ *capnp.Future }

func (f CodexAuthService_completeLogin_Results_Future) Struct() (CodexAuthService_completeLogin_Results, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_completeLogin_Results(p.Struct()), err
}

type CodexAuthService_refreshAccountToken_Params capnp.Struct

// CodexAuthService_refreshAccountToken_Params_TypeID is the unique identifier for the type CodexAuthService_refreshAccountToken_Params.
const CodexAuthService_refreshAccountToken_Params_TypeID = 0xb2878bff13b9e66a

func NewCodexAuthService_refreshAccountToken_Params(s *capnp.Segment) (CodexAuthService_refreshAccountToken_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CodexAuthService_refreshAccountToken_Params(st), err
}

func NewRootCodexAuthService_refreshAccountToken_Params(s *capnp.Segment) (CodexAuthService_refreshAccountToken_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CodexAuthService_refreshAccountToken_Params(st), err
}

func ReadRootCodexAuthService_refreshAccountToken_Params(msg *capnp.Message) (CodexAuthService_refreshAccountToken_Params, error) {
	root, err := msg.Root()
	return CodexAuthService_refreshAccountToken_Params(root.Struct()), err
}

func (s CodexAuthService_refreshAccountToken_Params) String() string {
	str, _ := text.Marshal(0xb2878bff13b9e66a, capnp.Struct(s))
	return str
}

func (s CodexAuthService_refreshAccountToken_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_refreshAccountToken_Params) DecodeFromPtr(p capnp.Ptr) CodexAuthService_refreshAccountToken_Params {
	return CodexAuthService_refreshAccountToken_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_refreshAccountToken_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_refreshAccountToken_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_refreshAccountToken_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_refreshAccountToken_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_refreshAccountToken_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_refreshAccountToken_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_refreshAccountToken_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_refreshAccountToken_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CodexAuthService_refreshAccountToken_Params_List is a list of CodexAuthService_refreshAccountToken_Params.
type CodexAuthService_refreshAccountToken_Params_List = capnp.StructList[CodexAuthService_refreshAccountToken_Params]

// NewCodexAuthService_refreshAccountToken_Params creates a new list of CodexAuthService_refreshAccountToken_Params.
func NewCodexAuthService_refreshAccountToken_Params_List(s *capnp.Segment, sz int32) (CodexAuthService_refreshAccountToken_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CodexAuthService_refreshAccountToken_Params](l), err
}

// CodexAuthService_refreshAccountToken_Params_Future is a wrapper for a CodexAuthService_refreshAccountToken_Params promised by a client call.
type CodexAuthService_refreshAccountToken_Params_Future struct{ *capnp.Future }

func (f CodexAuthService_refreshAccountToken_Params_Future) Struct() (CodexAuthService_refreshAccountToken_Params, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_refreshAccountToken_Params(p.Struct()), err
}

type CodexAuthService_refreshAccountToken_Results capnp.Struct

// CodexAuthService_refreshAccountToken_Results_TypeID is the unique identifier for the type CodexAuthService_refreshAccountToken_Results.
const CodexAuthService_refreshAccountToken_Results_TypeID = 0x8b90d6220acf2511

func NewCodexAuthService_refreshAccountToken_Results(s *capnp.Segment) (CodexAuthService_refreshAccountToken_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4})
	return CodexAuthService_refreshAccountToken_Results(st), err
}

func NewRootCodexAuthService_refreshAccountToken_Results(s *capnp.Segment) (CodexAuthService_refreshAccountToken_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4})
	return CodexAuthService_refreshAccountToken_Results(st), err
}

func ReadRootCodexAuthService_refreshAccountToken_Results(msg *capnp.Message) (CodexAuthService_refreshAccountToken_Results, error) {
	root, err := msg.Root()
	return CodexAuthService_refreshAccountToken_Results(root.Struct()), err
}

func (s CodexAuthService_refreshAccountToken_Results) String() string {
	str, _ := text.Marshal(0x8b90d6220acf2511, capnp.Struct(s))
	return str
}

func (s CodexAuthService_refreshAccountToken_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_refreshAccountToken_Results) DecodeFromPtr(p capnp.Ptr) CodexAuthService_refreshAccountToken_Results {
	return CodexAuthService_refreshAccountToken_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_refreshAccountToken_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_refreshAccountToken_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_refreshAccountToken_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_refreshAccountToken_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_refreshAccountToken_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CodexAuthService_refreshAccountToken_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s CodexAuthService_refreshAccountToken_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_refreshAccountToken_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_refreshAccountToken_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_refreshAccountToken_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CodexAuthService_refreshAccountToken_Results) AccessToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CodexAuthService_refreshAccountToken_Results) HasAccessToken() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CodexAuthService_refreshAccountToken_Results) AccessTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CodexAuthService_refreshAccountToken_Results) SetAccessToken(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CodexAuthService_refreshAccountToken_Results) RefreshToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s CodexAuthService_refreshAccountToken_Results) HasRefreshToken() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CodexAuthService_refreshAccountToken_Results) RefreshTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s CodexAuthService_refreshAccountToken_Results) SetRefreshToken(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s CodexAuthService_refreshAccountToken_Results) IdToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s CodexAuthService_refreshAccountToken_Results) HasIdToken() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CodexAuthService_refreshAccountToken_Results) IdTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s CodexAuthService_refreshAccountToken_Results) SetIdToken(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s CodexAuthService_refreshAccountToken_Results) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s CodexAuthService_refreshAccountToken_Results) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// CodexAuthService_refreshAccountToken_Results_List is a list of CodexAuthService_refreshAccountToken_Results.
type CodexAuthService_refreshAccountToken_Results_List = capnp.StructList[CodexAuthService_refreshAccountToken_Results]

// NewCodexAuthService_refreshAccountToken_Results creates a new list of CodexAuthService_refreshAccountToken_Results.
func NewCodexAuthService_refreshAccountToken_Results_List(s *capnp.Segment, sz int32) (CodexAuthService_refreshAccountToken_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4}, sz)
	return capnp.StructList[CodexAuthService_refreshAccountToken_Results](l), err
}

// CodexAuthService_refreshAccountToken_Results_Future is a wrapper for a CodexAuthService_refreshAccountToken_Results promised by a client call.
type CodexAuthService_refreshAccountToken_Results_Future struct{ *capnp.Future }

func (f CodexAuthService_refreshAccountToken_Results_Future) Struct() (CodexAuthService_refreshAccountToken_Results, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_refreshAccountToken_Results(p.Struct()), err
}

type CodexAuthService_revokeToken_Params capnp.Struct

// CodexAuthService_revokeToken_Params_TypeID is the unique identifier for the type CodexAuthService_revokeToken_Params.
const CodexAuthService_revokeToken_Params_TypeID = 0xbbd01594974b10a3

func NewCodexAuthService_revokeToken_Params(s *capnp.Segment) (CodexAuthService_revokeToken_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CodexAuthService_revokeToken_Params(st), err
}

func NewRootCodexAuthService_revokeToken_Params(s *capnp.Segment) (CodexAuthService_revokeToken_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CodexAuthService_revokeToken_Params(st), err
}

func ReadRootCodexAuthService_revokeToken_Params(msg *capnp.Message) (CodexAuthService_revokeToken_Params, error) {
	root, err := msg.Root()
	return CodexAuthService_revokeToken_Params(root.Struct()), err
}

func (s CodexAuthService_revokeToken_Params) String() string {
	str, _ := text.Marshal(0xbbd01594974b10a3, capnp.Struct(s))
	return str
}

func (s CodexAuthService_revokeToken_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_revokeToken_Params) DecodeFromPtr(p capnp.Ptr) CodexAuthService_revokeToken_Params {
	return CodexAuthService_revokeToken_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_revokeToken_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_revokeToken_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_revokeToken_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_revokeToken_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_revokeToken_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_revokeToken_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_revokeToken_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_revokeToken_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CodexAuthService_revokeToken_Params_List is a list of CodexAuthService_revokeToken_Params.
type CodexAuthService_revokeToken_Params_List = capnp.StructList[CodexAuthService_revokeToken_Params]

// NewCodexAuthService_revokeToken_Params creates a new list of CodexAuthService_revokeToken_Params.
func NewCodexAuthService_revokeToken_Params_List(s *capnp.Segment, sz int32) (CodexAuthService_revokeToken_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CodexAuthService_revokeToken_Params](l), err
}

// CodexAuthService_revokeToken_Params_Future is a wrapper for a CodexAuthService_revokeToken_Params promised by a client call.
type CodexAuthService_revokeToken_Params_Future struct{ *capnp.Future }

func (f CodexAuthService_revokeToken_Params_Future) Struct() (CodexAuthService_revokeToken_Params, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_revokeToken_Params(p.Struct()), err
}

type CodexAuthService_revokeToken_Results capnp.Struct

// CodexAuthService_revokeToken_Results_TypeID is the unique identifier for the type CodexAuthService_revokeToken_Results.
const CodexAuthService_revokeToken_Results_TypeID = 0xa55a3fa50853ca5b

func NewCodexAuthService_revokeToken_Results(s *capnp.Segment) (CodexAuthService_revokeToken_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CodexAuthService_revokeToken_Results(st), err
}

func NewRootCodexAuthService_revokeToken_Results(s *capnp.Segment) (CodexAuthService_revokeToken_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CodexAuthService_revokeToken_Results(st), err
}

func ReadRootCodexAuthService_revokeToken_Results(msg *capnp.Message) (CodexAuthService_revokeToken_Results, error) {
	root, err := msg.Root()
	return CodexAuthService_revokeToken_Results(root.Struct()), err
}

func (s CodexAuthService_revokeToken_Results) String() string {
	str, _ := text.Marshal(0xa55a3fa50853ca5b, capnp.Struct(s))
	return str
}

func (s CodexAuthService_revokeToken_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexAuthService_revokeToken_Results) DecodeFromPtr(p capnp.Ptr) CodexAuthService_revokeToken_Results {
	return CodexAuthService_revokeToken_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexAuthService_revokeToken_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexAuthService_revokeToken_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexAuthService_revokeToken_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexAuthService_revokeToken_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexAuthService_revokeToken_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CodexAuthService_revokeToken_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s CodexAuthService_revokeToken_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexAuthService_revokeToken_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexAuthService_revokeToken_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexAuthService_revokeToken_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CodexAuthService_revokeToken_Results_List is a list of CodexAuthService_revokeToken_Results.
type CodexAuthService_revokeToken_Results_List = capnp.StructList[CodexAuthService_revokeToken_Results]

// NewCodexAuthService_revokeToken_Results creates a new list of CodexAuthService_revokeToken_Results.
func NewCodexAuthService_revokeToken_Results_List(s *capnp.Segment, sz int32) (CodexAuthService_revokeToken_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[CodexAuthService_revokeToken_Results](l), err
}

// CodexAuthService_revokeToken_Results_Future is a wrapper for a CodexAuthService_revokeToken_Results promised by a client call.
type CodexAuthService_revokeToken_Results_Future struct{ *capnp.Future }

func (f CodexAuthService_revokeToken_Results_Future) Struct() (CodexAuthService_revokeToken_Results, error) {
	p, err := f.Future.Ptr()
	return CodexAuthService_revokeToken_Results(p.Struct()), err
}
