// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type CodexQueryService capnp.Client

// CodexQueryService_TypeID is the unique identifier for the type CodexQueryService.
const CodexQueryService_TypeID = 0x80e03a21568b6b78

func (c CodexQueryService) GetProfile(ctx context.Context, params func(CodexQueryService_getProfile_Params) error) (CodexQueryService_getProfile_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x80e03a21568b6b78,
			MethodID:      0,
			InterfaceName: "codex_query.capnp:CodexQueryService",
			MethodName:    "getProfile",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CodexQueryService_getProfile_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CodexQueryService_getProfile_Results_Future{Future: ans.Future()}, release

}

func (c CodexQueryService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c CodexQueryService) String() string {
	return "CodexQueryService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c CodexQueryService) AddRef() CodexQueryService {
	return CodexQueryService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c CodexQueryService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c CodexQueryService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c CodexQueryService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CodexQueryService) DecodeFromPtr(p capnp.Ptr) CodexQueryService {
	return CodexQueryService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c CodexQueryService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c CodexQueryService) IsSame(other CodexQueryService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c CodexQueryService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c CodexQueryService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A CodexQueryService_Server is a CodexQueryService with a local implementation.
type CodexQueryService_Server interface {
	GetProfile(context.Context, CodexQueryService_getProfile) error
}

// CodexQueryService_NewServer creates a new Server from an implementation of CodexQueryService_Server.
func CodexQueryService_NewServer(s CodexQueryService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CodexQueryService_Methods(nil, s), s, c)
}

// CodexQueryService_ServerToClient creates a new Client from an implementation of CodexQueryService_Server.
// The caller is responsible for calling Release on the returned Client.
func CodexQueryService_ServerToClient(s CodexQueryService_Server) CodexQueryService {
	return CodexQueryService(capnp.NewClient(CodexQueryService_NewServer(s)))
}

// CodexQueryService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CodexQueryService_Methods(methods []server.Method, s CodexQueryService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x80e03a21568b6b78,
			MethodID:      0,
			InterfaceName: "codex_query.capnp:CodexQueryService",
			MethodName:    "getProfile",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetProfile(ctx, CodexQueryService_getProfile{call})
		},
	})

	return methods
}

// CodexQueryService_getProfile holds the state for a server call to CodexQueryService.getProfile.
// See server.Call for documentation.
type CodexQueryService_getProfile struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CodexQueryService_getProfile) Args() CodexQueryService_getProfile_Params {
	return CodexQueryService_getProfile_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CodexQueryService_getProfile) AllocResults() (CodexQueryService_getProfile_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return CodexQueryService_getProfile_Results(r), err
}

// CodexQueryService_List is a list of CodexQueryService.
type CodexQueryService_List = capnp.CapList[CodexQueryService]

// NewCodexQueryService_List creates a new list of CodexQueryService.
func NewCodexQueryService_List(s *capnp.Segment, sz int32) (CodexQueryService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CodexQueryService](l), err
}

type CodexQueryService_getProfile_Params capnp.Struct

// CodexQueryService_getProfile_Params_TypeID is the unique identifier for the type CodexQueryService_getProfile_Params.
const CodexQueryService_getProfile_Params_TypeID = 0xfd8ebeafcb0da8d5

func NewCodexQueryService_getProfile_Params(s *capnp.Segment) (CodexQueryService_getProfile_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CodexQueryService_getProfile_Params(st), err
}

func NewRootCodexQueryService_getProfile_Params(s *capnp.Segment) (CodexQueryService_getProfile_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CodexQueryService_getProfile_Params(st), err
}

func ReadRootCodexQueryService_getProfile_Params(msg *capnp.Message) (CodexQueryService_getProfile_Params, error) {
	root, err := msg.Root()
	return CodexQueryService_getProfile_Params(root.Struct()), err
}

func (s CodexQueryService_getProfile_Params) String() string {
	str, _ := text.Marshal(0xfd8ebeafcb0da8d5, capnp.Struct(s))
	return str
}

func (s CodexQueryService_getProfile_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexQueryService_getProfile_Params) DecodeFromPtr(p capnp.Ptr) CodexQueryService_getProfile_Params {
	return CodexQueryService_getProfile_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexQueryService_getProfile_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexQueryService_getProfile_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexQueryService_getProfile_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexQueryService_getProfile_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexQueryService_getProfile_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexQueryService_getProfile_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexQueryService_getProfile_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexQueryService_getProfile_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CodexQueryService_getProfile_Params_List is a list of CodexQueryService_getProfile_Params.
type CodexQueryService_getProfile_Params_List = capnp.StructList[CodexQueryService_getProfile_Params]

// NewCodexQueryService_getProfile_Params creates a new list of CodexQueryService_getProfile_Params.
func NewCodexQueryService_getProfile_Params_List(s *capnp.Segment, sz int32) (CodexQueryService_getProfile_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CodexQueryService_getProfile_Params](l), err
}

// CodexQueryService_getProfile_Params_Future is a wrapper for a CodexQueryService_getProfile_Params promised by a client call.
type CodexQueryService_getProfile_Params_Future struct{ *capnp.Future }

func (f CodexQueryService_getProfile_Params_Future) Struct() (CodexQueryService_getProfile_Params, error) {
	p, err := f.Future.Ptr()
	return CodexQueryService_getProfile_Params(p.Struct()), err
}

type CodexQueryService_getProfile_Results capnp.Struct

// CodexQueryService_getProfile_Results_TypeID is the unique identifier for the type CodexQueryService_getProfile_Results.
const CodexQueryService_getProfile_Results_TypeID = 0xea24b3a205204e93

func NewCodexQueryService_getProfile_Results(s *capnp.Segment) (CodexQueryService_getProfile_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return CodexQueryService_getProfile_Results(st), err
}

func NewRootCodexQueryService_getProfile_Results(s *capnp.Segment) (CodexQueryService_getProfile_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return CodexQueryService_getProfile_Results(st), err
}

func ReadRootCodexQueryService_getProfile_Results(msg *capnp.Message) (CodexQueryService_getProfile_Results, error) {
	root, err := msg.Root()
	return CodexQueryService_getProfile_Results(root.Struct()), err
}

func (s CodexQueryService_getProfile_Results) String() string {
	str, _ := text.Marshal(0xea24b3a205204e93, capnp.Struct(s))
	return str
}

func (s CodexQueryService_getProfile_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CodexQueryService_getProfile_Results) DecodeFromPtr(p capnp.Ptr) CodexQueryService_getProfile_Results {
	return CodexQueryService_getProfile_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CodexQueryService_getProfile_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CodexQueryService_getProfile_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CodexQueryService_getProfile_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CodexQueryService_getProfile_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CodexQueryService_getProfile_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CodexQueryService_getProfile_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s CodexQueryService_getProfile_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CodexQueryService_getProfile_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CodexQueryService_getProfile_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CodexQueryService_getProfile_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CodexQueryService_getProfile_Results) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CodexQueryService_getProfile_Results) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CodexQueryService_getProfile_Results) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CodexQueryService_getProfile_Results) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CodexQueryService_getProfile_Results) ChatgptAccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s CodexQueryService_getProfile_Results) HasChatgptAccountId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CodexQueryService_getProfile_Results) ChatgptAccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s CodexQueryService_getProfile_Results) SetChatgptAccountId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s CodexQueryService_getProfile_Results) Email() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s CodexQueryService_getProfile_Results) HasEmail() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CodexQueryService_getProfile_Results) EmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s CodexQueryService_getProfile_Results) SetEmail(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s CodexQueryService_getProfile_Results) PlanType() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s CodexQueryService_getProfile_Results) HasPlanType() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s CodexQueryService_getProfile_Results) PlanTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s CodexQueryService_getProfile_Results) SetPlanType(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

// CodexQueryService_getProfile_Results_List is a list of CodexQueryService_getProfile_Results.
type CodexQueryService_getProfile_Results_List = capnp.StructList[CodexQueryService_getProfile_Results]

// NewCodexQueryService_getProfile_Results creates a new list of CodexQueryService_getProfile_Results.
func NewCodexQueryService_getProfile_Results_List(s *capnp.Segment, sz int32) (CodexQueryService_getProfile_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5}, sz)
	return capnp.StructList[CodexQueryService_getProfile_Results](l), err
}

// CodexQueryService_getProfile_Results_Future is a wrapper for a CodexQueryService_getProfile_Results promised by a client call.
type CodexQueryService_getProfile_Results_Future struct{ *capnp.Future }

func (f CodexQueryService_getProfile_Results_Future) Struct() (CodexQueryService_getProfile_Results, error) {
	p, err := f.Future.Ptr()
	return CodexQueryService_getProfile_Results(p.Struct()), err
}
