// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
)

type ProxyInfo capnp.Struct

// ProxyInfo_TypeID is the unique identifier for the type ProxyInfo.
const ProxyInfo_TypeID = 0x9c8046fbc9ccf744

func NewProxyInfo(s *capnp.Segment) (ProxyInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 8})
	return ProxyInfo(st), err
}

func NewRootProxyInfo(s *capnp.Segment) (ProxyInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 8})
	return ProxyInfo(st), err
}

func ReadRootProxyInfo(msg *capnp.Message) (ProxyInfo, error) {
	root, err := msg.Root()
	return ProxyInfo(root.Struct()), err
}

func (s ProxyInfo) String() string {
	str, _ := text.Marshal(0x9c8046fbc9ccf744, capnp.Struct(s))
	return str
}

func (s ProxyInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProxyInfo) DecodeFromPtr(p capnp.Ptr) ProxyInfo {
	return ProxyInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProxyInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProxyInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProxyInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProxyInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProxyInfo) Ip() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProxyInfo) HasIp() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProxyInfo) IpBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetIp(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ProxyInfo) Country() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ProxyInfo) HasCountry() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProxyInfo) CountryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetCountry(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ProxyInfo) Region() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ProxyInfo) HasRegion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ProxyInfo) RegionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetRegion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ProxyInfo) City() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ProxyInfo) HasCity() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ProxyInfo) CityBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetCity(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ProxyInfo) Continent() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ProxyInfo) HasContinent() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ProxyInfo) ContinentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetContinent(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ProxyInfo) Asn() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ProxyInfo) SetAsn(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s ProxyInfo) AsOrganization() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s ProxyInfo) HasAsOrganization() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ProxyInfo) AsOrganizationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetAsOrganization(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s ProxyInfo) Colo() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s ProxyInfo) HasColo() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s ProxyInfo) ColoBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetColo(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s ProxyInfo) Timezone() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s ProxyInfo) HasTimezone() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s ProxyInfo) TimezoneBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s ProxyInfo) SetTimezone(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

// ProxyInfo_List is a list of ProxyInfo.
type ProxyInfo_List = capnp.StructList[ProxyInfo]

// NewProxyInfo creates a new list of ProxyInfo.
func NewProxyInfo_List(s *capnp.Segment, sz int32) (ProxyInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 8}, sz)
	return capnp.StructList[ProxyInfo](l), err
}

// ProxyInfo_Future is a wrapper for a ProxyInfo promised by a client call.
type ProxyInfo_Future struct{ *capnp.Future }

func (f ProxyInfo_Future) Struct() (ProxyInfo, error) {
	p, err := f.Future.Ptr()
	return ProxyInfo(p.Struct()), err
}

type ProbeTiming capnp.Struct

// ProbeTiming_TypeID is the unique identifier for the type ProbeTiming.
const ProbeTiming_TypeID = 0x92600b6ece7a8651

func NewProbeTiming(s *capnp.Segment) (ProbeTiming, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 0})
	return ProbeTiming(st), err
}

func NewRootProbeTiming(s *capnp.Segment) (ProbeTiming, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 0})
	return ProbeTiming(st), err
}

func ReadRootProbeTiming(msg *capnp.Message) (ProbeTiming, error) {
	root, err := msg.Root()
	return ProbeTiming(root.Struct()), err
}

func (s ProbeTiming) String() string {
	str, _ := text.Marshal(0x92600b6ece7a8651, capnp.Struct(s))
	return str
}

func (s ProbeTiming) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProbeTiming) DecodeFromPtr(p capnp.Ptr) ProbeTiming {
	return ProbeTiming(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProbeTiming) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProbeTiming) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProbeTiming) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProbeTiming) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProbeTiming) ClientBuildUs() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s ProbeTiming) SetClientBuildUs(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s ProbeTiming) RequestSendMs() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s ProbeTiming) SetRequestSendMs(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s ProbeTiming) BodyReadUs() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s ProbeTiming) SetBodyReadUs(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s ProbeTiming) JsonParseUs() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s ProbeTiming) SetJsonParseUs(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s ProbeTiming) TotalMs() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s ProbeTiming) SetTotalMs(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s ProbeTiming) BodyLen() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s ProbeTiming) SetBodyLen(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

// ProbeTiming_List is a list of ProbeTiming.
type ProbeTiming_List = capnp.StructList[ProbeTiming]

// NewProbeTiming creates a new list of ProbeTiming.
func NewProbeTiming_List(s *capnp.Segment, sz int32) (ProbeTiming_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 0}, sz)
	return capnp.StructList[ProbeTiming](l), err
}

// ProbeTiming_Future is a wrapper for a ProbeTiming promised by a client call.
type ProbeTiming_Future struct{ *capnp.Future }

func (f ProbeTiming_Future) Struct() (ProbeTiming, error) {
	p, err := f.Future.Ptr()
	return ProbeTiming(p.Struct()), err
}
