// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type ProxyService capnp.Client

// ProxyService_TypeID is the unique identifier for the type ProxyService.
const ProxyService_TypeID = 0xe229b70fcd90a51f

func (c ProxyService) ProbeProxy(ctx context.Context, params func(ProxyService_probeProxy_Params) error) (ProxyService_probeProxy_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe229b70fcd90a51f,
			MethodID:      0,
			InterfaceName: "proxy.capnp:ProxyService",
			MethodName:    "probeProxy",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ProxyService_probeProxy_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ProxyService_probeProxy_Results_Future{Future: ans.Future()}, release

}

func (c ProxyService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c ProxyService) String() string {
	return "ProxyService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c ProxyService) AddRef() ProxyService {
	return ProxyService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c ProxyService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c ProxyService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c ProxyService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (ProxyService) DecodeFromPtr(p capnp.Ptr) ProxyService {
	return ProxyService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c ProxyService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c ProxyService) IsSame(other ProxyService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c ProxyService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c ProxyService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A ProxyService_Server is a ProxyService with a local implementation.
type ProxyService_Server interface {
	ProbeProxy(context.Context, ProxyService_probeProxy) error
}

// ProxyService_NewServer creates a new Server from an implementation of ProxyService_Server.
func ProxyService_NewServer(s ProxyService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ProxyService_Methods(nil, s), s, c)
}

// ProxyService_ServerToClient creates a new Client from an implementation of ProxyService_Server.
// The caller is responsible for calling Release on the returned Client.
func ProxyService_ServerToClient(s ProxyService_Server) ProxyService {
	return ProxyService(capnp.NewClient(ProxyService_NewServer(s)))
}

// ProxyService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ProxyService_Methods(methods []server.Method, s ProxyService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe229b70fcd90a51f,
			MethodID:      0,
			InterfaceName: "proxy.capnp:ProxyService",
			MethodName:    "probeProxy",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ProbeProxy(ctx, ProxyService_probeProxy{call})
		},
	})

	return methods
}

// ProxyService_probeProxy holds the state for a server call to ProxyService.probeProxy.
// See server.Call for documentation.
type ProxyService_probeProxy struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ProxyService_probeProxy) Args() ProxyService_probeProxy_Params {
	return ProxyService_probeProxy_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ProxyService_probeProxy) AllocResults() (ProxyService_probeProxy_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ProxyService_probeProxy_Results(r), err
}

// ProxyService_List is a list of ProxyService.
type ProxyService_List = capnp.CapList[ProxyService]

// NewProxyService_List creates a new list of ProxyService.
func NewProxyService_List(s *capnp.Segment, sz int32) (ProxyService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[ProxyService](l), err
}

type ProxyService_probeProxy_Params capnp.Struct

// ProxyService_probeProxy_Params_TypeID is the unique identifier for the type ProxyService_probeProxy_Params.
const ProxyService_probeProxy_Params_TypeID = 0xe841b7d32f4306f9

func NewProxyService_probeProxy_Params(s *capnp.Segment) (ProxyService_probeProxy_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ProxyService_probeProxy_Params(st), err
}

func NewRootProxyService_probeProxy_Params(s *capnp.Segment) (ProxyService_probeProxy_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ProxyService_probeProxy_Params(st), err
}

func ReadRootProxyService_probeProxy_Params(msg *capnp.Message) (ProxyService_probeProxy_Params, error) {
	root, err := msg.Root()
	return ProxyService_probeProxy_Params(root.Struct()), err
}

func (s ProxyService_probeProxy_Params) String() string {
	str, _ := text.Marshal(0xe841b7d32f4306f9, capnp.Struct(s))
	return str
}

func (s ProxyService_probeProxy_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProxyService_probeProxy_Params) DecodeFromPtr(p capnp.Ptr) ProxyService_probeProxy_Params {
	return ProxyService_probeProxy_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProxyService_probeProxy_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProxyService_probeProxy_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProxyService_probeProxy_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProxyService_probeProxy_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProxyService_probeProxy_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProxyService_probeProxy_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProxyService_probeProxy_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProxyService_probeProxy_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ProxyService_probeProxy_Params_List is a list of ProxyService_probeProxy_Params.
type ProxyService_probeProxy_Params_List = capnp.StructList[ProxyService_probeProxy_Params]

// NewProxyService_probeProxy_Params creates a new list of ProxyService_probeProxy_Params.
func NewProxyService_probeProxy_Params_List(s *capnp.Segment, sz int32) (ProxyService_probeProxy_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ProxyService_probeProxy_Params](l), err
}

// ProxyService_probeProxy_Params_Future is a wrapper for a ProxyService_probeProxy_Params promised by a client call.
type ProxyService_probeProxy_Params_Future struct{ *capnp.Future }

func (f ProxyService_probeProxy_Params_Future) Struct() (ProxyService_probeProxy_Params, error) {
	p, err := f.Future.Ptr()
	return ProxyService_probeProxy_Params(p.Struct()), err
}

type ProxyService_probeProxy_Results capnp.Struct

// ProxyService_probeProxy_Results_TypeID is the unique identifier for the type ProxyService_probeProxy_Results.
const ProxyService_probeProxy_Results_TypeID = 0x8873f9097b095502

func NewProxyService_probeProxy_Results(s *capnp.Segment) (ProxyService_probeProxy_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ProxyService_probeProxy_Results(st), err
}

func NewRootProxyService_probeProxy_Results(s *capnp.Segment) (ProxyService_probeProxy_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ProxyService_probeProxy_Results(st), err
}

func ReadRootProxyService_probeProxy_Results(msg *capnp.Message) (ProxyService_probeProxy_Results, error) {
	root, err := msg.Root()
	return ProxyService_probeProxy_Results(root.Struct()), err
}

func (s ProxyService_probeProxy_Results) String() string {
	str, _ := text.Marshal(0x8873f9097b095502, capnp.Struct(s))
	return str
}

func (s ProxyService_probeProxy_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProxyService_probeProxy_Results) DecodeFromPtr(p capnp.Ptr) ProxyService_probeProxy_Results {
	return ProxyService_probeProxy_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProxyService_probeProxy_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProxyService_probeProxy_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProxyService_probeProxy_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProxyService_probeProxy_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProxyService_probeProxy_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ProxyService_probeProxy_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ProxyService_probeProxy_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProxyService_probeProxy_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProxyService_probeProxy_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProxyService_probeProxy_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ProxyService_probeProxy_Results) ProxyInfo() (ProxyInfo, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return ProxyInfo(p.Struct()), err
}

func (s ProxyService_probeProxy_Results) HasProxyInfo() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProxyService_probeProxy_Results) SetProxyInfo(v ProxyInfo) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewProxyInfo sets the proxyInfo field to a newly
// allocated ProxyInfo struct, preferring placement in s's segment.
func (s ProxyService_probeProxy_Results) NewProxyInfo() (ProxyInfo, error) {
	ss, err := NewProxyInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ProxyInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ProxyService_probeProxy_Results) Timing() (ProbeTiming, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return ProbeTiming(p.Struct()), err
}

func (s ProxyService_probeProxy_Results) HasTiming() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ProxyService_probeProxy_Results) SetTiming(v ProbeTiming) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewTiming sets the timing field to a newly
// allocated ProbeTiming struct, preferring placement in s's segment.
func (s ProxyService_probeProxy_Results) NewTiming() (ProbeTiming, error) {
	ss, err := NewProbeTiming(capnp.Struct(s).Segment())
	if err != nil {
		return ProbeTiming{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ProxyService_probeProxy_Results_List is a list of ProxyService_probeProxy_Results.
type ProxyService_probeProxy_Results_List = capnp.StructList[ProxyService_probeProxy_Results]

// NewProxyService_probeProxy_Results creates a new list of ProxyService_probeProxy_Results.
func NewProxyService_probeProxy_Results_List(s *capnp.Segment, sz int32) (ProxyService_probeProxy_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[ProxyService_probeProxy_Results](l), err
}

// ProxyService_probeProxy_Results_Future is a wrapper for a ProxyService_probeProxy_Results promised by a client call.
type ProxyService_probeProxy_Results_Future struct{ *capnp.Future }

func (f ProxyService_probeProxy_Results_Future) Struct() (ProxyService_probeProxy_Results, error) {
	p, err := f.Future.Ptr()
	return ProxyService_probeProxy_Results(p.Struct()), err
}
func (p ProxyService_probeProxy_Results_Future) ProxyInfo() ProxyInfo_Future {
	return ProxyInfo_Future{Future: p.Future.Field(1, nil)}
}
func (p ProxyService_probeProxy_Results_Future) Timing() ProbeTiming_Future {
	return ProbeTiming_Future{Future: p.Future.Field(2, nil)}
}
